common.config
=> Updated page id for opportunity response to use new MyResponses page.

crds-angular/app/crossroads.net/register/register_controller.js, crds-angular/app/modules/profile/profile_controller.js
little fix that Lakshmi just noticed
=> US904 Added global notification to profile account

crds-angular/app/crossroads.net/login/login_controller.js, crds-angular/app/crossroads.net/login/login_form.html, crds-angular/app/crossroads.net/login/login_form_directive.js, crds-angular/app/crossroads.net/register/register_controller.js, crds-angular/app/crossroads.net/register/register_form.html, crds-angular/app/modules/password_field/password_field.html, crds-angular/app/modules/password_field/password_field_directive.js, crds-angular/app/modules/profile/profile_controller.js, crds-angular/app/modules/profile/templates/profile_account.html
* Added a new scope variable to the password directive to prefix the id of
the field
* Used that same prefix to id the link
* Cleaned up some comments and logging
=> DE72 - Refactor password for easier testing

crds-angular/app/modules/profile/personal/profile_personal_controller.js
*Added the scope variable passwordPrefix in the
profile_personal_controller.js
=> DE77 Account Page Password Unique ID

crds-angular/app/crossroads.net/login/login_form.html, crds-angular/app/crossroads.net/register/register_form.html, crds-angular/app/modules/email_field/email_field.html, crds-angular/app/modules/email_field/email_field_directive.js, crds-angular/app/modules/profile/personal/profile_personal.html
@IngageMaddoxT can you review and merge this?
Each email field needed a unique id for testing purposes. I reused the
passwordPrefix scope variable
=> DE76 - Refactor email ids

crds-angular/app/crossroads.net/home/home.html, crds-angular/app/crossroads.net/routes.js, crds-angular/app/modules/profile/profile.html
=> Fix for multiple tabs in the DOM

crds-angular/app/crossroads.net/routes.js
*Made sure that '/' was the home route
=> US943 Refactor Routes for Authentication Routing

crossroads.net/styles/pages/atrium.scss
Per Tate (https://rally1.rallydev.com/#/27593764268d/detail/userstory/24467701533/discussion), removing background.
=> US300: Removed background color from atrium display

crossroads.net/app/routes.js
Fixing path expression for default route
=> US1044: Update path expression on default route

crossroads.net/app/app.js, crossroads.net/app/filters/index.js, crossroads.net/app/filters/time.filter.js, crossroads.net/app/my_serve/serveTabs.directive.js, crossroads.net/app/my_serve/serveTabs.html
Created a filter to address the incorrect time format
=> DE99 - Incorrect Time format

Gateway/crds-angular/Services/PersonService.cs
=> DE104 Added check to make sure event date is today or later

crossroads.net/app/app.config.js
Implemented fix @IngageMaddoxT found.
=> DE93: Possible fix for CORS issue

crossroads.net/app/my_serve/refine/refineList.directive.js, crossroads.net/app/my_serve/refine/refineList.html, crossroads.net/spec/my_serve/refineList.directive.spec.js
This is just adding the times to the filter section.
=> US1108 View unique serving times in filter

crossroads.net/app/my_serve/myserve.html, crossroads.net/app/my_serve/refine/refineList.directive.js, crossroads.net/spec/my_serve/refineList.directive.spec.js
Added `applyTimeFilter()` to `refineList` directive. Created method
called `filterAll()` which actually does the filtering when checking a
checkbox.
=> US1138 Filter opportunities by time

crossroads.net/app/profile/personal/profile_personal_controller.js, crossroads.net/app/profile/services/profile_reference_data.js
This ensures that profile data gets loaded each time the controller is instantiated.
=> DE119: Change ProfileReferenceData to be a non-singleton factory

crossroads.net/app/my_serve/refine/refineList.directive.js, crossroads.net/app/my_serve/refine/refineList.html, crossroads.net/spec/my_serve/refineList.directive.spec.js
Added method and test to clear filters
=> US1139 - Clear all filters

crossroads.net/app/community_groups_signup/group_signup_controller.js
=> DE130 Added logic to controller that handles 1 and 2 relationships

Gateway/crds-angular/Controllers/API/ServeController.cs, crossroads.net/app/my_serve/serveTeam.directive.js
client side: change string to date conversion using moment (known bug, https://github.com/moment/moment/issues/1407)
=> server side: added check for invalid date on save rsvp

.gitignore, crossroads.net/app/profile/personal/profile_personal.template.html
Removed preferred name help text.
=> Removed Help Text

crossroads.net/app/my_serve/serveTeam.html
=> flag for full changed

CI/SQL/DE151-UpdateGroupParticipantsAllWithContactIdSubPageView.sql
Correct column names (add underscores) and add Participant_ID column
=> DE151: Update the "All with ContactId" Groups Subpage View

crossroads.net/app/my_serve/filterState.service.js, crossroads.net/app/my_serve/myserve.controller.js, crossroads.net/app/my_serve/refine/refineList.directive.js, crossroads.net/app/my_serve/refine/refineList.html, crossroads.net/spec/my_serve/refineList.directive.spec.js
=> DE173 DE174 DE175 DE176 DE177 DE178

crossroads.net/app/my_serve/filterState.service.js, crossroads.net/app/my_serve/myserve.controller.js, crossroads.net/app/my_serve/myserve.html, crossroads.net/app/my_serve/refine/refineList.directive.js, crossroads.net/app/my_serve/refine/refineList.html
* Now sharing last filtered date with the refine directive
* Clicking LoadMore button updates last filtered date
* Changed layout of the filter, but still needs UI/UX to refine it
* Added 'apply' button to the Dates filter and moved submit logic to it
=> US1109 RefactorDateFilter

CI/SQL/DE168-UpdateEmailPage481.sql
=> DE168 Script for updated email page

crossroads.net/app/give/give_controller.js
Set the view to be "cc" for credit card when the default source is credit card.
=> setting the view to credit card if that is the default source

crossroads.net/app/email_field/email_field.html, crossroads.net/app/profile/personal/profile_personal.template.html, crossroads.net/app/register/register_form.html
I admit it is somewhat of a creative fix, but this was the only solution that worked for me.
=> DE191 Using ng-if to show email field with or without autofocus

Gateway/MinistryPlatform.Models/ContactRelationship.cs, Gateway/MinistryPlatform.Translation.Test/Services/ContactRelationshipServiceTest.cs, Gateway/MinistryPlatform.Translation/Services/ContactRelationshipService.cs, Gateway/crds-angular.test/Services/VolunteerApplicationServiceTest.cs, Gateway/crds-angular/Models/Crossroads/Serve/QualifiedServerDto.cs, Gateway/crds-angular/Services/ServeService.cs, Gateway/crds-angular/Services/VolunteerApplicationService.cs, Gateway/crds-angular/crds-angular.csproj, crossroads.net/app/volunteer_application/volunteerApplication.controller.js
=> DE228 & DE229

crossroads.net/styles/pages/corkboard.scss
Please review both crds-corkboard and crds-angular pull requests under Feature/US1502 view a post
=> US1502: Modify the layout of the corkboard image to be larger per UX.

crossroads.net/e2e/give/stateReset.e2e.js
Functionality is working after US1530, added functional test to verify.
=> US1534: Added functional test for checking reset state after register refresh

CI/SQL/DE252-AddEmailToPageView1058.sql
Adding a script that was overlooked
=> Script to add email address to page view 1058

crossroads.net/app/my_serve/refine/serveModal.controller.js, crossroads.net/spec/my_serve/serveModal.controller.spec.js
* We were using the wrong constructor for moment
=> DE280 - Date parsing

crossroads.net/app/my_serve/serveTeam.directive.js, crossroads.net/app/my_serve/serveTeam.html
* Added function to save initial state of the members tab
=> US1532 - Implement Cancel Button

crossroads.net/core/components/volunteer_applications/kc_student_application/kidsClubStudentApplication.template.html
=> US588-Removed grades for students too young to serve.

CI/SQL/US486-CreateDeclinedDonationsView.sql
Created the view in MP, extracted the SQL, then deleted the view and ran this script to test.
=> US486: Script Declined Donations View in MP

CI/TestSQL/QATEST_ACHUserAccount.sql, CI/TestSQL/QATEST_SeleniumEventRoomData.sql
For manual and automated tests.
=> Adding ACH test user plus scripted adding rooms for Atrium Screen

CI/SQL/US1546-02-AddProcessorTransferIdToBatches.sql, CI/SQL/US1546-03-AddProcessorTransferIdToBatchesPage.sql
Missed scripting this in initial commit
=> US1546: Add processor transfer id to batches

CI/SQL/US1629-DeclineEmailTemplate.sql
Correcting the communication ID.  Removing a bad sentence.
=> fixing the communiucation ID on the template

Gateway/MinistryPlatform.Translation/Services/DonationService.cs
I had the payment types reversed for bank and credit cards.
=> had bank and credit card payment types reversed

Gateway/crds-angular/Models/Json/StripeDateTimeConverter.cs
Updated code from Stripe.Net to serialize Date values properly (or at least with some consistency with the way they are deserialized...)
=> DE341: Fix crazy date serialization from Stripe.net

crossroads.net/app/gotrips/gotrips_controller.js, crossroads.net/app/gotrips/signup-page-1.html, crossroads.net/app/gotrips/signup-page-4.html
Resolved lottery and profession issues raised by Rich in story discussion
=> resolved feedback for US1575 discussion

CI/SQL/US488-CreateNewDonorLetter.sql
Sql script for new donor letter
=> sql script for new donor letter

crossroads.net/crossroads.ci.js
Needed to add the correct pattern for loading trips in the karma config
=> US1742 - Trip Module

CI/SQL/US232-01-AddColumnReconcileChangeNeededToDonations.sql, CI/SQL/US232-02-AddColumnReconcileChangeCompleteToDonations.sql, CI/SQL/US232-03-AddViewReconcileChangeNeeded.sql, CI/SQL/US232-04-UpdateDonationToReconcileChangeNeeded.sql
https://rally1.rallydev.com/#/27593764268d/detail/userstory/24467668840
=> US232-Enable reconcile contribution data

CI/SQL/US232-04-UpdateDonationToReconcileChangeNeeded.sql
https://rally1.rallydev.com/#/27593764268d/detail/defect/41297959327
=> Add a join and check on deposits table to see if exported.

crossroads.net/app/trips/signup/page2/signupPage2.html, crossroads.net/app/trips/signup/page4/signupPage4.html, crossroads.net/app/trips/signup/page5/signupPage5.html, crossroads.net/app/trips/signup/pages.controller.js, crossroads.net/app/trips/signup/signupProgress/signupProgress.controller.js
* Added values for T-Shirt Size
* Added Scrub Size dropdown
* Fixed percent indicator at 100%
* Required fields for NOLA
=> US1413 Signup Forms

crossroads.net/.jscsrc, crossroads.net/app/trips/signup/page2/signupPage2.html, crossroads.net/app/trips/signup/pages.controller.js
* Fixed @IngageBrewerM typo in [jscs](.jscsrc)
* Added method to pages controller to check if the current applicant is
under 18
* Added markup to display input boxes for guardian fname and lname if
applicant is under 18
=> DE383 Under Age Applicants

CI/SQL/US1713-01-AddColumnsToGL_Account_Mapping.sql, CI/SQL/US1713-02-AddSubViewGPExport.sql, CI/SQL/US1713-AddColumnsToGL_Account_Mapping.sql, Gateway/MinistryPlatform.Models/GPExportDatum.cs, Gateway/MinistryPlatform.Models/MinistryPlatform.Models.csproj, Gateway/MinistryPlatform.Translation.Test/Services/DonationServiceTest.cs, Gateway/MinistryPlatform.Translation/Services/DonationService.cs, Gateway/MinistryPlatform.Translation/Services/Interfaces/IDonationService.cs, Gateway/crds-angular.test/controllers/DonationControllerTest.cs, Gateway/crds-angular/Controllers/API/DonationController.cs, Gateway/crds-angular/MinistryPlatform.config, Gateway/crds-angular/Services/DonationService.cs, Gateway/crds-angular/Services/Interfaces/IDonationService.cs, Gateway/crds-angular/Util/CSV.cs, Gateway/crds-angular/crds-angular.csproj
https://rally1.rallydev.com/#/27593764268d/detail/userstory/39896062044
=> Us1713 gp file export

CI/SQL/US1725-AddProcessorFeeAndDepositAmt.sql
This script was already executed in the demo environment.
=> altering script to add description

CI/SQL/US489-05-FindDonorsHouseholdCrossroadsReport.sql, CI/SQL/US489-06-CRDSFindDonorHouseholdReport.sql, CI/SQL/US489-07-CRDSFindDonorHouseholdReportPage.sql, CI/SQL/US489-08-RoleReports.sql
NOTE - 4 other sql scripts have already been approved and merged.  This story was carryover form last sprint, and the initial sql files were merged then.
=> donations by household

CI/SQL/US489-01-FindDonorsCrossroadsReport.sql, CI/SQL/US489-05-FindDonorsHouseholdCrossroadsReport.sql
For defect 394, adding max amount so report can be executed for a range of donation values
=> Adding a range for amount

crossroads.net/app/media/media.routes.js, crossroads.net/app/media/services/media.service.js, crossroads.net/app/media/singleMedia.controller.js, crossroads.net/app/media/templates/mediaDetails.html, crossroads.net/app/media/templates/mediaSingle.html
- Updated services to support the ID in the URL vs as Param
- Cascading effects of that change
=> Changes to support related media

Gateway/crds-angular.test/Services/EzScanCheckScannerServiceTest.cs, Gateway/crds-angular/Controllers/API/CheckScannerController.cs, Gateway/crds-angular/Services/EzScanCheckScannerService.cs, Gateway/crds-angular/Services/Interfaces/ICheckScannerService.cs
https://rally1.rallydev.com/#/27593764268d/detail/defect/42965672045
=> Make it so endpoint is Create not CreateOrUpdate

crossroads.net/app/common/profile/personal/profilePersonal.controller.js
*Removed a function assignment for which there was no funciton!
=> DE426 Error in US1808

crossroads.net/app/common/profile/household/profileHousehold.template.html, crossroads.net/app/common/profile/personal/profilePersonal.template.html, crossroads.net/app/common/validation/invalidZip.validation.directive.js
* Updated zipcode directive to return true for a null or empty value
* Updated markup of household directive to use the row class
* added validate-date validation to the anniversary question
=> DE431 DE432 DE433

crossroads.net/.jscsrc, crossroads.net/app/common/profile/household/profileHousehold.template.html, crossroads.net/app/common/profile/personal/profilePersonal.template.html, crossroads.net/app/common/validation/invalidZip.validation.directive.js
* Needed to also check for an empty string in the zip code validator
* removed css from label to remove red during error state
=> DE431 DE432

crossroads.net/app/trips/signup/page0/page0.html, crossroads.net/app/trips/signup/signupPage.html, crossroads.net/app/trips/signup/tripsSignup.controller.js, crossroads.net/app/trips/signup/tripsSignup.service.js
* Changed title for thank you page
=> DE437 Thankyou Page Title

CI/SQL/US2049-AddCheckScannerBatchToDonationViews.sql
https://rally1.rallydev.com/#/27593764268d/detail/userstory/43259278440
=> US-2049: add check batch name to donation page views

crossroads.net/app/trips/tripgiving/tripgiving.controller.js
* was calling wrong method in the state listener
=> DE469 - Program not Showing after logging in

CI/SQL/US439-CreateUsersApiPageView.sql, Gateway/Crossroads.AsyncJobs/MinistryPlatform.config, Gateway/crds-angular/MinistryPlatform.config
Changed page view to 2181 in SQL, and updated MinistryPlatform.config to reflect this change.
=> US439: Fix SQL and config to address conflict with page view in Demo

Gateway/Crossroads.AsyncJobs/Unity.config, Gateway/crds-angular/Services/ServeService.cs
* Fixed Asyncjobs since tripService has a new dependency
* removed try-catch which was eating errors
=> US1557 Performance Improvements

Gateway/MinistryPlatform.Translation.Test/Services/DonorServiceTest.cs, Gateway/MinistryPlatform.Translation/Services/DonorService.cs, Gateway/MinistryPlatform.Translation/Services/Interfaces/IDonorService.cs, Gateway/crds-angular.test/Services/EzScanCheckScannerServiceTest.cs, Gateway/crds-angular.test/Services/StripeEventServiceTest.cs, Gateway/crds-angular.test/controllers/DonationControllerTest.cs, Gateway/crds-angular/Services/StripeEventService.cs, Gateway/crds-angular/Services/StripeService.cs
Also set fee amount appropriately
=> DE483: Get status from Stripe on invoice.created

Gateway/Crossroads.AsyncJobs/MinistryPlatform.config, Gateway/Crossroads.AsyncJobs/Unity.config
* Added missing config entries to MinistryPlatform.config
* Added missing IContactAttributeService mapping to Unity.config
=> Fix AsyncJobs Config

crossroads.net/app/profile/giving/recurring/recurring_giving_modals.controller.js, crossroads.net/app/profile/giving/recurring/templates/recurring_giving_edit_modal.html, crossroads.net/app/profile/giving/recurring/templates/recurring_giving_remove_modal.html
https://rally1.rallydev.com/#/27593764268d/detail/defect/45194926668
=> DE-549: Disable update button on recurring gift edit page if processing.

CI/SQL/DE556-Relationship_Permissions.sql
*Added script to give ApiUser permissions to edit relationships
=> DE556 Nica Application Not Submitting

crossroads.net/app/trips/signup/pageTemplates/signupPage6.html, crossroads.net/app/trips/signup/signupStep.controller.js, crossroads.net/app/trips/signup/tripsSignup.controller.js
Most of the work of this story was done when working on
[DE545](https://github.com/crdschurch/crds-angular/tree/defect/DE545-PassportNotPersisting)
. What was missed was the function that checks the valid passport flag
and makes the passport fields required or not.
=> US2536 Passport Prepopulation

crossroads.net/app/common/giving/confirmDonation/confirmDonation.html, crossroads.net/app/give/one_time/templates/one_time_confirm.html, crossroads.net/app/give/recurring/templates/recurring_account.html, crossroads.net/app/give/recurring/templates/recurring_thank_you.html
htmlmin defect: https://github.com/jonschlinkert/gulp-htmlmin/issues/15
=> DE567: Work around htmlmin defect

crossroads.net/app/common/profile/personal/profilePersonal.controller.js, crossroads.net/app/trips/signup/tripsSignup.controller.js
* Get date of current applicant and not of current logged in user
=> DE516 Guardian not showing correctly

crossroads.net/app/common/giving/creditCardInfo/creditCardInfo.directive.js, crossroads.net/spec/common/giving/creditCardInfo.directive.spec.js
https://rally1.rallydev.com/#/27593764268d/detail/defect/45562731856
=> DE573 - Fix defect

crossroads.net/app/mp_tools/admin_recurring_gift/adminRecurringGift.controller.js, crossroads.net/app/mp_tools/admin_recurring_gift/templates/adminManageRecurringGifts.html, crossroads.net/spec/mp_tools/admin_recurring_gift/adminRecurringGift.controller.spec.js
https://rally1.rallydev.com/#/27593764268d/detail/defect/45627758511
=> DE575 - Fix issue where person who can't impersonate is not seeing error message

crossroads.net/app/common/profile/household/profileHousehold.template.html
It was already required, I removed the `display:none` style from the
default option.
=> DE576 Make Location Required

crossroads.net/app/trips/signup/pageTemplates/signupPage2.html, crossroads.net/app/trips/signup/pageTemplates/signupPage3.html, crossroads.net/app/trips/signup/pageTemplates/signupPage4.html, crossroads.net/app/trips/signup/pageTemplates/signupPage5.html, crossroads.net/app/trips/signup/pageTemplates/signupPage6.html
=> US2537 Tab order on trip apps

crossroads.net/app/common/profile/personal/profilePersonal.controller.js, crossroads.net/app/common/profile/personal/profilePersonal.directive.js, crossroads.net/app/profile/profile.controller.js, crossroads.net/app/profile/profilePersonal.html, crossroads.net/app/trips/signup/pageTemplates/signupPage1.html, crossroads.net/app/trips/signup/tripsSignup.controller.js
* refactored profilePersonal directive to take age in the
`enforceAgeRestrictons` variable. If the variable is undefined then we
don't enforce age restrictions.
* Cleaned up profilePersonalController to align with style guide
* refactored profile.controller to use new directive variable to set age
to 13.
=> DE577 Exceptions list not validating correctly

Gateway/MinistryPlatform.Translation.Test/Services/DonorServiceTest.cs, Gateway/crds-angular/Controllers/API/DonationController.cs, Gateway/crds-angular/Controllers/API/DonorController.cs, Gateway/crds-angular/Controllers/API/ProfileController.cs
https://rally1.rallydev.com/#/27593764268d/detail/defect/45684163048
https://rally1.rallydev.com/#/27593764268d/detail/defect/45684698402
=> DE578 - Fix tests and also fix bug with impersonate user when user is not found

crossroads.net/app/common/profile/household/profileHousehold.controller.js, crossroads.net/app/common/profile/household/profileHousehold.template.html
* added new validation to dropdown
=> DE576 Location Not Required

Gateway/MinistryPlatform.Translation.Test/Services/DonorServiceTest.cs, Gateway/MinistryPlatform.Translation/Services/DonorService.cs
Addresses both [DE580](https://rally1.rallydev.com/#/27593764268d/detail/defect/45704123918) and [DE581](https://rally1.rallydev.com/#/27593764268d/detail/defect/45704908339)
=> DE580 & DE581: Fix issues in recurring giving confirmation emails

Gateway/crds-angular.test/controllers/CheckScannerControllerTest.cs, Gateway/crds-angular/Controllers/API/CheckScannerController.cs
* [US2675](https://rally1.rallydev.com/#/27593764268d/detail/userstory/45719866729)
=> US2675: Return new error codes from CheckScannerController

CI/SQL/US2400-01-CreatePledgeViewToFilterOnHousehold.sql
https://rally1.rallydev.com/#/27593764268d/detail/userstory/44105537990
=> US2400 - Create page view for searching for household pledges.

CI/SQL/US2400-00-CreateFunctionToFilterOnHousehold.sql, CI/SQL/US2400-02-CreateDonorSubViewToFilterPledgeOnHousehold.sql
https://rally1.rallydev.com/#/27593764268d/detail/userstory/44105537990
=> US2400 - Make subview for donor to view household pledges.

CI/SQL/US2615-01-CreateChildOfAge.sql
=> Create Has Child of Age

crossroads.net/app/give/one_time/templates/one_time_thank_you.html
* [DE596](https://rally1.rallydev.com/#/27593764268d/detail/defect/45985614604)
* __Do not merge until after Planning on Nov 3!__
=> DE596: Show "Make Recurring" link only when program allows recurring.

Gateway/MinistryPlatform.Models/Pledge.cs, Gateway/MinistryPlatform.Translation.Test/Services/PledgeCampaignServiceTest.cs, Gateway/MinistryPlatform.Translation/Services/PledgeService.cs, Gateway/crds-angular/Models/Crossroads/Stewardship/PledgeDto.cs, crossroads.net/app/profile/giving/commitment/templates/commitment_list.html
Note that pledgename was unused so I removed it as well.
=> US2693-remove name

crossroads.net/app/trips/signup/pageTemplates/signupPage6.html, crossroads.net/app/trips/signup/signupStep.controller.js
=> DE598 and DE604

CI/SQL/DE610-AddCampaignTypeToMyHouseholdPledges.sql, Gateway/Crossroads.AsyncJobs/MinistryPlatform.config, Gateway/MinistryPlatform.Models/Pledge.cs, Gateway/MinistryPlatform.Translation.Test/Services/PledgeCampaignServiceTest.cs, Gateway/MinistryPlatform.Translation/Services/Interfaces/IPledgeService.cs, Gateway/MinistryPlatform.Translation/Services/PledgeService.cs, Gateway/crds-angular/App_Start/AutoMapperConfig.cs, Gateway/crds-angular/Controllers/API/DonorController.cs, Gateway/crds-angular/MinistryPlatform.config, Gateway/crds-angular/Models/Crossroads/Stewardship/PledgeDto.cs, Gateway/crds-angular/Services/DonorService.cs, Gateway/crds-angular/Services/Interfaces/IDonorService.cs
* [DE610](https://rally1.rallydev.com/#/27593764268d/detail/defect/46131542348)
=> DE610: Filter capital campaigns only on giving page

crossroads.net/app/profile/giving/profile_giving.controller.js
https://rally1.rallydev.com/#/27593764268d/detail/defect/46146631843
=> Add back in the redirect to recurring gift creation.

CI/SQL/US2494-UpdateDonorHouseholdPledgesSubView.sql
https://rally1.rallydev.com/#/27593764268d/detail/userstory/44393526300
http://mp-build.cloudapp.net/viewType.html?buildTypeId=Skunkworks_TestDatabaseScripts&branch_Skunkworks=US2494-ImproveDonorHouseholdPledgeView&tab=buildTypeStatusDiv
=> Generate script to update household pledge sub view.

crossroads.net/app/giving_history/templates/donation_list.html
https://rally1.rallydev.com/#/27593764268d/detail/defect/46539174246
=> Fix so tbody is not being repeated by using ng-repeat-start/end

CI/SQL/US16-03-AddContactIdView.sql, Gateway/MinistryPlatform.Translation/Services/Interfaces/IUserService.cs, Gateway/MinistryPlatform.Translation/Services/UserService.cs, Gateway/crds-angular/Services/LoginService.cs
=> Defect Fixes

Gateway/MinistryPlatform.Translation/Services/Interfaces/IUserService.cs, Gateway/MinistryPlatform.Translation/Services/UserService.cs, Gateway/crds-angular.test/Services/LoginServiceTest.cs, Gateway/crds-angular/Controllers/API/LoginController.cs, Gateway/crds-angular/Services/LoginService.cs
* changed method to look at username
=> DE633 Unable to login if my email is !my username

CI/SQL/US16-02-AddEmailTemplate.sql, Gateway/crds-angular/Services/LoginService.cs
=> Fixed Reset Link

crossroads.net/app/common/profile/personal/profilePersonal.controller.js, crossroads.net/app/common/profile/personal/profilePersonal.template.html, crossroads.net/app/profile/profile.html
* only load tab views when needed
=> DE600 - Gender Not Populating

CI/SQL/US2780-UpdateDonationToReconcileChangeNeeded.sql
…ion date is updated.https://rally1.rallydev.com/#/27593764268d/detail/userstory/46919200138
=> Update trigger to set reconcile to true and message of why when donation date is updated.

Gateway/Crossroads.ChildcareRsvp/App.config, Gateway/Crossroads.ChildcareRsvp/Crossroads.ChildcareRsvp.csproj, Gateway/Crossroads.ChildcareRsvp/packages.config, Gateway/MinistryPlatform.Translation/Services/EventParticipantService.cs
=> DE653 Added quotes to search string.

Gateway/crds-angular/Services/GroupService.cs
An exception was being thrown when there were no events for the wait list.
=> DE670 events being null was causing an exception

crossroads.net/app/give/one_time/templates/one_time_confirm.html, crossroads.net/app/give/one_time/templates/one_time_thank_you.html
* [DE683](https://rally1.rallydev.com/#/27593764268d/detail/defect/47842098181)
=> DE683: Fix extra space before ending punctuation on giving pages

crossroads.net/app/mp_tools/volunteer_contact/contact.html, crossroads.net/app/mp_tools/volunteer_contact/volunteerContact.component.js, crossroads.net/app/mp_tools/volunteer_contact/volunteer_contact_form/volunteerContactForm.component.js, crossroads.net/app/mp_tools/volunteer_contact/volunteer_contact_form/volunteerContactForm.html
* added two 'show' methods for to handle when to show the messages
=> DE680 handle no events or participants correctly

CI/SQL/US222-CreateNonCashAssetTable.sql, CI/SQL/US222-InsertPageSection.sql
* [DE689](https://rally1.rallydev.com/#/27593764268d/detail/defect/47983726679)
=> DE689: Fix issues with Non-Cash Assets Page

crossroads.net/app/mp_tools/check_batch_processor/checkBatchProcessor.html
* [DE693](https://rally1.rallydev.com/#/27593764268d/detail/defect/48003005160)
* Added containing "container" and "row" divs, resulting in no more love for the left side of the browser
=> DE693: Less love for the left side of the window

crossroads.net/app/common/profile/personal/profilePersonal.controller.js
=> DE706: Moved set pristine to only on success

crossroads.net/app/mp_tools/check_batch_processor/checkBatchProcessor.html
* [DE717](https://rally1.rallydev.com/#/27593764268d/detail/defect/48292536510)
* Changed dynamic-content to ng-bind-html on dropdowns
=> DE717: Use ng-bind-html in place of dynamic-content for dropdowns

Gateway/MinistryPlatform.Models/Communication.cs
DE701 - Fixed password reset email issue.
=> Fix No Password Reset Email

CI/TestSQL_TearDown/ZTestTeardownUsers/TD_SignUptoServe_Users.sql, crossroads.net/app/signup/community_group_signup/communityGroupSignup.controller.js, crossroads.net/app/signup/signup.routes.js, crossroads.net/app/trips/trips.routes.js, crossroads.net/spec/group_signup_controller_spec.js
* added `$urlMatcherFactoryProvider.strictMode(false)` so that is
doesn't matter if there is a ending slash on routes
* added code to add trailing slash to cms api calls if trailing slash
does not already exist
=> DE664 - Trailing Slash not working on some pages

crossroads.net/app/trips/tripgiving/tripgiving.controller.js
* set `dto.emailPrefix` to the `give`
=> DE527 Email ID set correctly

Gateway/Crossroads.AsyncJobs/Web.Release.config
* [DE762](https://rally1.rallydev.com/#/27593764268d/detail/defect/48682750352)
=> DE762: Fix release config for AsyncJobs

CI/SQL/US225-ViewCommitmentProgress.sql
[DE764](https://rally1.rallydev.com/#/27593764268d/detail/defect/48683163632)
=> DE764: Ignore pledge status when getting pledge ids

Gateway/Crossroads.AsyncJobs/App_Start/AutoMapperConfig.cs, Gateway/MinistryPlatform.Translation.Test/Services/ProgramServiceTest.cs, Gateway/crds-angular/App_Start/AutoMapperConfig.cs
[DE763](https://rally1.rallydev.com/#/27593764268d/detail/defect/48683158315)
=> DE763: Fix default email template logic

Gateway/crds-angular.test/controllers/DonorControllerTest.cs, Gateway/crds-angular/Controllers/API/DonorController.cs, Gateway/crds-angular/Services/DonorService.cs, Gateway/crds-angular/Services/Interfaces/IDonorService.cs
* [DE793](https://rally1.rallydev.com/#/27593764268d/detail/defect/48730667639)
* Don't call Stripe to create a customer for the token before recurring gift - it is called during the recurring gift flow.
=> DE793: Fix recurring giving so first-time giver works properly

crossroads.net/app/common/profile/personal/profilePersonal.controller.js, crossroads.net/app/common/profile/personal/profilePersonal.template.html
* `vm.today` was not being set ( the max date to show in the datepicker
=> DE806 DE807

CI/SQL/US2765-01-Filter-Relationship-Values.sql
US2765 - Added query to filter relationship lookup values
=> Filter Relationship Values

Gateway/crds-angular.test/Services/ServeServiceTest.cs, Gateway/crds-angular/Controllers/API/ServeController.cs, Gateway/crds-angular/Services/Interfaces/IServeService.cs, Gateway/crds-angular/Services/ServeService.cs
we were using the logged in users token to get min and max info, I changed
it to use the api user to get that info
=> DE750 SU2S Badges

CI/SQL/US2765-01-Filter-Relationship-Values.sql
US2765 - Changed the columns displayed
=> Filter Relationship Types

Gateway/crds-angular.test/Services/EzScanCheckScannerServiceTest.cs, Gateway/crds-angular/Services/EzScanCheckScannerService.cs
Rollback changes made here from story US2720 - https://github.com/crdschurch/crds-angular/pull/1190/files
=> US2721 - Rollback the hard coded account and routing number sent to stripe from EZ Scan

Gateway/crds-angular/Services/LoginService.cs
US2663 - Updated save field name
=> Reset Password

crossroads.net/app/mp_tools/signup_to_serve/signupToServe.controller.js
we weren't setting the opportunityIds array when saving the serveRsvp
=> DE801 - SU2STool

crossroads.net/spec/mp_tools/signup_to_serve/signUpToServe.controller.spec.js
=> DE801 - SU2S Tool

crossroads.net/app/media/templates/messagesListCard.html
DE759 - Removed testing code from template
=> Fix for Message Title

Gateway/MinistryPlatform.Translation/Services/Interfaces/IParticipantService.cs, Gateway/MinistryPlatform.Translation/Services/ParticipantService.cs, Gateway/crds-angular/Services/PersonService.cs
matches what we do with contact and attributes in the same method and
fixes role security problem.
=> DE835 Changed to use apilogin.

crossroads.net/app/mp_tools/signup_to_serve/index.js, crossroads.net/app/mp_tools/signup_to_serve/signupToServe.controller.js, crossroads.net/app/mp_tools/signup_to_serve/su2s.html, crossroads.net/spec/mp_tools/signup_to_serve/signUpToServe.controller.spec.js
dates where not being parsed correctly 1/3/2016 versus 01/03/2016
=> DE801 SU2S Tool

crossroads.net/app/giving_history/giving_history.controller.js, crossroads.net/app/mp_tools/admin_giving_history/adminGivingHistory.html, crossroads.net/app/mp_tools/admin_recurring_gift/adminRecurringGift.controller.js, crossroads.net/app/mp_tools/admin_recurring_gift/templates/adminManageRecurringGifts.html, crossroads.net/app/mp_tools/check_batch_processor/checkBatchProcessor.controller.js, crossroads.net/app/mp_tools/gp_export/gpExport.controller.js, crossroads.net/app/mp_tools/index.js, crossroads.net/app/mp_tools/kc_applicant/applicant.html, crossroads.net/app/mp_tools/kc_applicant/kcApplicant.controller.js, crossroads.net/app/mp_tools/mpTools.constants.js, crossroads.net/app/mp_tools/trip_participants/trip.html, crossroads.net/app/mp_tools/trip_participants/tripParticipant.controller.js, crossroads.net/app/mp_tools/trip_private_invite/invite.html, crossroads.net/app/mp_tools/trip_private_invite/tripPrivateInvite.controller.js, crossroads.net/app/mp_tools/volunteer_contact/contact.html, crossroads.net/app/mp_tools/volunteer_contact/volunteerContact.component.js, crossroads.net/spec/mp_tools/check_batch_processor/checkBatchProcessor.controller.spec.js, crossroads.net/spec/mp_tools/gp_export/gpExport.controller.spec.js
* [US13](https://rally1.rallydev.com/#/27593764268d/detail/userstory/24467556512)
* [Google doc with roles](https://docs.google.com/spreadsheets/d/17WdnJBDUkfm3qvQsvehJKvhDnXvUY0cTVQRyMFeQglk/edit?ts=567978f4#gid=0)
=> US13: Check security roles in tools

CI/SQL/EmailTemplates/Su2sEmailTemplate.sql, CI/SQL/PageViews/Response_RemindersToSend.sql, CI/SQL/Tables/Add_Reminders_To_Opportunities.sql, Gateway/Crossroads.AsyncJobs/Unity.config, Gateway/EventReminder/Program.cs, Gateway/MinistryPlatform.Translation/MinistryPlatform.Translation.csproj, Gateway/MinistryPlatform.Translation/Models/MPServeReminders.cs, Gateway/MinistryPlatform.Translation/Services/Interfaces/IResponseService.cs, Gateway/MinistryPlatform.Translation/Services/ResponseService.cs, Gateway/crds-angular.test/Services/ServeServiceTest.cs, Gateway/crds-angular/App_Start/AutoMapperConfig.cs, Gateway/crds-angular/MinistryPlatform.config, Gateway/crds-angular/Models/Crossroads/Serve/ServeProfile.cs, Gateway/crds-angular/Models/Crossroads/Serve/ServeReminder.cs, Gateway/crds-angular/Services/EventService.cs, Gateway/crds-angular/Services/Interfaces/IServeService.cs, Gateway/crds-angular/Services/ServeService.cs, Gateway/crds-angular/Unity.config, Gateway/crds-angular/crds-angular.csproj
* Added email template
* Added a view to responses to get needed reminders
* Created new method in serveservice to send su2s reminder emails
=> US2926 Signup 2 Serve Reminder

CI/GoLive SQL/US1152-01-SetResetToken.sql, CI/GoLive SQL/US1152-02-CreateResetEmails.sql
US1152 - Send go live reset emails
=> Send Password Reset Emails

Gateway/EventReminder/Program.cs, Gateway/crds-angular/Services/EventService.cs
* put each send email method in it's own try-catch. that way if one
fails, it doesn't stop the other from trying to send
* when I remapped the event, I forgot to set the name...
=> DE891 Emails not sending

Gateway/crds-angular/App_Start/UnityConfig.cs, Gateway/crds-angular/Unity.config
Determine if explicitly registering controllers fixes production
=> Hotfix for Unity Config

crossroads.net/app/mp_tools/kc_applicant/kcApplicant.controller.js, crossroads.net/app/routes.js, crossroads.net/spec/mp_tools/kc_applicant/kcApplicant.controller.spec.js
* Enhanced to only allow selections from within records
=> DE885 KCApplicantTool

crossroads.net/app/give/recurring/recurring_giving.service.js, crossroads.net/app/give/recurring/templates/recurring_thank_you.html, crossroads.net/spec/give/recurring/recurring_giving.service.spec.js
https://rally1.rallydev.com/#/27593764268d/detail/defect/49430007251
=> Fix Thank You Page frequency on recurring gifts and add test.

CI/SQL/US2808-01-CreateEcheckRelationship.sql
US2808 - Commit of trigger script
=> Create Echeck Relationship

CI/SQL/US2741-ResponsesForEventWithGroup.sql, Gateway/Crossroads.AsyncJobs/MinistryPlatform.config, Gateway/Crossroads.Utilities.Test/Crossroads.Utilities.Test.csproj, Gateway/Crossroads.Utilities.Test/Extensions/DateTimeExtensionTest.cs, Gateway/Crossroads.Utilities/Extensions/DateTimeExtensions.cs, Gateway/MinistryPlatform.Translation/MinistryPlatform.Translation.csproj, Gateway/MinistryPlatform.Translation/Models/Opportunities/MPResponse.cs, Gateway/MinistryPlatform.Translation/Services/Interfaces/IOpportunityService.cs, Gateway/MinistryPlatform.Translation/Services/OpportunityServiceImpl.cs, Gateway/crds-angular.test/Services/GroupServiceTest.cs, Gateway/crds-angular.test/Services/ServeServiceTest.cs, Gateway/crds-angular/MinistryPlatform.config, Gateway/crds-angular/Models/Crossroads/Opportunity/OpportunityResponseDto.cs, Gateway/crds-angular/Services/GroupService.cs, Gateway/crds-angular/Services/Interfaces/IServeService.cs, Gateway/crds-angular/Services/ServeService.cs
* Added some date extensions to make it easy to determine if we are looked
at an event on the weekend (Saturday or Sunday)
* Modified a response view to show only responses with an attached event
and show the event Start Date
* Created new public method in ServeService to get Potential Volunteers
* by determining if the volunteer has any responses on the weekend
=> US2976 Refactor Volunteer Contact Tool

Gateway/crds-angular.test/Services/ServeServiceTest.cs, Gateway/crds-angular/Services/ServeService.cs
* Forgot to check for other responses on the current day
=> DE908 Volunteer Contact Tool

crossroads.net/app/common/giving/donation_details/donationDetails.html, crossroads.net/app/give/one_time/templates/one_time_change.html
https://rally1.rallydev.com/#/27593764268d/detail/defect/49538652775
=> Do not show recurrence options on one time page change.

CI/SQL/US2808-01-CreateEcheckRelationship.sql, CI/SQL/US2808-02-update-echeck-relationships.sql
Fixed bugs with duplicate relationships when adding child to multiple parents or vice versa.
Fixed trigger to handle multiple rows inserted into contacts at same time
=> DE906: Fixed issue with duplicate relationships

Gateway/CrossroadsStripeOnboarding/Services/StripePlansAndSubscriptions.cs
https://rally1.rallydev.com/#/27593764268d/detail/defect/49611988349
=> DE916 - Update end date of active recurring gifts to be 2000/01/01

CI/SQL/US16-02-AddEmailTemplate.sql
US2953 - Added anchor tag to link
=> Added anchor tag to link in reset password email

CI/GoLive SQL/US3063-01-OptOut-Blacklist.sql
=> Opt Out Blacklist

Gateway/crds-angular/Web.Demo.config, Gateway/crds-angular/Web.Release.config
* [US3078](https://rally1.rallydev.com/#/27593764268d/detail/userstory/49941826388)
* Added max pool size setting to DB connection in Demo and Prod
=> US3078: Add connection pool settings to MP database connection

crossroads.net/app/common/profile/personal/confirmPassword.controller.js, crossroads.net/app/common/profile/personal/profilePersonal.controller.js
DE969 - Modified where the password was being cleared out
=> Credential Errors

crossroads.net/app/common/profile/personal/profilePersonal.controller.js
=> Missing Modal Content

CI/GoLive SQL/US3063-01-OptOut-Blacklist.sql
US3063 - Checking in updated script from Phil
=> MP Opt Out Blacklist

CI/GoLive SQL/US3004-02-CreateEquipment.sql
=> Fixed Equipment Script

crossroads.net/app/search/search-results.html
- Also removed hard coded domain, because of some pages that are
external being in the search index
=> DE1037: remove dynamic-content in favor of ng-bind-html

Gateway/crds-angular/Web.config
=> increase max message size DE1133

CI/SQL/20160217141340_DE1149-FixRecurringGiftDonationDistributions.sql, CI/SQL/20160217141340_DE1149-FixRecurringGiftDonations.sql, Gateway/crds-angular/Services/DonationService.cs
Also, script to fix existing records.
=> DE1149 Don't cast to int and drop cents

Gateway/Crossroads.AsyncJobs/MinistryPlatform.config
=> US3185: Add missing MP config entries

CI/SQL/20160301095500_US3353-relate-locations-to-organizations.sql, CI/SQL/20160301103000_US3353-relate-locations-to-organizations.sql
* Add column 'Organization_ID' to Location Table
* Add Foreign Key to cr_Organization Table
* Update Page View to include Organization
=> US3353 Relate Location and Organization

crossroads.net/app/group_finder/dashboard/dashboard.html, crossroads.net/app/group_finder/dashboard/group_detail.controller.js, crossroads.net/app/group_finder/dashboard/group_detail.html, crossroads.net/app/group_finder/directives/group_card/group_card.html, crossroads.net/app/group_finder/host/host_confirm.controller.js, crossroads.net/app/group_finder/host/host_review.controller.js, crossroads.net/app/group_finder/host/host_review.html, crossroads.net/app/group_finder/services/group_info.service.js
* Fixes DE1214 - Email Group button not working
* Fixes issues with group info not updating consistently
* Hide email group button if the host is the only group member
* Host email address is correct on the "Email Host" mailto link
* Publish button will not allow duplicate clicks
* Publish button will be hidden upon error
=> US3245 - Dashboard updates

CI/SQL/201603010810_DE1172-update-serve-reminder-pageview.sql
DE1172 - commented out rollback code
=> Not Placed Response Emails

crossroads.net/app/group_finder/directives/question/input_radio.html, crossroads.net/app/group_finder/directives/questions/questions.controller.js
=> DE1221 - updated layout for radio buttons; handle error messages

crossroads.net/app/group_finder/directives/question/question.html
Has corresponding PR in `core-js` https://github.com/crdschurch/crds-corejs/pull/243
=> QA flow validation

crossroads.net/app/group_finder/common/layout.html
corresponding PR in `core-js` https://github.com/crdschurch/crds-corejs/pull/244
=> updated image assets

crossroads.net/app/group_finder/directives/group_card/group_card.controller.js, crossroads.net/app/group_finder/directives/group_profile/group_profile.controller.js, crossroads.net/app/group_finder/directives/question/question.controller.js, crossroads.net/app/group_finder/host/host_review.controller.js, crossroads.net/app/group_finder/services/group_questions.service.js
Also updates seats taken to default to 0
=> DE1204 group type update

crossroads.net/app/group_finder/directives/group_card/group_card.controller.js, crossroads.net/app/group_finder/group_finder.constants.js, crossroads.net/app/group_finder/host/host_review.controller.js, crossroads.net/app/group_finder/index.js, crossroads.net/app/group_finder/invitation/invitation.controller.js, crossroads.net/app/group_finder/services/group_info.service.js
Public and private group confirmation emails
=> DE1213 - Participant confirmation emails

crossroads.net/app/group_finder/directives/group_profile/group_profile.controller.js, crossroads.net/app/group_finder/directives/group_profile/group_profile.html, crossroads.net/app/group_finder/host/host_review.controller.js, crossroads.net/app/group_finder/services/group_info.service.js
corresponding PR in `core-js` https://github.com/crdschurch/crds-corejs/pull/249
=> DE1208 incorrect meeting time

CI/SQL/20160304144300_DE1250-fix_project_preferences.sql
* change column name from 'descrition' to 'Project Type'
=> DE1250 Change Project Preferences SubPage

Gateway/crds-angular.test/Services/EzScanCheckScannerServiceTest.cs, Gateway/crds-angular/Services/EzScanCheckScannerService.cs
* [DE1249](https://rally1.rallydev.com/#/27593764268d/detail/defect/52289737478)
=> DE1249: Use proper customer ID when processing a check into stripe

crossroads.net/app/group_finder/directives/group_profile/group_profile.controller.js, crossroads.net/app/group_finder/directives/group_profile/group_profile.directive.js, crossroads.net/app/group_finder/directives/group_profile/group_profile.html, crossroads.net/app/group_finder/directives/index.js, crossroads.net/app/group_finder/host/host_review.controller.js, crossroads.net/app/group_finder/services/results.service.js
Updated to pull in empty profile pictures and resolved host flow errors
=> US3245 results page

crossroads.net/app/trips/trips.routes.js
DE1185 - Fixed controller name in trip giving route
=> Fix for register in trip giving routes

crossroads.net/app/group_finder/invitation/invitation.controller.js, crossroads.net/app/group_finder/join/join_results.controller.js
@danrye addressed a bug that I noticed
=> JoinFlowDefect

crossroads.net/app/group_finder/directives/questions/questions.controller.js, crossroads.net/app/group_finder/group_finder.constants.js, crossroads.net/app/group_finder/invitation/invitation.controller.js, crossroads.net/app/group_finder/join/join_results.controller.js, crossroads.net/app/group_finder/join/join_results.html, crossroads.net/app/group_finder/services/results.service.js
=> Release feature/defect/results page defects

crossroads.net/app/group_finder/dashboard/dashboard.routes.js, crossroads.net/app/group_finder/dashboard/group_detail.controller.js, crossroads.net/app/group_finder/host/host.routes.js, crossroads.net/app/group_finder/invitation/invitation.controller.js, crossroads.net/app/group_finder/join/join.routes.js, crossroads.net/app/group_finder/services/results.service.js
Covers:
* DE1300
* DE1307
* DE1273
* DE1275
=> Group Finder defects

CI/SQL/20160304051342_US3361-create-volunteer-prepwork-attribute-type.sql, CI/SQL/20160304104501_US3360-registration-children-attribute-type.sql, CI/SQL/20160304105301_US3360-registration-children-attributes.sql, CI/SQL/20160314134901_DE1306-GroupConnectorPage.sql
=> DE1306 Update Group Connector Page Defintion

crossroads.net/app/go_volunteer/organizations/organizations.template.html
=> DE1320 Archdio Nav Error

Gateway/MinistryPlatform.Models/GPExportDatum.cs, Gateway/MinistryPlatform.Translation.Test/Services/DonationServiceTest.cs, Gateway/MinistryPlatform.Translation/Services/DonationService.cs, Gateway/crds-angular.test/Services/DonationServiceTest.cs, Gateway/crds-angular/App_Start/AutoMapperConfig.cs, Gateway/crds-angular/Models/Crossroads/Stewardship/GPExportDatumDTO.cs
Fix a issue found where the Document Number was not unique.
=> Add uniqueness to Document Number

CI/SQL/201603181431_US3431_PrintedStatementsDeclined.sql
=> Printed Statement Show No Declines

crossroads.net/app/go_volunteer/page/groupFindConnector/goVolunteerGroupFindConnector.component.js, crossroads.net/app/go_volunteer/page/groupFindConnector/goVolunteerGroupFindConnector.template.html
=> Updated disabled group style

CI/SQL/20160330144224_DE1344-FixInitiativesPage.sql
=> DE1344 Added table names to start/end dates

CI/Reports/CRDS GivingByCongregation.rdl
grouping on vertical axis by month and year
=> grouping on vertical axis by month and year

Gateway/Crossroads.AsyncJobs/App_Start/AutoMapperConfig.cs, Gateway/crds-angular.test/Services/DonationServiceTest.cs, Gateway/crds-angular.test/controllers/DonationControllerTest.cs, Gateway/crds-angular/App_Start/AutoMapperConfig.cs, Gateway/crds-angular/Models/Crossroads/Stewardship/DonationSourceDTO.cs, Gateway/crds-angular/Services/DonationService.cs, Gateway/crds-angular/Services/DonorService.cs, crossroads.net/app/common/giving/bankInfo/bankInfo.directive.js, crossroads.net/app/common/giving/services/donation.service.js, crossroads.net/app/common/giving/services/giveTransfer.service.js, crossroads.net/app/give/recurring/recurring_giving.service.js
This PR covers defect 1392 and 1393.  it seemed silly to split up the work.
=> DE1392 make recurring gifts work

crossroads.net/app/go_volunteer/page/additionalInfo/goVolunteerAdditionalInfo.template.html, crossroads.net/app/go_volunteer/page/availablePrep/goVolunteerAvailablePrep.template.html, crossroads.net/app/go_volunteer/page/children/goVolunteerChildren.template.html, crossroads.net/app/go_volunteer/page/childrenCount/goVolunteerChildrenCount.template.html, crossroads.net/app/go_volunteer/page/connectorInfo/goVolunteerConnectorInfo.template.html, crossroads.net/app/go_volunteer/page/equipment/goVolunteerEquipment.template.html, crossroads.net/app/go_volunteer/page/groupConnector/goVolunteerGroupConnector.template.html, crossroads.net/app/go_volunteer/page/groupFindConnector/goVolunteerGroupFindConnector.template.html, crossroads.net/app/go_volunteer/page/launchSite/goVolunteerLaunchSite.template.html, crossroads.net/app/go_volunteer/page/orgName/goVolunteerOrgName.template.html, crossroads.net/app/go_volunteer/page/profilePage/goVolunteerProfile.template.html, crossroads.net/app/go_volunteer/page/projectPrefOne/goVolunteerProjectPrefOne.template.html, crossroads.net/app/go_volunteer/page/projectPrefThree/goVolunteerProjectPrefThree.template.html, crossroads.net/app/go_volunteer/page/projectPrefTwo/goVolunteerProjectPrefTwo.template.html, crossroads.net/app/go_volunteer/page/spouse/goVolunteerSpouse.template.html, crossroads.net/app/go_volunteer/page/spouseName/goVolunteerSpouseName.template.html, crossroads.net/app/go_volunteer/page/thankYou/goVolunteerThankYou.template.html, crossroads.net/app/go_volunteer/page/uniqueSkills/goVolunteerUniqueSkills.template.html, crossroads.net/app/go_volunteer/page/waiver/goVolunteerWaiver.template.html
=> Remove Progress Bar Until Functional

crossroads.net/app/go_volunteer/page/groupFindConnector/goVolunteerGroupFindConnector.component.js
two issues were found. the chidrenCount flag was not being set anymore
in favor of childrenOptions. we didn't account for this in the
groupConnectorComponent.
we also didn't account for the fact that absoluteMaximum may not be set.
=> DE1401 Groups disabled for unknown reason -- RELEASE

crossroads.net/app/go_volunteer/page/groupFindConnector/goVolunteerGroupFindConnector.component.js
two issues were found. the chidrenCount flag was not being set anymore
in favor of childrenOptions. we didn't account for this in the
groupConnectorComponent.
we also didn't account for the fact that absoluteMaximum may not be set.
=> DE1401 groups disabled unknown -- DEVELOPMENT

Gateway/crds-angular/Services/GoSkillsService.cs
Update Skills object configuration for logged in user.  - RELEASE
=> use correct configuration for logged in user

CI/SQL/20160405074000-registration-table-fix.sql
Add _Registration_Creation_Date column to cr_Registrations table
=> Add _Registration_Creation_Date column to cr_Registrations table

Gateway/crds-angular.test/TestHelpers.cs
=> Is is that bad data was being generated?

Gateway/crds-angular.test/Services/GoVolunteerServiceTest.cs, Gateway/crds-angular.test/TestHelpers.cs, Gateway/crds-angular/Services/GoVolunteerService.cs
Now the skills are included in the email if they are set
=> DE1413 Skillz in Email -- RELEASE

Gateway/crds-angular.test/Services/GoVolunteerServiceTest.cs, Gateway/crds-angular.test/TestHelpers.cs, Gateway/crds-angular/Services/GoVolunteerService.cs
Now the skills are included in the email if they are set
=> DE1413 Skillz in Email -- DEVELOPMENT

Gateway/crds-angular/Controllers/API/GoVolunteerController.cs, Gateway/crds-angular/Services/GoVolunteerService.cs
* create spouse participant when needed
* general cleanup and housekeeping
=> DE1412 spouse participant record -- RELEASE

crossroads.net/app/go_volunteer/goVolunteer.routes.js, crossroads.net/app/go_volunteer/page/children/goVolunteerChildren.component.js, crossroads.net/app/go_volunteer/page/groupFindConnector/goVolunteerGroupFindConnector.component.js
* stop caching group connectors...
* don't assume that the number of kids in an age range is greater than 0
=> DE1425 Available Age

CI/SQL/20160413113500_DE1385-update-recurring-gifts-subscriptionId-page-view.sql, Gateway/MinistryPlatform.Translation/Services/DonorService.cs, Gateway/MinistryPlatform.Translation/Services/Interfaces/IDonorService.cs, Gateway/crds-angular.test/Services/DonationServiceTest.cs, Gateway/crds-angular.test/Services/StripeEventServiceTest.cs, Gateway/crds-angular/Models/Crossroads/Stewardship/StripeCharge.cs, Gateway/crds-angular/Services/DonationService.cs
Revert "Merge pull request #2067 from crdschurch/defect/DE1385-Revert"
This reverts commit fdea4d51c0d6b11a607a55b2ab55acb7d035aed3, reversing
changes made to 6bc338c4815c7d2d897240a9cc4114226b500163.
=> DO NOT MERGE UNTIL After Demo Deploy

CI/SQL/20160422133444_US3532-volunteer-skills-function.sql, CI/SQL/20160422135140_US3532-volunteer-equipment-function.sql, CI/SQL/20160422142825_US3532-add-volunteer-checklist-page.sql, CI/SQL/20160422143720_US3532-add-volunteer-checklist-to-pagesection-gocincinnati.sql
Volunteer checklist page in GoCincinnati
=> US3532 - Create Volunteer check list

CI/SQL/20160502101200_US3706-create-event-template-copy-tool.sql
Update SQL scripts for new event tools
=> Fix tool setup

CI/SQL/20160503075100_US3539-add-GO-email-template.sql
=> US3539-add GO email template

Gateway/Crossroads.AsyncJobs/MinistryPlatform.config, Gateway/crds-angular/MinistryPlatform.config
US3706 - Updated config values to point back to Trips event page view
=> Fix Trips Issue

CI/SQL/20160509163201_US3429-dont-show-cancelled-events.sql
* scripted update to 5 page views
=> US3429 Don't show cancelled events on views

Gateway/MinistryPlatform.Translation.Test/Services/EventServiceTest.cs
=> Filter Sort Events

crossroads.net/app/mp_tools/admin_checkin_dashboard/adminCheckinDashboard.controller.js, crossroads.net/app/mp_tools/admin_checkin_dashboard/templates/adminCheckinDashboard.html, crossroads.net/spec/mp_tools/admin_checkin_dashboard/adminCheckinDashboard.controller.spec.js
https://rally1.rallydev.com/#/27593764268d/detail/userstory/55233895452
=> Add the date range filter to the checkin dashboard. 

crossroads.net/app/mp_tools/admin_checkin_dashboard/templates/eventRooms.html
https://rally1.rallydev.com/#/27593764268d/detail/userstory/55404635207
=> Update column names on checkin dashboard.

CI/SQL/20160511114500_US3884-allow-checkin-nullable.sql, Gateway/MinistryPlatform.Translation.Test/Services/RoomServiceTest.cs
US3884 - Updated unit test and added db script to alter event_room table
=> Allow checkin nullable

CI/SQL/20160511142115_DE1479-AddSortingToEventGroupsBySiteView.sql
https://rally1.rallydev.com/#/27593764268d/detail/defect/55706484789
=> Fix the sorting for events selection.

crossroads.net/package.json, crossroads.net/webpack.config.js
* Lock version of moment to 2.12.0
=> DE1478 Event Management Tool

crossroads.net/app/trips/signup/familySelectTool/familySelect.html
=> Fixed Trip Family Tabled Layout

CI/SQL/20160517110242_US4016-create-childcare-request-status-table.sql, CI/SQL/20160518015224_US4016-create-childcare-request-table.sql, CI/SQL/20160518024715_US4016-add-page-childcarerequeststatuses-under-lookupvalues.sql, CI/SQL/20160518032349_US4016-add-chilcarerequestpage.sql
Created childcare request  table
Added childcare request status page under look up values
Added childcare request page
=> Created childcare request status table

crossroads.net/app/media/singleMedia.controller.js
* fall back to sourceUrl if source.file is not available
=> DE1107 - Upload/Download CMS

CI/SQL/20160518082500_US3999-create-table-childcare-preferred-times.sql, CI/SQL/20160518092200_US3999-page-childcare-times.sql
US3999 - Table and Page for Childcare Preferred times
=> US3999 - Table and Page for Childcare Preferred times

CI/SQL/201605251417_DE1511-alter-sp-FacilityEventChangeTracking.sql
=> Alter sp to fix dup data

CI/SQL/20160525171832_US3738-undivided_groups.sql
* created script to add groups
=> US3738 Undivided Groups

CI/SQL/20160526114400_DE1485-NightlyBatchTripPledges.sql
=> Night Job Not Connecting Trip Pledges

CI/SQL/20160526120057_DE1497-AddFunctionToSplitProcessingFees.sql, CI/SQL/20160526120157_DE1497-UpdateGPExportPageViewToUseSplitingFunction.sql
https://rally1.rallydev.com/#/22244455064d/detail/defect/56149458765
=> Changes to GP Export Processing Fees.

CI/SQL/201605261305_DE1310-fix-subselects-Trip-Export-sp.sql
Altered stored procedure to handle multiple values returned from
subselects
=> Fix for subselect statements

crossroads.net/app/formBuilder/templates/formBuilder.html, crossroads.net/app/formBuilder/templates/groupParticipant/childcare.html, crossroads.net/app/formBuilder/templates/groupParticipant/coFacilitator.html, crossroads.net/app/formBuilder/templates/groupParticipant/coParticipant.html, crossroads.net/app/formBuilder/templates/groupParticipant/facilitatorTraining.html, crossroads.net/app/formBuilder/templates/groupParticipant/preferredSession.html, crossroads.net/app/formBuilder/templates/profile/birthdate.html, crossroads.net/app/formBuilder/templates/profile/email.html, crossroads.net/app/formBuilder/templates/profile/ethnicity.html, crossroads.net/app/formBuilder/templates/profile/gender.html, crossroads.net/app/formBuilder/templates/profile/location.html, crossroads.net/app/formBuilder/templates/profile/name.html
=> Cleaned up HTML

crossroads.net/app/mp_tools/mpTools.constants.js
* Updated to use All Backend Users Role
=> US3843 Request Childcare

CI/SQL/201600602134000_US3952-add-childcareapproval-tool.sql, CI/TestSQL/US3852-DevToolChildcareDecision.sql, crossroads.net/app/mp_tools/mpTools.routes.js
Feature us395 childcareapproval pjl
=> Feature us395 childcareapproval pjl

crossroads.net/app/mp_tools/add_event_tool/addEventTool.component.js
US3985 - Added confirmation dialog before save
=> Prompt to Save Room

CI/Reports/CRDS Facilities Event Change Tracking.rdl, CI/SQL/201606030828_US4087-alter-added-room-FacilityEventChangeTracking.sql
Added Room Name to existing Facilities Event Change Tracking report
=> US4087- added Room Info

Gateway/crds-angular.test/Services/EzScanCheckScannerServiceTest.cs, Gateway/crds-angular.test/Services/StripeServiceTest.cs, Gateway/crds-angular/Services/EzScanCheckScannerService.cs, Gateway/crds-angular/Services/Interfaces/IPaymentService.cs, Gateway/crds-angular/Services/StripeService.cs
https://rally1.rallydev.com/#/22244455064d/detail/userstory/51405633400
=> Dynamically pass a statement description to Stripe for Scanned Checks only

crossroads.net/app/mp_tools/request_childcare/requestChildcare.controller.js, crossroads.net/app/mp_tools/request_childcare/requestChildcare.html, crossroads.net/spec/mp_tools/request_childcare/requestChildcare.controller.spec.js
Two defects were worked in this branch:
[DE1543](https://rally1.rallydev.com/#/22244455064d/detail/defect/57067036178)
[DE1542](https://rally1.rallydev.com/#/22244455064d/detail/defect/57018108988)
* Followed styleguide to layout timepickers side-by-side
* Updated the onEndDate callback to actually change the model
=> DE1542 DE1543

CI/SQL/201606081452_DE1553-alter-sp-CRDS-BDay-Anniversary-By-Group.sql, CI/SQL/201606081453_DE1553-add-bday-anniversaries-report-myservegp-page.sql
Changed masking on Year from question marks to dashes in stored
procedure
=> Changed BDay Year Masking in stored procedure

CI/Reports/CRDS Volunteers by Site.rdl, CI/SQL/20160609_141300_US3448-report_CRDS_TotalVolsByLocation.sql, CI/SQL/20160609_1440000_US3448-add-crds-vol-site-report-page.sql
US3448 - Initial commit of report and sql
=> Volunteers by Site Report

Gateway/MinistryPlatform.Translation/Services/ChildcareRequestService.cs
Make sure time for childcare date is set to midnight
=> Make sure time for childcare date is set to midnight

CI/Reports/CRDS Volunteers by Group.rdl, CI/SQL/20160609-140000_US3449-report_CRDS_TotalVolsByGroup.sql, CI/SQL/20160609_1530000_US3449-add-crds-vol-group-report-page.sql
US3449 - Initial commit of report and sql
=> Volunteers by Group Report

CI/Reports/CRDS New Givers.rdl, CI/SQL/201606092310_US461-create-sp-report-CRDS-New-Givers.sql, CI/SQL/201606092311_US461-add-report-page-New-Givers.sql
Initial build for New Givers report
=> US461 Create New Givers Report

crossroads.net/app/mp_tools/request_childcare/requestChildcare.controller.js
DE1565-reset dateselected flag when generateDateList runs
=> DE1565-reset dateselected flag when generateDateList runs

CI/Reports/CRDS New Givers.rdl, CI/SQL/201606211622_DE1571-alter-sp-report-CRDS-New-Givers_add_detail.sql
DE1571 - uploaded proc and report
=> Add Co Giver Giver Information

CI/Reports/CRDS Large Donations.rdl, CI/SQL/20160630_0730_US477-create-sp-report-CRDS-Large-Donations.sql, CI/SQL/20160630_0756_US477-add-report-page-Large-Donations.sql
Large Donations report includes stored procedure, SSRS, add to MP script.
=> Large Donations report

crossroads.net/app/app.js, crossroads.net/app/constants.js, crossroads.net/app/group_tool/groupTool.routes.js, crossroads.net/app/group_tool/index.js, crossroads.net/app/group_tool/my_groups/index.js, crossroads.net/app/group_tool/my_groups/myGroups.component.js, crossroads.net/app/group_tool/my_groups/myGroups.controller.js, crossroads.net/app/group_tool/my_groups/myGroups.html
This is just the foundation piece to start building out the group tools under the group tools directory using es6/es2015.
=> Add the foundation to doing group tool feature in es6 on the front end.

crossroads.net/app/mp_tools/add_event_tool/addEvent.service.js, crossroads.net/app/mp_tools/add_event_tool/add_event/addEvent.component.js
Check for childcare event upon load so back button properly behaves
=> Check for childcare event upon load so back button properly behaves

crossroads.net/app/mp_tools/add_event_tool/add_event/add_event.html
use CMS message childcareAgeMessage
=> Add error message when max age is out of range

crossroads.net/app/group_tool/group_detail/about/groupDetail.about.html
Shifted columns around, shrunk profile image to make more room for data.
=> US4262: Update per comments from McDavid

crossroads.net/app/mp_tools/add_event_tool/addEventTool.component.js, crossroads.net/app/mp_tools/add_event_tool/add_event/addEvent.component.js
=> DE1594 - min max validations

crossroads.net/app/index.html, crossroads.net/app/streaming/streaming.component.html, crossroads.net/app/streaming/streaming.component.js, crossroads.net/app/streaming/streaming.component.js.map, crossroads.net/app/streaming/streaming.component.ts, crossroads.net/styles/main.scss, crossroads.net/styles/pages/streaming.scss
This PR delivers [US-4361](https://rally1.rallydev.com/#/41662702253d/detail/userstory/58571943886) by implementing static HTML/CSS for the updated streaming landing page. 
Since this work originated as a sub-branch of [`US4291-bootstrap-for-angular2`](https://github.com/crdschurch/crds-angular/tree/US4291-bootstrap-for-angular2) this PR is attempting to merge these updates back into that branch vs `development` but let me know if you'd prefer this be handled in another fashion. 
**NOTE:** 
Some of the elements here are still being reviewing / receiving feedback so some items may not match the concepts and/or prototype exactly. We're operating under the assumption that the following things will need to happen after this code has been merged...
=> US-4361: HTML for Streaming Landing Page

crossroads.net/app/group_tool/group_detail/about/groupDetail.about.html, crossroads.net/app/group_tool/group_detail/groupDetail.controller.js, crossroads.net/app/group_tool/group_detail/groupDetail.html, crossroads.net/app/group_tool/group_detail/participants/groupDetail.participants.controller.js, crossroads.net/app/group_tool/group_detail/participants/groupDetail.participants.html, crossroads.net/app/group_tool/group_detail/participants/participant_card/groupDetail.participant.card.html, crossroads.net/app/group_tool/group_detail/requests/groupDetail.requests.controller.js, crossroads.net/app/group_tool/group_detail/requests/groupDetail.requests.html, crossroads.net/app/group_tool/services/group.service.js, crossroads.net/styles/modules/group-participants-cards.scss
* Group Detail UI updates, from review by @Dmacatude 
* [US4261](https://rally1.rallydev.com/#/27593764268d/detail/userstory/58429119512) and [US4263](https://rally1.rallydev.com/#/27593764268d/detail/userstory/58429124813)
=> Group detail UI updates

crossroads.net/app/streaming/event.ts, crossroads.net/app/streaming/streamspot.service.ts
Added filter to remove deleted streaming events
=> Filter deleted streaming events

crossroads.net/app/boot.ts, crossroads.net/package.json
Fix for IE 11 compatibility issues. Specifically required ES6-shim.
=> DE1610: IE11Compatibility

Gateway/MinistryPlatform.Translation.Test/MinistryPlatform.Translation.Test.csproj, Gateway/MinistryPlatform.Translation.Test/Services/GroupRepositoryTest.cs, Gateway/MinistryPlatform.Translation/Repositories/GroupRepository..cs, Gateway/MinistryPlatform.Translation/Repositories/Interfaces/IGroupRepository.cs, Gateway/crds-angular.test/Services/ChildcareServiceTest.cs, Gateway/crds-angular.test/Services/GroupServiceTest.cs, Gateway/crds-angular/Models/HouseHoldData.cs, Gateway/crds-angular/Services/ChildcareService.cs, Gateway/crds-angular/Services/GroupService.cs, Gateway/crds-angular/Services/Interfaces/IChildcareService.cs, Gateway/crds-angular/Services/Interfaces/IGroupService.cs, Gateway/crds-angular/crds-angular.csproj
DE1597
* create new repo method that gets all groups
* Update tests
*
=> Look at all groups, not just community groups

crossroads.net/app/childcare_dashboard/childcare_group/childcareDashboardGroup.controller.js, crossroads.net/spec/childcare_dashboard/childcare_group/childcareGroup.controller.spec.js
[DE1607](https://rally1.rallydev.com/#/27593501023d/detail/defect/59088840730)
* update to look for `status` of http response instead of `statusCode`
=> Group full message not displaying correctly

crossroads.net/app/streaming/streaming.component.html, crossroads.net/app/streaming/streaming.component.ts, crossroads.net/package.json
This PR delivers [US4412](https://rally1.rallydev.com/#/41662702253/detail/userstory/58961988131) by implementing some simple CSS transitions on primary elements of the streaming landing page. As the user scrolls down, elements are revealed like magic :tophat: :rabbit: 
Let me know if you have any questions.
=> US4412: Add CSS transitions 

crossroads.net/spec-es6/group_tool/create_group/createGroup.controller.spec.js
=> US4458: Fix failing test

crossroads.net/app/streaming/streaming.component.html, crossroads.net/app/streaming/streaming.component.ts, crossroads.net/styles/pages/streaming.scss
This PR addresses @bzmillerboy's comments on [US4419](https://rally1.rallydev.com/#/41662702253d/detail/userstory/58984628724/discussion) and [US4412](https://rally1.rallydev.com/#/41662702253d/detail/userstory/58961988131/discussion) as well as some additional cleanup of some elements on mobile devices. Please let me know if you'd prefer a single PR for each user story.
=> US4419 / US4412: Production Images / CSS Transitions

CI/SQL/20160719_133505_DE1523-UpdateJoinGroupNotificationProcessTriggerFieldToParticipentID.sql
pdate process to use participant as trigger field to workaround MP bug
=> DE1523 update process

crossroads.net/app/childcare_dashboard/childcare_group/childcareDashboardGroup.controller.js, crossroads.net/app/childcare_dashboard/childcare_group/childcareGroup.html
[DE1627](https://rally1.rallydev.com/#/27593501023d/detail/defect/59453299666)
=> Removed ng-disabled because it was causing issues

crossroads.net/styles/pages/streaming.scss
This PR fixes a build error related to US4361.
=> US4361: Streaming Landing

crossroads.net/app/formlyBuilder/formlyBuilder.run.js, crossroads.net/app/formlyBuilder/templates/profilePicture.html, crossroads.net/app/group_tool/formlyWrappers/createGroupProfilePicture.html, crossroads.net/app/group_tool/groupTool.formlyConfig.js, crossroads.net/app/group_tool/groupTool.routes.js, crossroads.net/app/group_tool/index.js, crossroads.net/app/group_tool/services/createGroup.service.js, crossroads.net/app/group_tool/services/group.service.js
Also fixed DE1632. Note: this doesn't fix the existing defect where it doesn't refresh when you add a profile picture.
=> US4378: Leader manages profile picture.

crossroads.net/app/group_tool/services/createGroup.service.js
Show and hide fields based on selections. (When will your group meet and Where will your group meet sections)
=> US4379: Create Groups Cross field logic.

crossroads.net/app/streaming/video.ng2component.html, crossroads.net/styles/pages/streaming.scss
This PR implements the existing "active viewers" iframe (via S3) on the streaming landing page.
=> US4289: Specify Number of Viewers

crossroads.net/app/streaming/data/content-blocks.csv, crossroads.net/app/streaming/streaming.ng2component.html
This PR updates the streaming landing page to use the dynamic content directive for current series and past weekend content.
=> US4555: Series Content Blocks

Gateway/MinistryPlatform.Translation/Repositories/GroupRepository.cs
[DE1640](https://rally1.rallydev.com/#/27593501023d/detail/defect/59573976603)
=> use env var BaseUrl instead of BaseMPUrl

crossroads.net/core/templates/header.html
Hide the my group menu item on the profile menu
=> Hide My Groups menu item

crossroads.net/app/trips/tripgiving/tripgiving.controller.js
Fix bug so that it works the second time
=> DE1570: Don't init until after state change success so

crossroads.net/app/group_tool/group_detail/requests/invite/groupDetail.invite.controller.js, crossroads.net/app/group_tool/group_detail/requests/invite/groupDetail.invite.html
https://rally1.rallydev.com/#/27593764268d/detail/defect/59852027836
=> DE1669 - Add new function to cancel invite and have the Cancel button call that.

Gateway/MinistryPlatform.Translation.Test/Services/GroupToolRepositoryTest.cs, Gateway/MinistryPlatform.Translation/Repositories/GroupToolRepository.cs, Gateway/MinistryPlatform.Translation/Repositories/Interfaces/IGroupToolRepository.cs, Gateway/crds-angular.test/Services/GroupToolServiceTest.cs, Gateway/crds-angular/Services/GroupToolService.cs
DE1672 - Removed user token in a couple of places that we didn't know they needed to be removed from.
=> API User Issue for Invites

crossroads.net/app/group_tool/group_detail/requests/groupDetail.requests.html
* Change Request column label to "Request Type"
* Re-order buttons to Deny / Approve
* Approve button primary color
* Deny button standard color
=> US4588 - Group requests page UI changes

crossroads.net/app/group_tool/groupTool.routes.js, crossroads.net/app/group_tool/group_search/groupSearch.component.js, crossroads.net/app/group_tool/group_search/groupSearch.controller.js, crossroads.net/app/group_tool/group_search/groupSearch.html, crossroads.net/app/group_tool/group_search/index.js, crossroads.net/app/group_tool/index.js
HTML template for Find a Group search form.  Responsive for desktop, tablet, mobile.  Follows style guide.  Uses `<loading-button>` directive for submit loading state
=> US4592 - Find a Group UI

crossroads.net/app/streaming/data/content-blocks.csv
This PR delivers [DE1683](https://rally1.rallydev.com/#/41662702253d/detail/defect/60055808131) and [DE1684](https://rally1.rallydev.com/#/41662702253d/detail/defect/60055989130) by updating the CSV with current copy. Note– these content blocks exist in both INT & PROD environments.
=> DE1683 / DE1684: Current Series Content

Gateway/crds-angular/Services/ChildcareService.cs
[DE1671](https://rally1.rallydev.com/#/27593501023d/detail/defect/59876593040)
=> Max age inclusive

Gateway/crds-angular/Services/ChildcareService.cs
[DE1694](https://rally1.rallydev.com/#/27593501023d/detail/defect/60170477824)
* don't try to send email if there is no email address (bad data)
* update base_Url with https
=> Prefix base_url with https

Gateway/crds-angular.test/Services/InvitationServiceTest.cs, Gateway/crds-angular/Services/InvitationService.cs
US4483 - Addressed some problems with the reply to email field and leader name merge tag
=> Leader Sends Invite

Gateway/crds-angular/MinistryPlatform.Debug.config, Gateway/crds-angular/MinistryPlatform.Demo.config, Gateway/crds-angular/MinistryPlatform.Integration.config, Gateway/crds-angular/MinistryPlatform.Release.config, Gateway/crds-angular/MinistryPlatform.config
[DE1696](https://rally1.rallydev.com/#/27593501023d/detail/defect/60172285808)
Create a transform for int and debug this way when production gets copied
down, we can just remove the transform in the development environment and
production/demo is never effected.
=> Update debug and int configs

crossroads.net/app/group_tool/group_invitation/groupInvitation.controller.js, crossroads.net/app/group_tool/group_invitation/groupInvitation.html
https://rally1.rallydev.com/#/27593764268d/detail/defect/60295445036
=> Fix to show the right button when one processes is happening.

crossroads.net/app/group_tool/group_search_results/groupSearchResults.html
Add "Close" and "Request to Join" buttons to the Group Search Results - Group Detail expanded view.
=> US4639 - Group Search Result Details - Add "Close" and "Request to Join"

crossroads.net/app/group_tool/create_group/preview/createGroup.preview.controller.js
Growls now showing on create AND edit and also on save failure.
=> de1697: growl messages

crossroads.net/app/group_tool/services/createGroup.service.js
Also removes start date and defaults it to todays date. (US4652)
=> DE1725: Reorder create group.

crossroads.net/app/group_tool/groupTool.routes.js, crossroads.net/app/group_tool/group_detail/participants/groupDetail.participants.html, crossroads.net/app/group_tool/group_detail/requests/groupDetail.requests.controller.js, crossroads.net/app/group_tool/group_detail/requests/groupDetail.requests.html, crossroads.net/spec-es6/group_tool/group_detail/requests/groupDetail.requests.controller.spec.js
* Always show help content for participant
* Show Request help content when there are no inquiries or invites
* Hide participant Edit and Email Group buttons when leader is the only person in group (count == 1)
=> US4644 - Participant and Requests tab help content

crossroads.net/app/group_tool/my_groups/myGroups.html
=> US4623 - Add a content block for My Groups when there are zero groups

CI/SQL/20160805_102200_US4657-Update-Group-Type-Attribute-Names.sql
[US4657](https://rally1.rallydev.com/#/22244455064d/detail/userstory/60401251277)
**Group Type Choices**
* Men and women together (like God intended).
* Men only (no girls allowed).
* Women only (don’t be a creeper, dude).
* Couples (married, engaged, etc.).
**Expected output:**
=> US4657: Update group type attributes, per latest copy

crossroads.net/app/group_tool/my_groups/myGroups.controller.js, crossroads.net/app/group_tool/my_groups/myGroups.html
* Make a determination on the my groups page if the user is a Leader.  If a leader, show them a content block with leader links.  If a participant, show them an alternate content block without the "Being a Leader" link.
* Group Resources link in content block refers to CMS page
* Feedback/Support link is mailto:groups@crossroads.net
* Being a Leader link is still TBD and will not work
=> US4621 - My Groups page Right Hand navigation links

CI/SQL/20160808_083700_DE1726-cannot-search-on-frequency.sql
DE1726 - Included missing subquery and fixed column name
=> Cannot Search By Frequency

CI/Reports/CRDSWeeklyGivingByProgram.rdl, CI/SQL/20160809_0821_DE1743-sp-add-softcredit-donation-status.sql
Changes to stored procedure (soft credit, donation time format, donation status). 
Changes to SSRS (added donation status as dropdown).
=> Add softcredit-donationmillisecond-donationstatus to stored procedure

crossroads.net/app/group_tool/services/createGroup.service.js
Removed duplicate participants setter. Don't Merge this without kathryn's OK
=> DE1750: Include email address.

CI/Reports/CRDS Large Donations.rdl
being pulled by the stored proc
=> DE1699: Added city and state columns to the report. The data was already

crossroads.net/app/group_tool/groupTool.routes.js, crossroads.net/app/group_tool/group_search_results/groupSearchResults.controller.js, crossroads.net/app/group_tool/group_search_results/groupSearchResults.html
https://rally1.rallydev.com/#/27593764268d/detail/userstory/59649511619
=> Minor Search Refactoring

CI/SQL/20160811_164959_US4671-FixScriptToOnlyLookAtPublicGroups.sql
https://rally1.rallydev.com/#/27593764268d/detail/userstory/60574915263
=> Fix up script.

Gateway/MinistryPlatform.Translation/Models/DTO/MpGroupSearchResultDto.cs
DE1773 - Added exception handling to deal with bad group data
=> Cannot Search on Address

crossroads.net/app/group_tool/group_search_filter/groupSearchFilter.controller.js, crossroads.net/app/group_tool/group_search_filter/groupSearchFilter.html, crossroads.net/styles/helpers/utilities.scss, crossroads.net/styles/main.scss, crossroads.net/styles/modules/group-search-filter.scss
**Note: Selected filter tags and "Clear Filters" are hidden on mobile**
=> US4695 - Filter Search UI

crossroads.net/app/group_tool/group_search_filter/groupSearchFilter.html
* Hide "Clear Filters" if no filters are set
* Always hide "Clear Filters" on mobile
* Always hide filter tags on mobile
* Show the "Filter" button full width on mobile
=> US4695 - Hide "Clear Filters" if no filters are set; Hide filter tags on mobile

crossroads.net/app/group_tool/group_search_results/groupSearchResults.html
Added a content block that is visible when the results have been queried and the array is length 0.  I also hide the table header row when array is == 0
=> US4643 - No Search Results content block text

crossroads.net/styles/pages/streaming.scss
This PR corrects some rendering issues associated with the player during a live stream.
=> US4536: Streaming Video Embed

crossroads.net/app/group_tool/model/smallGroup.js, crossroads.net/spec-es6/group_tool/model/smallGroup.spec.js
https://rally1.rallydev.com/#/27593764268d/detail/defect/60482803315
=> Fix time to use moment to be non military.

crossroads.net/app/group_tool/group_search_results/groupSearchResults.html
https://rally1.rallydev.com/#/27593764268d/detail/defect/60995118637
=> Fix to not show map link if there is nothing in address.

crossroads.net/app/group_tool/group_detail/about/groupDetail.about.html
https://rally1.rallydev.com/#/27593764268d/detail/defect/61120310520
=> Fix to only allow the leader to see the group visibilty on the my group about

crossroads.net/app/group_tool/my_groups/myGroups.html, crossroads.net/styles/modules/group-cards.scss
Clicking Find a Group now navigates to the search page
=> US4769 - Re-enabling Find a Group on My Groups

crossroads.net/app/group_tool/group_search_results/groupSearchResults.html
US4640 was already in acceptance review, when @dmiyamasu noticed it was not working properly on mobile.  Pulled the story back to developing to fix mobile.
=> US4640: Hide search result when detail open on mobile

Gateway/Crossroads.AsyncJobs/MinistryPlatform.Release.config, Gateway/Crossroads.AsyncJobs/MinistryPlatform.config, Gateway/crds-angular/MinistryPlatform.Release.config, Gateway/crds-angular/MinistryPlatform.config
=> Limit Distance Graph Search Results By Environment

crossroads.net/app/group_tool/confirm_request/confirmRequest.controller.js, crossroads.net/app/group_tool/confirm_request/confirmRequest.html
Show joined with commas when multiple leaders
=> US4737 - Show leader's name on the Contact Group Leader form

crossroads.net/app/streaming/current-series.component.ts, crossroads.net/core/services/CMSData.service.ts
Allow for current series to fall back to last series if no series is scheduled into the future.
=> US4802: Allow for current series to fall back

crossroads.net/app/group_tool/group_search_filter/filter_impl/groupType.filter.js, crossroads.net/app/group_tool/group_search_filter/groupSearchFilter.controller.js, crossroads.net/spec-es6/group_tool/group_search_filter/filter_impl/groupType.filter.spec.js, crossroads.net/spec-es6/group_tool/group_search_filter/groupSearchFilter.controller.spec.js
* [US4775 - Group Type search filter](https://rally1.rallydev.com/#/27593764268d/detail/userstory/61286430389)
=> US4775: Add Group Type search filter

crossroads.net/app/group_tool/group_search_filter/groupSearchFilter.html, crossroads.net/app/group_tool/group_search_results/groupSearchResults.controller.js, crossroads.net/app/group_tool/group_search_results/groupSearchResults.html
=> US4800 - Format multiple columns of search filters

CI/Reports/CRDS Staff Giving.rdl
Change report headings to only show: Giving, Last Name, First Name. 
Removing: Household ID, Display Name
Adding: date range when the report was run
=> SSRS Change report column headings

crossroads.net/app/group_tool/end_group/endGroup.html
=> US4795 - Center the end group form

crossroads.net/app/trips/signup/tripDeposit/tripDeposit.controller.js, crossroads.net/app/trips/signup/tripsSignup.controller.js
Fixes [DE1852](https://rally1.rallydev.com/#/27593501023d/detail/defect/61784833711)
* add rules in stateChanges to prevent unwanted navigation
=> do not allow going back to app from thankyou page

crossroads.net/app/common/profile/household/profileHousehold.controller.js, crossroads.net/app/profile/profile.controller.js
Fixed site display on crossroads.net
=> DE1848: ._find was passing in wrong parameters

crossroads.net/app/group_tool/group_search_results/groupSearchResults.controller.js, crossroads.net/app/group_tool/group_search_results/groupSearchResults.html
=> US4844 - Add an additional content block for filters showing no results

Gateway/crds-angular.test/controllers/GroupControllerTest.cs, Gateway/crds-angular/Controllers/API/GroupController.cs
* [DE1861 - Geocode address when editing a group](https://rally1.rallydev.com/#/27593764268d/detail/defect/61952503453)
=> DE1861: Geocode addresses when editing a group

crossroads.net/app/group_tool/group_resources/model/groupResourceCategory.js, crossroads.net/spec-es6/group_tool/group_resources/model/groupResourceCategory.spec.js
* [DE1871 - Default Group Category not working](https://rally1.rallydev.com/#/22244455064d/detail/defect/62050503046)
=> DE1871: Detect default group category properly

crossroads.net/app/group_tool/group_detail/about/groupDetail.about.html
=> US4790 - Change attribute order for group detail component

crossroads.net/app/streaming/streaming.ng2component.html, crossroads.net/app/streaming/video.ng2component.html, crossroads.net/styles/pages/streaming.scss
This PR addresses the style regressions identified by [US4847](https://rally1.rallydev.com/#/41662702253d/detail/userstory/61712292945). Let me know if you have any questions.
=> US4847 - Digital Program Layout Tweaks

crossroads.net/app/streaming/reminder-modal.ng2component.html, crossroads.net/app/streaming/reminder.ts
This PR updates the reminder modal so that the text/phone input is the default option. Let me know if you have any questions.
=> DE1876 - Stream Reminder Defaults

crossroads.net/app/streaming/current-series.ng2component.html, crossroads.net/styles/pages/streaming.scss
This PR updates the styles associated with the series trailer modal window so it is more consistent with the reminder-modal styles, per @bzmillerboy's comments on [US4632](https://rally1.rallydev.com/#/41662702253d/detail/userstory/60251622693/discussion).
=> US4632 - Series Trailer Modal

crossroads.net/app/downgrades.ts, crossroads.net/app/streaming/content-card.component.ts, crossroads.net/app/streaming/content-card.ng2component.html, crossroads.net/app/streaming/video.component.ts, crossroads.net/app/streaming/video.ng2component.html, crossroads.net/core/linked_content/linked-content-ng2.component.ts, crossroads.net/spec-ts/core/linked_content/linked-content-ng2.component.spec.ts, crossroads.net/styles/pages/streaming.scss
This PR updates the digital program and streaming landing page with a new component that will conditionally link to content, if there is a link provided by the CMS. Please see [DE1883](https://rally1.rallydev.com/#/41662702253d/detail/defect/62124203665) for details.
=> DE1883 - Conditional Links

CI/SQL/20160901_141200_DE1877-NewGiversReport_update_sp.sql
donations also to determine first donation date
=> DE1877: For soft credit donations, look at soft donor's regular (not sc)

crossroads.net/app/streaming/video.ng2component.html, crossroads.net/styles/pages/streaming.scss
Tweak header of live stream modal per @bzmillerboy's comments
=> DE1882 - Close Modal Button

crossroads.net/app/streaming/reminder-modal.component.ts
Fix regression error in reminder modal, see [DE1888](https://rally1.rallydev.com/#/41662702253d/detail/defect/62181352903).
=> DE1888 - Set Reminder Default View

crossroads.net/app/group_tool/group_search_filter/filter_impl/meetingDay.filter.js, crossroads.net/app/group_tool/group_search_filter/groupSearchFilter.controller.js, crossroads.net/spec-es6/group_tool/group_search_filter/filter_impl/meetingDay.filter.spec.js, crossroads.net/spec-es6/group_tool/group_search_filter/groupSearchFilter.controller.spec.js
https://rally1.rallydev.com/#/27593764268d/detail/userstory/61288988298
=> Added meeting day filter to group tool search.

Gateway/crds-angular.test/Services/GroupToolServiceTest.cs, Gateway/crds-angular/Services/GroupToolService.cs
US4807 - Initial commit of code
=> Email All Groups Leaders

crossroads.net/app/group_tool/group_search_filter/filter_impl/meetingDay.filter.js, crossroads.net/app/group_tool/group_search_filter/groupSearchFilter.controller.js
https://rally1.rallydev.com/#/27593764268d/detail/userstory/61288988298
=> Add flexible meeting time.

CI/SQL/20160907_154800_US4873-GetGroupCategoriesFunction.sql, CI/SQL/20160907_155500_US4873-GetGroupLeaderEmails.sql, CI/SQL/20160907_162800_US4873-SmallGroupsWithCategoryDetailsPageView.sql
* [US4873 - Custom View with Group Category Details](https://rally1.rallydev.com/#/27593764268d/detail/userstory/62018716833)
=> US4873: Create Small Group Category Details Page View

crossroads.net/app/group_tool/group_search_results/groupSearchResults.html
https://rally1.rallydev.com/#/27593764268d/detail/defect/62589264917
=> Fix to point to the actual dataset instead of the returned results from API

crossroads.net/app/trips/signup/tripsSignup.controller.js
[DE1914](https://rally1.rallydev.com/#/27593501023d/detail/defect/62605821287)
:radio_button:  set `vm.submitting` to false if there is an error in the form
=> update next button loading state

crossroads.net/app/trips/signup/pageTemplates/signupPage3.html
[DE1917](https://rally1.rallydev.com/#/27593501023d/detail/defect/62613941924)
This is now required for Three Amigos :es:
=> make emergency contact required

CI/SQL/20160909_092500_US4482-UnplacedGroupInquiriesPageView.sql, CI/SQL/20160909_102500_US4482-CreatePendingGroupRequestsEmailTemplate.sql, Gateway/Crossroads.AsyncJobs/Unity.config, Gateway/Crossroads.ScheduledDataUpdate/App.Release.config, Gateway/Crossroads.ScheduledDataUpdate/App.config, Gateway/Crossroads.ScheduledDataUpdate/Crossroads.ScheduledDataUpdate.csproj, Gateway/Crossroads.ScheduledDataUpdate/Program.cs, Gateway/Crossroads.ScheduledDataUpdate/ScheduledDataUpdate.Unity.config, Gateway/MinistryPlatform.Translation.Test/Services/GroupToolRepositoryTest.cs, Gateway/MinistryPlatform.Translation/Repositories/GroupToolRepository.cs, Gateway/MinistryPlatform.Translation/Repositories/Interfaces/IGroupToolRepository.cs, Gateway/crds-angular.test/Services/GroupToolServiceTest.cs, Gateway/crds-angular/MinistryPlatform.config, Gateway/crds-angular/Services/GroupToolService.cs, Gateway/crds-angular/Services/Interfaces/IGroupToolService.cs, Gateway/crds-angular/Unity.config
* [US4482 - Pending group request reminder email](https://rally1.rallydev.com/#/27593764268d/detail/userstory/59425682120)
* **NOTE:** There is also a [pull request](https://github.com/crdschurch/schedule-jobs/pull/8) in schedule-jobs for this story.  Please review that as well.
=> US4482: Send emails for old pending group requests

CI/Reports/CRDS Quarterly Giving List.rdl, CI/SQL/20160909_104400_US4829-create_sp_report_CRDS_Giving_List.sql, CI/SQL/20160909_150738_US4054-createReportQuarterlyGivingList.sql
new report, add report in mp to Donor page, new sp
=> US4829: New Quarterly Giving List report

crossroads.net/app/group_tool/group_search_filter/groupSearchFilter.controller.js, crossroads.net/app/group_tool/group_search_filter/groupSearchFilter.html, crossroads.net/spec-es6/group_tool/group_search_filter/groupSearchFilter.controller.spec.js, crossroads.net/styles/modules/group-search-filter.scss, crossroads.net/styles/pages/group-search-results.scss
=> US4898 - New Search Filter layout

crossroads.net/app/group_tool/group_detail/participants/groupDetail.participants.html
https://rally1.rallydev.com/#/27593764268d/detail/userstory/62248630944
=> add ng-class to determine if sm-col-pull should be used.

CI/Reports/CRDS Groups Snapshot Summary.rdl, CI/SQL/20160913_081700_US4748-groups-summary-proc.sql
US4917 - Extends the CRDS Groups Snapshot Summary report to show groups created by week.
=> Staff Views Groups Created by Date

CI/Reports/CRDS Groups Snapshot Summary.rdl, CI/SQL/20160914_095600_US4916-crds-Participant-Start-Date.sql
=> Group Participants by Date

crossroads.net/app/profile/personal/profilePersonal.html
[DE1934](https://rally1.rallydev.com/#/27593501023d/detail/defect/62999241602)
=> Send the correct contactId to the profile component

crossroads.net/app/common/profile/personal/profilePersonal.controller.js, crossroads.net/app/signup/community_group_signup/communityGroupSignup.controller.js, crossroads.net/app/signup/community_group_signup/communityGroupSignupForm.html
[DE1934](https://rally1.rallydev.com/#/27593501023d/detail/defect/62999241602)
* pass the contactId to the profile directive
* make sure the contactId is a number in the profile directive
=> Allow change email in Community Group profile

crossroads.net/app/common/profile/personal/profilePersonal.controller.js
[DE1929](https://rally1.rallydev.com/#/27593501023d/detail/defect/62941404982)
=> Don't set oldEmail if we are still in the trip flow

CI/SQL/20160914-164800_DE1937-update-report-stored-proc-with-correct-attribute_type-ids.sql
The Stored Procedure had the wrong id's for both new attributes. This is
because I gave @plachmann bad information... Please forgive me @plachmann!
:cold_sweat:
=> DE1937 Fix Detailed Trip Report

Gateway/crds-angular/Services/GroupToolService.cs
https://rally1.rallydev.com/#/27593764268d/detail/userstory/61955443215
=> Fix to allow someone who has requested in the past and accepted unless a current member

CI/Reports/CRDSAmigosExport.rdl
original query contrained the pledge campaign selection to only Nicaragua trips.
=> Modify query for selecting pledge campaign to show all active campaigns

crossroads.net/app/group_tool/group_detail/requests/invite/groupDetail.invite.html
=> US4921 - Change label to "Message" on Invite Someone form

crossroads.net/app/formlyBuilder/formlyConfig/types/templates/multiCheckBoxCombo.html
Also fix padding below the checkbox inputs
**Updated on Left, Old version on Right**
=> US4797 - Fix the left alignment on the checkboxes

crossroads.net/app/formlyBuilder/formlyBuilder.module.js
DE1953 - Validation issue for Create & Edit Group
=> DEXXX adding validation back in create group form

CI/Reports/Weekend Service Crossroads.rdl
This is the rdl file that TM placed on our INT servers (not the rdl file that they actually emailed to us).
=> US2742 updated rdl file

crossroads.net/spec-es6/live_streaming/services/streamspot.service.spec.js, crossroads.net/spec-es6/live_streaming/streaming_reminder/streamingReminder.controller.spec.js
=> DE1961/Commented Out Test Scripts for Deployment (will fix later)

Gateway/MinistryPlatform.Translation.Test/Services/InvitationRepositoryTest.cs, Gateway/MinistryPlatform.Translation/Repositories/InvitationlRepository.cs, Gateway/crds-angular/Services/GroupToolService.cs
membership, look for specific member that is logged in instead of Any()
=> US5337: Hotfix for group tool link defect. When checking for group

CI/SQL/20161011_111000_US5283-CreateApiKeyTable.sql, CI/SQL/20161011_111500_US5283-CreateApiKeyPage.sql
* This is the database scripts for [US5283 - Domain-Locked API keys](https://rally1.rallydev.com/#/27593764268d/detail/userstory/67014143924/tasks)
* **Please also review [this PR in SignInCheckIn](https://github.com/crdschurch/crds-signin-checkin/pull/21) before green-checking the story.**
=> US5283: Table and page for API keys

crossroads.net/app/my_serve/index.js, crossroads.net/app/my_serve/myserve.html, crossroads.net/app/my_serve/refine/refineList.html, crossroads.net/app/my_serve/serveTeam.directive.js, crossroads.net/app/my_serve/serveTeam.html, crossroads.net/app/my_serve/serveTeamAutocomplete.html, crossroads.net/app/my_serve/serve_team_members/serveTeamMembers.controller.js, crossroads.net/app/my_serve/serve_team_message/serveTeamMessage.component.js, crossroads.net/styles/pages/serve.scss
=> US5088 Volunteer Sign Up

crossroads.net/app/my_serve/serveTeam.html
=> DE2008 - remove Ng Repeat on Not Available

crossroads.net/app/media/singleMedia.controller.js, crossroads.net/app/media/templates/mediaDetails.html, crossroads.net/app/media/templates/mediaSingle.html, crossroads.net/app/media/templates/messageActionButtons.html, crossroads.net/styles/pages/media.scss
Show the 3 weekend summary CMS fields in a collapse
* Key Points
* Discussion Questions
* Additional Resources
=> US5331 - Weekend Summary

crossroads.net/app/live_stream/services/geolocation.service.js, crossroads.net/spec-es6/live_streaming/services/geolocation.service.spec.js
=> DE2053 - move success flag

crossroads.net/app/live_stream/services/stream-status.service.js, crossroads.net/spec-es6/live_streaming/services/stream-status.service.spec.js
Fix moment object being undefined as per failure on this build:
http://mp-ci.centralus.cloudapp.azure.com/viewLog.html?tab=buildLog&buildTypeId=Code_Integration_Crossroads&buildId=10278#_focus=7563
=> DE2099 - Fix Failing Tests 

Gateway/MinistryPlatform.Translation/Repositories/Interfaces/IEventRepository.cs, Gateway/crds-angular.test/Services/CampServiceTest.cs, Gateway/crds-angular/Services/CampService.cs
fixed save gender to contacts
fixed nick name
updated display name
=> fixing save gender id, display name, nick name and check event participant

crossroads.net/app/camps/camp.controller.js, crossroads.net/app/camps/camp.html, crossroads.net/spec/camps/camp.component.spec.js, crossroads.net/spec/camps/campHelpers.js
[DE2102](https://rally1.rallydev.com/#/detail/defect/71341365452?fdp=true)
* Pull cms message if registration is closed
* don't show any of the other routes if registration is closed
=> DE2102 Summer Camps - handle registration date correctly

Gateway/MinistryPlatform.Translation.Test/Services/GroupParticipantRepositoryTest.cs, Gateway/MinistryPlatform.Translation/Repositories/GroupParticipantRepository.cs
Not a defect yet, but fixed anyways
=> removed =to from end date

CI/SQL/20161027-091400_US5192-kiosk-types-table.sql, CI/SQL/20161027_101800_US5192-kiosk-configs-table.sql, CI/SQL/20161027_103400_US5192-add-kiosk-types-page.sql, CI/SQL/20161027_103500_US5192-add-kiosk-configs-page.sql, CI/SQL/20161028_0844_US5192-script-kiosk-types.sql
=> Adding Tables and Pages for Kiosk Config

Gateway/MinistryPlatform.Translation.Test/Services/GroupRepositoryTest.cs, Gateway/MinistryPlatform.Translation.Test/Services/MinistryPlatformRestServiceIntegrationTest.cs, Gateway/MinistryPlatform.Translation/Repositories/GroupRepository.cs, Gateway/MinistryPlatform.Translation/Repositories/Interfaces/IGroupRepository.cs, Gateway/crds-angular.test/Services/CampServiceTest.cs, Gateway/crds-angular/Services/CampService.cs
* added new repository method to get grade group from rest
* called new method from campsService
=> DE2119 Page Load Time

Gateway/crds-angular.test/Services/CampServiceTest.cs, Gateway/crds-angular/Services/CampService.cs
* added tests for not head of household
* only return current user if not head of household
=> US5342 Camp Signup NonHead

crossroads.net/app/camps/camp_waivers/camp_waivers.html
=> DE2153 - Show error message when waivers are not set up for camp

crossroads.net/app/formlyBuilder/formlyConfig/types/crdsMultiCheckBoxCombo.js, crossroads.net/app/formlyBuilder/formlyConfig/types/templates/crds-multiCheckBoxCombo.html, crossroads.net/app/group_tool/services/createGroup.service.js, crossroads.net/spec-es6/live_streaming/services/countdown.service.spec.js
=> updated control and usage

crossroads.net/app/common/profile/personal/profilePersonal.controller.js
retrieve the attendance start date# Please enter the commit message for your changes. Lines starting
=> DE2180: Get Personal instead of person in edit profile so that you

crossroads.net/app/camps/camps.routes.js
Ensure that the thank you page has a resolve to retrieve the family information for the household list component
=> US5238 - Thank you page household list

crossroads.net/app/live_stream/countdown_intro/countdownIntro.component.js, crossroads.net/app/live_stream/landing/landing.controller.js, crossroads.net/app/live_stream/services/stream-status.service.js
Countdown intro can now be specifically position by placing `<countdown-upcoming>&nbsp;</countdown-upcoming>` anywhere within the streamingLandingIntroUpcoming content block
=> US5547 - countdown intro refactor

CI/SQL/20161116_092500_US5285-create-printer-maps-table.sql, CI/SQL/20161116_092600_US5285-add-printer-map-id.sql, CI/SQL/20161116_094600_US5285-printer-maps-page.sql
US5285 - Adding printer mapping table, updating kiosk configs, and printer mapping page
=> Kiosk Printer Setup

CI/SQL/20161116_101224_US5735-add-batchid-to-payments.sql, CI/SQL/20161116_101224_US5735-add-payments-subpage-to-batch.sql
Add scripts for payments subpage on batch
=> US5735 Payment Subpage on Batches

crossroads.net/app/camps/application_page/product_summary/product_summary.controller.js
DE2239
* we were not being inclusive of todays date when filtering
=> Product summary page not respecting today!

CI/SQL/20161117_084100_DE2247-clean-up-allergy-types.sql, Gateway/MinistryPlatform.Translation/Models/MpAllergy.cs, Gateway/MinistryPlatform.Translation/Repositories/MedicalInformationRepository.cs, Gateway/crds-angular/MinistryPlatform.config, Gateway/crds-angular/Services/CampService.cs
Allergy types where being created everytime someone added allergies. They
were meant to be a lookup and not be created everytime.
=> DE2247 - Allergy Types

crossroads.net/app/camps/application_page/camps_payment/camps_payment.controller.js, crossroads.net/app/camps/application_page/camps_payment/camps_payment.html, crossroads.net/app/camps/application_page/product_summary/product_summary.controller.js, crossroads.net/app/camps/application_page/product_summary/product_summary.html, crossroads.net/spec/camps/application_page/product_summary/product_summary.component.spec.js, crossroads.net/styles/main.scss, crossroads.net/styles/pages/camps.scss
=> US5318 - Implement Payment in Application

crossroads.net/app/camps/application_page/camper_info/camper_info.controller.js, crossroads.net/app/camps/application_page/camper_info/camper_info.html, crossroads.net/app/camps/application_page/camper_info/camper_info_form.service.js
* Update camper info layout to match wireframes
* Completing camper info page navigates to emergency contacts
=> US5508 - Update camper info layout

crossroads.net/app/camps/application_page/camps_payment/camps_payment.controller.js
* update option on iframe-resizer to calculate max height
=> DE2264 Invalid iframe sizing

Gateway/crds-angular/Controllers/API/CampController.cs
=> DE2280 Emergency Contact Stopped working

crossroads.net/app/profile/giving/recurring/templates/recurring_giving_remove_modal.html
The dialog is access from the giving tab on My Profile page.
=> Add an ID to the remove button the confirm removal dialog.

crossroads.net/app/camps/application_page/camps_payment/camps_payment.controller.js
* update the widget url to not include the `payment` path
=> DE2318 Payment Widget Borked

Gateway/MinistryPlatform.Translation/Repositories/EventRepository.cs
fix the childcare group update job
=> DE2323-Get the contact_id for the event primary contact

crossroads.net/app/group_tool/group_detail/about/groupDetail.about.html, crossroads.net/app/mp_tools/add_event_tool/add_event/addEvent.controller.js, crossroads.net/app/mp_tools/add_event_tool/add_event/add_event.html
=> DE2320: this totally works locally. I hope it works on int this time.

CI/SQL/20161206_102700_DE2331-update-bumping-rules-subpage.sql
https://rally1.rallydev.com/#/27593764268d/detail/defect/78971627692
=> Fix Room Reservations Bumping Rules script.

crossroads.net/styles/pages/streaming.scss
Simplest PR ever. 
This update will fix styling issues related to US4496 on the /stream attendance tracker. See the following defect for more information. 
https://rally1.rallydev.com/#/66096127196d/detail/defect/79847906424
=> DE2374 - Attendance Tracker

CI/SQL/20161207_095200_US5828-SetupLexingtonLegacyGivingMetadata.sql
* [US5828 - Setup Lexington metatada for giving migration](https://rally1.rallydev.com/#/38108142417d/detail/userstory/77219191172)
* Data scripted per [sheet ](https://docs.google.com/spreadsheets/d/1TTvJM7-XyCLXj18ru9KbIQ8H1zhpEKj3YmEj6IbMPdo/edit?ts=58481241#gid=0)from Mike F.
=> US5828: Script Lexington metadata for giving migration

crossroads.net/app/live_stream/stream/stream.controller.js, crossroads.net/app/live_stream/stream/stream.html
Inline giving should be added to the stream page as a content block, as an iframe initially. (update using embed script will come later)
Create script for new content block.
=> DE2375 - implement iframe via content block

crossroads.net/core/core.controller.js
=> DE2395 - Handle the fact that give runs the core.controller twice

CI/SQL/20161206_090000_US5562-addSitesToMP.sql
SQL Script to Add CKY sites Andover, Georgetown, Richmond and Downtown to MinistryPlatform. The pastor's contact and dp_user record is created for the Georgetown and Richmond sites, and Brian Tome is used as the pastor for Downtown.
=> US5562 - Add CKY Sites to MP

crossroads.net/app/live_stream/stream/stream.controller.js
This PR will close the following two defects... 
* [DE2411](https://rally1.rallydev.com/#/66096127196d/detail/defect/80294345604)
* [DE2414](https://rally1.rallydev.com/#/66096127196d/detail/defect/80298823980)
=> DE2414 Inline Giving

crossroads.net/styles/modules/crds-modal.scss
This PR addresses a regression introduced via [DE2392](https://rally1.rallydev.com/#/66096127196d/detail/defect/80084197060).
=> DE2420 Modal Shift

crossroads.net/app/camps/camps_family/camp_household_members/camp_household_members.html
* Camp title was hard coded, changed to use the CampsService
=> DE2441 Incorrect Camp Title

crossroads.net/app/camps/dashboard/camps_dashboard.controller.js, crossroads.net/app/camps/dashboard/camps_dashboard.html, crossroads.net/spec/camps/dashboard/camp_dashboard.component.spec.js
* Please also look at [the cms pull
request](https://github.com/crdschurch/SS-CMS/pull/211)
=> DE2447 Message on my camps when there are none

crossroads.net/app/camps/application_page/medical_info/medical_info.component.js, crossroads.net/app/camps/camp.controller.js, crossroads.net/app/camps/camp.html, crossroads.net/app/camps/camps.resolves.js, crossroads.net/app/camps/camps.routes.js, crossroads.net/app/camps/camps.service.js
If the update flag is set to true then don't show the registration
closed screen.
Also minor eslint fixes
=> DE2454 Check $stateParams for update flag

CI/SQL/20161214_163900_US6000-ChildSearchApiStoredProcedure.sql
* [US6000 - Speed up phone number search](https://rally1.rallydev.com/#/27593764268d/detail/userstory/80079859348)
* Also review [PR 165](https://github.com/crdschurch/crds-signin-checkin/pull/165) in crds-signin-checkin
=> US6000: New stored proc for child signin search

CI/Reports/CRDSWeeklyGivingByProgram.rdl
Adjust the filter for congregation to include the selected accounting company
=> US5967: Add Accounting Company to Congregation filter

CI/Reports/CRDSWeeklyGivingByCongregation.rdl
Adjust the filter for congregation to include the selected accounting company
=> US5966 modify weekly giving by congregation report

crossroads.net/app/live_stream/stream/stream.controller.js, crossroads.net/app/live_stream/stream/stream.html, crossroads.net/core/core.js, crossroads.net/core/embed/embed.component.js, crossroads.net/core/embed/embed.controller.js, crossroads.net/core/embed/embed.html, crossroads.net/core/embed/index.js, crossroads.net/spec-es6/core/embed.controller.spec.js, crossroads.net/spec-es6/live_streaming/stream/stream.controller.spec.js
This PR refactors the current implementation of the embedded, inline-giving iframe into a new directive to resolve a race condition related to instantiating the resizer script against DOM elements populated by a content-block.
=> DE2449 Iframe Resizer Redux

Gateway/crds-angular.test/Helpers/Factories.cs, Gateway/crds-angular.test/Services/CampServiceTest.cs, Gateway/crds-angular/Services/CampService.cs, crossroads.net/spec-es6/mp_tools/add_event_tool/add_event/addEvent.controller.spec.js
hotfix/DE2502-invoice-showing-incorrectly
=> Hotfix - Summer Camp invoice amount

crossroads.net/app/live_stream/geolocation/geolocation.controller.js, crossroads.net/app/live_stream/geolocation/geolocation.html
Keep geolocation violator text from appearing prematurely on module.
=> DE2534 - Violator on roll call on stream

crossroads.net/styles/pages/streaming.scss
Fix overlapping articles in horizontal slider on iphone6.
=> DE2486 - Stream layout on iphone 6 broken

crossroads.net/app/live_stream/geolocation/geolocation.html
Hide violator text on iOS Safari by replacing ng-hide with ng-if.
=> DE2534 - Violator roll call showing on stream page

CI/SQL/20161227-114302_DE2549-AddForeignKeyFromRuleGendersToGenders.sql
Fixes subpage error and dropdowns.
=> DE2549 Added FK to Genders

crossroads.net/core/core.run.js, crossroads.net/core/login/login_form.html, crossroads.net/core/services/session_service.js, crossroads.net/spec-core/services/session.service.spec.js, crossroads.net/styles/pages/signin-register.scss
Part 2 (of 2) for Reactive SSO. This PR addresses it from the crds-angular repository. Part 1 was the crds-embed side (https://github.com/crdschurch/crds-embed/pull/225).
story: https://rally1.rallydev.com/#/41662702253d/detail/userstory/69982082372
=> US5414: Reactive SSO for Angular

CI/SQL/20162112_144800_US6025-call-number-persistence.sql
=> Call Number Persistence

crossroads.net/app/profile/profile.html
to make finding the control easier in selenium
=> Adding an ID to the More tab on the profile page

CI/SQL/20170104_1246000_US6195-add-default-guest-household.sql
SQL Script to Add Default Household
=> US6195 - Add Guest Children

CI/SQL/20170104_143209_US5624-DeclinedPaymentsView.sql
Creates a new view for Declined Payments
=> US6124 Declined Payments View

CI/SQL/20170106_132700_DE2585-update-api_crds_Child_Signin_Search.sql
Updated api_crds_Child_Signin_Search to not pull end dated group participants
=> DE2585 - Duplicated Group Participants

Gateway/MinistryPlatform.Translation/Repositories/InvoiceRepository.cs, Gateway/crds-angular.test/Services/PaymentServiceTest.cs, Gateway/crds-angular/Services/PaymentService.cs
Also, count the declines because they zero out.
=> US5814 use auth this time

Gateway/MinistryPlatform.Translation/Repositories/InvoiceRepository.cs, Gateway/crds-angular.test/Services/PaymentServiceTest.cs, Gateway/crds-angular/Services/PaymentService.cs
Reverts crdschurch/crds-angular#3406
=> Revert "US5814 use auth this time"

Gateway/MinistryPlatform.Translation/Repositories/Interfaces/IInvoiceRepository.cs, Gateway/MinistryPlatform.Translation/Repositories/InvoiceRepository.cs, Gateway/crds-angular.test/Services/PaymentServiceTest.cs, Gateway/crds-angular/MinistryPlatform.config, Gateway/crds-angular/Services/Interfaces/IPaymentService.cs, Gateway/crds-angular/Services/PaymentService.cs
Reverts crdschurch/crds-angular#3371
=> Revert "US5814 Determine correct invoice status and set it"

Gateway/MinistryPlatform.Translation/Repositories/Interfaces/IInvoiceRepository.cs, Gateway/MinistryPlatform.Translation/Repositories/InvoiceRepository.cs, Gateway/crds-angular.test/Services/PaymentServiceTest.cs, Gateway/crds-angular/MinistryPlatform.config, Gateway/crds-angular/Services/Interfaces/IPaymentService.cs, Gateway/crds-angular/Services/PaymentService.cs
Reverts crdschurch/crds-angular#3420
=> Revert "Revert "US5814 Determine correct invoice status and set it""

Gateway/MinistryPlatform.Translation/Repositories/InvoiceRepository.cs, Gateway/crds-angular.test/Services/PaymentServiceTest.cs, Gateway/crds-angular/Services/PaymentService.cs
Reverts crdschurch/crds-angular#3419
=> Revert "Revert "US5814 use auth this time""

CI/SQL/201601112017_092042_US6059-EnableHyperlinks.sql, crossroads.net/app/group_tool/group_detail/about/groupDetail.about.html
=> Feature release/feature/us6059 enable hyper links

CI/SQL/20170111_095759_DE2609-fix-ready-for-batch-view.sql
* modified the view clause to look at the Payment Date and not the batch date
=> fix view clause in batch view

CI/Reports/CRDS Large Donations.rdl, CI/Reports/CRDS New Givers.rdl
=> US6355: Order Congregation names alphabetically

CI/SQL/20170112_103709_DE2594-fix-medinfo-column-names.sql, Gateway/MinistryPlatform.Translation/Models/MpMedicalInformation.cs, Gateway/MinistryPlatform.Translation/Repositories/MedicalInformationRepository.cs
* scripted update to column names
* scripted update to pages
* updated rest calls
=> DE2594 Name columns correctly

Gateway/crds-angular.test/Services/CampServiceTest.cs, Gateway/crds-angular/Services/CampService.cs
* frontend was passing null values to backend
* filtered out all null values before saving to MP
=> DE2574 extra commas

CI/TestSQL/02.TestData/MP_TestPledgeCampaign.sql
Added automation pledge campaigns
=> add automation pledge campaigns

CI/Reports/CRDSChildcareSummary.rdl, CI/SQL/20170117_131509_DE2656-update-stored-proc-to-handle-nonfilter-filters.sql
filters are now columns :1st_place_medal:
=> Remove filter filters so report is not filtered

CI/Reports/CRDSChildcareSummary.rdl, CI/SQL/20170117_131509_DE2656-update-stored-proc-to-handle-nonfilter-filters.sql
Reverts crdschurch/crds-angular#3504
=> Revert "Revert "Remove filter filters so report is not filtered""

CI/Reports/CRDS Large Donations.rdl
In short, hard-coded "Not Site Specific" Congregation_ID for the IN (whatever Congregations) query when getting Program list.  
https://rally1.rallydev.com/#/74313728980d/detail/defect/87266978620
=> Adjust large donations report to include not site specific programs

CI/TestSQL/02.TestData/MidgarTrip.sql, CI/TestSQL/03.TestConfigData/GoMidgarParticipants.sql
Updated GoMidgarParticipants.sql and MidgarTrip.sql so that the trip should show up on int.
=> Updated scripts so that GO Midgar trip should show up on int

CI/TestSQL/02.TestData/MidgarTrip.sql, CI/TestSQL/03.TestConfigData/GoMidgarParticipants.sql
Fixed syntax errors. Select statements need to be in parens when being used to set the value of a variable.
=> Fixed syntax error(s)

CI/TestSQL/01.TestUsers/QATEST_TripFamily.sql, CI/TestSQL/03.TestConfigData/GoMidgarParticipants.sql, CI/TestSQL/03.TestConfigData/TifaLockhartDonations.sql
Standardized Cloud and Tifa's email addresses to be lowercase.
=> Clean up sql setup teardown

CI/TestSQL/02.TestData/MidgarTrip.sql, CI/TestSQL/03.TestConfigData/GoMidgarParticipants.sql
Added a fundraising goal to make it more realistic.
Changed Cloud's participation type to registered because the pages specifically look for this. (This is the change that gets his trip to show up)
=> Changed Cloud's participation type and added a fundraising goal.

CI/SQL/20170210_121800_US6613-Manage-Rooms-Proc.sql
=> US6613 - Manage Rooms Performance

crossroads.net/core/login/login_controller.js, crossroads.net/spec-core/login/login.controller.spec.js
Code change routes user to site root instead of to the profile view.  Inconsistent behavior was due to session_service logging out the user during the auth check occurring every 3 seconds.
=> DE2734 Resolve inconsistent sign-in behavior

crossroads.net/app/group_tool/group_search_results/groupSearchResults.controller.js, crossroads.net/app/group_tool/group_search_results/groupSearchResults.html, crossroads.net/es6.tests.conf.js, crossroads.net/spec-es6/group_tool/group_search_results/groupSearchResults.controller.spec.js
-Renamed initialFilters to currentFIlters
-Extracted functionailty that gathers currently selected filters into its own function to be reused elsewhere
=> Fixed filters being removed on research

Gateway/crds-angular/DataAccess/EzScanCheckScannerDao.cs
Invalid data conversion (Int16 should be Int32)
=> DE2780: Hotfix for checkscanner batches failing. 

Gateway/MinistryPlatform.Translation.Test/Services/ContactServiceTest.cs, Gateway/MinistryPlatform.Translation.Test/Services/MinistryPlatformRestServiceIntegrationTest.cs, Gateway/MinistryPlatform.Translation/MinistryPlatform.Translation.csproj, Gateway/MinistryPlatform.Translation/Models/MpContactHousehold.cs, Gateway/MinistryPlatform.Translation/Models/MpHouseholdMember.cs, Gateway/MinistryPlatform.Translation/Repositories/ContactRepository.cs, Gateway/crds-angular.test/Services/CampServiceTest.cs, Gateway/crds-angular/Services/CampService.cs, Gateway/crds-angular/Services/ChildcareService.cs
Changed translation layer to look at other members from the Contacts_Households table instead of Other_Households.
=> DE2723 Handle other households properly

Gateway/crds-angular/DataAccess/EzScanCheckScannerDao.cs, crossroads.net/app/group_tool/group_search_results/groupSearchResults.html
=> Hotfix to Release for Check Scanner Issues 

CI/SQL/20170217_091100_US6676-update-room-data-proc.sql
=> US6676 - Manage Room Performance

Gateway/MinistryPlatform.Translation.Test/Services/MinistryPlatformRestServiceIntegrationTest.cs, Gateway/MinistryPlatform.Translation/Models/Payments/MpInvoiceDetail.cs, Gateway/MinistryPlatform.Translation/Repositories/InvoiceRepository.cs
=> DE2786 Unable to pay deposit

Gateway/MinistryPlatform.Translation.Test/MinistryPlatform.Translation.Test.csproj, Gateway/MinistryPlatform.Translation.Test/Services/FormSubmissionRepositoryTest.cs, Gateway/MinistryPlatform.Translation.Test/Services/FormSubmissionServiceTest.cs, Gateway/MinistryPlatform.Translation/Models/MpFormResponse.cs, Gateway/MinistryPlatform.Translation/Repositories/FormSubmissionRepository.cs, Gateway/crds-angular/Services/CampService.cs
* update FormSubmisssionRepository to do the correct action based on the
data passed in.
* write tests to validate behavior
* update all places where FormSubmissionRepository method is called to
include EventID in the Object
=> DE2732 Serial Camper Syndrome

crossroads.net/app/formlyBuilder/formlyConfig/types/crdsInput.js, crossroads.net/app/go_volunteer/anywhereProfile/goVolunteerAnywhereProfile.component.js, crossroads.net/app/go_volunteer/anywhereProfile/goVolunteerAnywhereProfile.controller.js, crossroads.net/app/go_volunteer/anywhereProfile/goVolunteerAnywhereProfile.html, crossroads.net/app/go_volunteer/anywhereProfile/goVolunteerAnywhereProfileForm.service.js, crossroads.net/app/go_volunteer/anywhereProfile/index.js, crossroads.net/app/go_volunteer/formly_wrappers/bootstrap_row.html, crossroads.net/app/go_volunteer/goVolunteer.formly.js, crossroads.net/app/go_volunteer/goVolunteer.module.js, crossroads.net/app/go_volunteer/goVolunteer.routes.js, crossroads.net/app/go_volunteer/projectCard/goVolunteerProjectCard.component.js, crossroads.net/app/go_volunteer/projectCard/goVolunteerProjectCard.controller.js, crossroads.net/app/go_volunteer/projectCard/goVolunteerProjectCard.html, crossroads.net/app/go_volunteer/projectCard/index.js, crossroads.net/styles/pages/go-volunteer.scss
UI Implementation for GO Local Anywhere
Route: `/go-volunteer/anywhere/seattle/profile`
* Created component `go-volunteer-anywhere-profile`
* Created component `go-volunteer-project-card`
* Added ability to use a `placeholder` to the Formly crdsInput type
* Choosing "Yes" for service projects displays list of options
* Choosing "Other" serving options displays description input
=> US7024 - GO Local Anywhere Profile UI

CI/SQL/20170222_140900_DE2699-mitigate-duplicate-phone-num.sql
Changed sort order on households to retturn newest household
=> DE2699 - Mitigate Duplicate Household Phone Numbers

Gateway/crds-angular/Models/Crossroads/AddressDTO.cs, Gateway/crds-angular/Models/Finder/PinDto.cs, Gateway/crds-angular/Services/FinderService.cs
=> Revert "US7081 only calling geocode when needed"

Gateway/crds-angular/Models/Crossroads/AddressDTO.cs, Gateway/crds-angular/Models/Finder/PinDto.cs, Gateway/crds-angular/Services/FinderService.cs
Reverts crdschurch/crds-angular#3644
=> Revert "Revert "US7081 only calling geocode when needed""

crossroads.net/app/go_volunteer/anywhereProfile/goVolunteerAnywhereProfile.html, crossroads.net/core/templates/goCincinnati.html, crossroads.net/styles/modules/menu-icon.scss, crossroads.net/styles/pages/go-volunteer.scss
=> US7146 - Convert GO Local from dark to light background

CI/SQL/20170227_104300_US7057-Update-StatementEmailProc-To-Include-MoneyOrders.sql
=> US7057: Include money orders, DE2824 filter out guest giver, DE2808 get

CI/TestSQL/02.TestData/MP_TestPledgeCampaign.sql
When pledge campaign was being created, we were trying to assign it to the wrong program. Also increased campaign goals.
=> Added pledges for automation campaigns. Pointed at correct program.

crossroads.net/app/go_volunteer/page/anywhereProfile/goVolunteerAnywhereProfileForm.service.js
Fix typo in the word Aftercare
=> US7024 - Fix typo

CI/TestSQL/01.TestUsers/QATEST_GeorgeSmithFamily.sql, CI/TestSQL/01.TestUsers/QA_AUTO_MakeJamesMayKCAdmin.sql, CI/TestSQL/01.TestUsers/userList.csv
=> Check in test data

crossroads.net/app/go_volunteer/page/anywhereProfile/goVolunteerAnywhereProfile.html
* pulled in the newly named content block
* the new content block is already in all of the environments
=> US6788 Use new waiver content block

CI/SQL/20170310_084400_US6326-Alter-Manage-Rooms-Proc.sql
**Rally:** https://rally1.rallydev.com/#/27593764268d/detail/userstory/85657432116
**Build:** http://mp-ci.centralus.cloudapp.azure.com/viewType.html?buildTypeId=Code_Development_Crossroads_Feature&branch_Code_Development_Crossroads=feature%2FUS6326-FixCountOnAdventureClubSignedInCheckInOnManageRooms&tab=buildTypeStatusDiv
=> Fix up stored proc.

crossroads.net/app/go_volunteer/organizations/organizations.controller.js
This fixes both DE2929 and DE2930
=> fixed broken 'Other' flow

Gateway/crds-angular.test/Services/GoVolunteerServiceTest.cs, Gateway/crds-angular/Models/Crossroads/GoVolunteer/CincinnatiRegistration.cs, Gateway/crds-angular/Models/Crossroads/GoVolunteer/Registration.cs, Gateway/crds-angular/Services/GoVolunteerService.cs
We were depending on the fact that GroupConnectorID was set, when in reality, we set the object GroupConnector. I modified the code to search for the existence of the object and fall back to GroupConnectorID.
=> DE2930 group connector code broken

crossroads.net/app/camps/camps.routes.js
Added a route to catch `/camps/` and redirect to the content route
=> DE2983 Camp Slash issue

CI/SQL/20170313_163722_DE2950-update-connect-sp-filter-locations.sql
added WHERE Location_ID not in (4, 12)  -- 'Not Site Specific' and Anywhere
=> DE2950 filter out Anywhere from locations

CI/SQL/20170216_095900_US6612-Camp-registration-report.sql
If you are in multiple active grade groups you won't show up on the report
correctly.
=> DE2961 Fixed issue except one case

crossroads.net/app/mp_tools/add_event_tool/addEvent.service.js
Daylight Savings Time. Use moment local() instead
=> DE2968: Don't hardcode GMT offset because it's bad and breaks during

CI/SQL/20170314_161500_US7384-add-all-platform-users.sql
* Remove duplicate roles from dp_User_Roles
* Add new index on dp_User_Roles
* Add All Platform Users role to all users who are missing that role.
=> US7384: Add All Platform Users to users who are missing that role

CI/SQL/20170316_091301_DE2979-OnlyShowActiveChildren.sql
**Build:** http://mp-ci.centralus.cloudapp.azure.com/viewType.html?buildTypeId=Code_Development_Crossroads_Defect&branch_Code_Development_Crossroads=defect%2FDE2979-ShowActiveChildrenOnly&tab=buildTypeStatusDiv
**Rally:** https://rally1.rallydev.com/#/27593764268d/detail/defect/100121274272
=> DE2979 - Updated stored proc to show only active children.

CI/SQL/20170316_110700_DE2987-AddOxfordToSites.sql
new scheme: congregation -> location -> address
=> defect/de2987 - Change the site lookup for connect

CI/SQL/20170316_110900_DE2879-RemoveDuplicateAdvClubEventCancelingCode.sql
=> remove ac event cancelling/uncancelling code from proc

CI/SQL/20170316_125300_DE2986-KeepCapacityAllowSigninAndVolunteersWhenTogglingACRoom.sql
**BUILD:** http://mp-ci.centralus.cloudapp.azure.com/viewType.html?buildTypeId=Code_Development_Crossroads_Defect&branch_Code_Development_Crossroads=defect%2FDE2986-KeepCapacityAllowSigninAndVolunteersWhenTogglingACRoom&tab=buildTypeStatusDiv
**RALLY:** https://rally1.rallydev.com/#/27593764268d/detail/defect/100144869044
Only change was to lines 74-76
=> DE2986 - Fix Stored Proc to keep capacity, volunteer, and allow signin values when toggling a rooms AC

crossroads.net/app/go_volunteer/page/anywhereProfile/goVolunteerAnywhereProfileForm.service.js
* add the required property to the field
=> DE3011 Make Children Required

crossroads.net/app/go_volunteer/organizations/organizations.template.html, crossroads.net/app/go_volunteer/page/anywhereProfile/goVolunteerAnywhereProfile.html, crossroads.net/app/go_volunteer/page/equipment/goVolunteerEquipment.template.html, crossroads.net/app/go_volunteer/page/waiver/goVolunteerWaiver.template.html, crossroads.net/styles/helpers/utilities.scss, crossroads.net/styles/pages/go-volunteer.scss
=> US7428 - GO Local branding update

Gateway/crds-angular/crds-angular.csproj, Gateway/crds-angular/packages.config
This is in support of the mobile app hitting endpoints.
=> US6833: Update client API key package

CI/SQL/20170320_160200_US7358-CreateSPToAddAuditRecord.sql, CI/SQL/20170320_160300_US7358-FixNumbers.sql
=> US7358: Add audit log sproc; update household home_phone nand contacts

crossroads.net/app/go_volunteer/page/anywhereProfile/goVolunteerAnywhereProfileForm.service.js
This uses the CMS content block message for InvalidData
=> DE3002 - Add a Formly validation message for the Birthdate invalid format

crossroads.net/app/go_volunteer/formly_wrappers/email_change_warning.html, crossroads.net/app/go_volunteer/goVolunteer.formly.js, crossroads.net/app/go_volunteer/page/anywhereProfile/goVolunteerAnywhereProfileForm.service.js, crossroads.net/app/go_volunteer/page/profilePage/goVolunteerProfile.template.html, crossroads.net/styles/pages/go-volunteer.scss
The Crossroads and Anywhere profile forms display a warning that changing email will change the username.
The Archdiocese and Other organization profile forms do not display the email warning
=> DE2908 - GO Local email changes username warning

CI/SQL/20170324_084700_US503-participant-status-types.sql
Script to update participant status types
=> US503 - Store Turned Away Kid Data

Gateway/crds-angular/Models/Crossroads/GoVolunteer/Registrant.cs, crossroads.net/app/go_volunteer/page/anywhereProfile/goVolunteerAnywhereProfileForm.service.js, crossroads.net/app/go_volunteer/page/profilePage/goVolunteerProfile.component.js, crossroads.net/app/go_volunteer/page/profilePage/goVolunteerProfile.template.html
* Validate that mobile form on profiles are of format ###-###-####
* Phone number field placeholder will be "###-###-####"
* Add the “required” class to input fields on the Crossroads profile form so that the label includes the red required asterix
=> US7413 - Go Local profile forms use ###-###-#### phone validation

Gateway/crds-angular.test/crds-angular.test.csproj, Gateway/crds-angular.test/packages.config, Gateway/crds-angular/crds-angular.csproj, Gateway/crds-angular/packages.config
* Latest update is able to better determine client origin/hostname
=> US6833: Update to latest ClientApiKeys

crossroads.net/app/go_volunteer/page/anywhereProfileConfirm/goVolunteerAnywhereProfileConfirm.html
=> DE3008 Anywhere profile confirmation logout

CI/SQL/20170327_094800_DE3047-FixToReturnHouseholdID.sql
**Build:** http://mp-ci.centralus.cloudapp.azure.com/viewType.html?buildTypeId=Code_Development_Crossroads_Defect&branch_Code_Development_Crossroads=defect%2FDE3047-FixToShowIfGuestOrNotOnManageChildrenScreen&tab=buildTypeStatusDiv
**Rally:** https://rally1.rallydev.com/#/27593764268d/detail/defect/103192934652
=> Update Manage Children Page to return Household ID

crossroads.net/app/go_volunteer/formly_wrappers/email_change_warning.html, crossroads.net/app/go_volunteer/page/anywhereProfile/goVolunteerAnywhereProfileForm.service.js, crossroads.net/styles/pages/go-volunteer.scss
Email validation formatting is fixed:
Email address is validated:
=> DE3042 - GO Local Anywhere email field allows bad email

crossroads.net/app/go_volunteer/page/spouseName/goVolunteerSpouseName.component.js, crossroads.net/app/go_volunteer/page/spouseName/goVolunteerSpouseName.template.html, crossroads.net/styles/pages/go-volunteer.scss
Add asterisk to required fields
=> DE3077 Fix Spouse Phone Number

CI/TestSQL/01.TestUsers/QATEST_RichardTremplayFamily.sql, CI/TestSQL/01.TestUsers/QA_AUTO_CreateFamily.sql
Statement_Type_ID = 2 for family statements
=> Gave both family members family statement types

Gateway/crds-angular.test/Services/GoVolunteerServiceTest.cs, Gateway/crds-angular/Controllers/API/GoVolunteerController.cs, Gateway/crds-angular/Models/Crossroads/GoVolunteer/DashboardDatum.cs, Gateway/crds-angular/Services/GoVolunteerService.cs
Protected export from unauthorized users
=> DE3137 Corrected Export headers

CI/DatabaseRestoreFromBlob.ps1, CI/MPDemoDatabaseRestore.ps1, CI/MPIntDatabaseRestore.ps1, CI/MPTestDatabaseRestore.ps1
Commit of updated powershell scripts
=> Fix Builder Server DB Restore Scripts

CI/TestSQL/01.TestUsers/QATEST_GeorgeSmithFamily.sql, CI/TestSQL/01.TestUsers/userList.csv
I need a child to be 2 years or younger, to test signing into adventure
club.
=> Add a child into george smith's hh for TC3620

crossroads.net/app/go_volunteer/page/anywhereProfile/goVolunteerAnywhereProfileForm.service.js
convert to string and exclude time to avoid timezone/DST issues
=> DE2992: birthdate fix for Go Anywhere

Gateway/MinistryPlatform.Translation/Repositories/GroupParticipantRepository.cs, crossroads.net/app/my_serve/my_serve.routes.js, crossroads.net/app/my_serve/myserve.controller.js
backend to send minimum number of weeks until we find an opportunity (up
to 6). Also fix front end filter date range display
=> DE3239: SU2S Front end back to asking for default (0) on init. Change

crossroads.net/app/profile/giving/commitment/commitment_list.directive.js, crossroads.net/app/profile/giving/commitment/templates/commitment_list.html, crossroads.net/app/profile/giving/profileGiving.html
* Move the Commitments section to the top
* Change the progress bar text to bold white
* Display the amount remaining for each campaign (hide for smaller screens where it doesn't fit)
* Make card width consistent (so multiple pledges are the same width)
=> US7769: Updates for the Profile | Giving page

Gateway/MinistryPlatform.Translation/Models/MpHousehold.cs, Gateway/MinistryPlatform.Translation/Repositories/ContactRepository.cs, Gateway/MinistryPlatform.Translation/Repositories/Interfaces/IContactRepository.cs, Gateway/crds-angular.test/Services/PersonServiceTest.cs, Gateway/crds-angular.test/Services/StaffContactServiceTest.cs, Gateway/crds-angular/Models/Crossroads/PrimaryContactDto.cs, Gateway/crds-angular/Services/GroupLeaderService.cs, Gateway/crds-angular/Services/PersonService.cs, Gateway/crds-angular/Services/StaffContactService.cs
Added new method just to update congregation on household - call in `SetProfile` method because the `UpdateContact()` method does not save household data unless there is an address.
=> US7362 -leader application

CI/SQL/20170419_061700_US7920-add-guest-flag-column.sql
=> US7920 - Add Guest Flag Column

CI/Reports/CRDS ContributionStatement.rdl
=> DE3313-DonationsOutOfOrder

CI/Reports/CRDS Checkin Guest Family.rdl, CI/SQL/20170419_121700_US7409-create-guest-report.sql
Good stuff happens after you read the AC more closely
Build: http://mp-ci.centralus.cloudapp.azure.com/viewLog.html?buildId=21051&tab=buildResultsDiv&buildTypeId=Code_Development_Crossroads_Feature
=> US7409 - Create Guest Report

CI/SQL/20170420_150000_US7860-GetManageChildrenData.sql
**Rally:** https://rally1.rallydev.com/#/27593764268d/detail/userstory/108692948104
**Build:** http://mp-ci.centralus.cloudapp.azure.com/viewType.html?buildTypeId=Code_Development_Crossroads_Feature&branch_Code_Development_Crossroads=feature%2FUS7860-ManageChildrenOrderByKCSort&tab=buildTypeStatusDiv
=> Update stored proc to return KC Sort Order.

Gateway/MinistryPlatform.Translation.Test/Services/MinistryPlatformRestServiceIntegrationTest.cs, Gateway/MinistryPlatform.Translation/Models/MpHousehold.cs, Gateway/MinistryPlatform.Translation/Models/MpParticipant.cs, Gateway/MinistryPlatform.Translation/Repositories/ParticipantRepository.cs, Gateway/crds-angular.test/Services/GroupLeaderServiceTest.cs, Gateway/crds-angular.test/controllers/GroupLeaderControllerTest.cs, Gateway/crds-angular/Controllers/API/GroupLeaderController.cs, Gateway/crds-angular/MinistryPlatform.config, Gateway/crds-angular/Services/GroupLeaderService.cs, Gateway/crds-angular/Services/Interfaces/IGroupLeaderService.cs
* added new method to set applicant as applied
* removed some un-needed attributes from MPHousehold
* updated config to included Applied GroupStatusId
* Tests!
=> US7389 Group Leader Confirmation

crossroads.net/package.json
* version 2.6.0 breaks our build server's spirit
=> rollback and lockdown jasmine

Gateway/crds-angular.test/Services/GoVolunteerServiceTest.cs, Gateway/crds-angular/MinistryPlatform.config, Gateway/crds-angular/Services/GoVolunteerService.cs, crossroads.net/package.json
Removed spouse birthdate from email as well
=> DE3358 fixed Spouse Go Local Email

CI/Reports/CRDS Checkin New Family.rdl, CI/SQL/20170427_135900_US8401-update-new-family-report-proc.sql
=> US8041 - Add Address to New Family Report

CI/Reports/CRDSChildcareSummary.rdl, CI/SQL/20170117_131509_DE2656-update-stored-proc-to-handle-nonfilter-filters.sql
This code has already been reviewed and accepted. Will need to be merged and deployed when the checkin/signin system is deployed
=> US6234 Childcare Summary Report

CI/SQL/20170502_080800_US5898-update-mailchimp-segments.sql, CI/SQL/20170502_082200_US5898-update-mailchimp-segments.sql
=> US5898 - Update Mailchimp Segments

CI/SQL/20170501_110100_DE3447-Include0PercentPledges.sql
=> DE3447: Left join on pledges to dd instead of inner join to include

CI/SQL/20170505_0808000_US7888-create-capacity-proc.sql
=> US7888 - Capacity App Data

CI/SQL/20170505_0808000_US7888-create-capacity-proc.sql
Updated for null error
Build:
http://mp-ci.centralus.cloudapp.azure.com/viewLog.html?buildId=22331&tab=buildResultsDiv&buildTypeId=Code_Development_Crossroads_Feature
=> US7888 - Create Capacity Proc

CI/Reports/CRDSChildcareDetail.rdl
**Rally:** https://rally1.rallydev.com/#/27593764268d/detail/defect/115145327336
**Build:** http://mp-ci.centralus.cloudapp.azure.com/viewType.html?buildTypeId=Code_Development_Crossroads_Defect&branch_Code_Development_Crossroads=defect%2FDE3480-FixChildcareDetailsReport&tab=buildTypeStatusDiv
=> DE3480 - Fix the algorithms for RSVPOnline and RSVPOverride.

crossroads.net/app/live_stream/landing/landing.html, crossroads.net/styles/pages/streaming.scss
Update the /live page to include the new promo for Connect
Create new region of page for promo to live below the feature and above the series info
Include graphics & copy provided by Adam George
Copy should be driven by content blocks
=> US8190 - Connect Promo

CI/SQL/20170505_132744_US8129-update_feedback_redflag_views.sql
update contacts feedback and redflag views
=> US8129-update_views

crossroads.net/app/live_stream/services/reminder.service.js, crossroads.net/app/live_stream/stream/stream.controller.js
Apply crds-legacy-styles to modals
=> DE3517 Modal Styles

crossroads.net/package.json
Bump version of crds-shared-header to support request from automation team.
=> USXXXX Automation

CI/SQL/20170524_133600_US8303-add-invoice-number-to-detail.sql
Script to update Selected Record Expression
=> US8303 - Add Invoice Number to Invoice Detail

crossroads.net/core/ang.js, crossroads.net/core/app.core.module.js, crossroads.net/core/login/login_page.html, crossroads.net/package.json
* shim to handle svgs correctly
=> DE3508 Group Leader app

CI/SQL/20170524_153900_US8344-create-view-on-product-detail.sql
=> US8344 - Create View on Product Detail

CI/SQL/20170524_133000_US6010-update-report_crds_giving_by_site-UseCongregationID-from-dd-for-softcredit.sql
congregation in Giving By Site report
=> US6010: Use Congregation on DD instead of looking up soft credit donor

CI/SQL/20170523_102900_US8298-add-generic-invoice-message-template.sql, CI/SQL/20170523_111000_US8298-add-invoice-detail-email-process.sql
Updated the from contact to be accounts@crossroads.net
=> US8298 - Send Invoice Email

crossroads.net/app/group_tool/auth_modal/authModal.controller.js, crossroads.net/app/group_tool/group_search_results/groupSearchResults.html
Wrap second modal call in a 100 millisecond timeout
=> DE3543 Auth Modal Timeout

crossroads.net/package.json
Update dependency to latest version
=> US8469 CRDS Styles

CI/Reports/CRDSChildcareDetail.rdl, CI/SQL/20170526_085900_DE3535-refactor-childcare-detail.proc.sql
=> DE3535 - Childcare Detail Report Incorrect

CI/SQL/20170530_084900_DE3538-update-childcare-summary-proc.sql
=> DE3538 - Childcare summary not displaying correct info

CI/SQL/20170530_084900_DE3538-update-childcare-summary-proc.sql
=> DE3538 - Childcare Summary Report Fix

crossroads.net/app/invoices/invoice.controller.js, crossroads.net/app/invoices/invoice.html
**Rally:** https://rally1.rallydev.com/#/27593764268d/detail/userstory/121039123336
**Build:** http://mp-ci.centralus.cloudapp.azure.com/viewType.html?buildTypeId=MicroClients_Development_BuildAndTest_CrdsAngular&branch_MicroClients_Development_BuildAndTest=feature%2FUS8487-InvoiceAlreadyPaid&tab=buildTypeStatusDiv
=> Show that invoice is payed in full if nothing left to pay.

crossroads.net/app/events/atriumEvents.directive.js, crossroads.net/core/core.controller.js
Cleanup undefined method error in core.controller.js
=> DEXXXX Render Legacy Styles Error

crossroads.net/app/invoices/invoice-confirmation-redirecting.html, crossroads.net/app/invoices/invoices.routes.js
=> US3612: invoice redirection fix, wait for route to resolve

CI/SQL/20170602_103901_US8458-InvoiceConfirmationPaymentEmail.sql
=> fix email template

CI/Reports/CRDS ContributionStatement.rdl, CI/SQL/20170602_162044_US7183-filter-by-selected.sql, CI/SQL/20170605_133333_US7183-add-selection-report.sql
in selected and update to SQL to filter by selected's household (so we
work for selected co-givers)
=> US7183: contributions statements for selected donors. Add report to pass

crossroads.net/app/live_stream/stream/stream.controller.js, crossroads.net/core/services/CMS.service.js, crossroads.net/spec-es6/core/CMS.service.spec.js, crossroads.net/spec-es6/live_streaming/stream/stream.controller.spec.js
Please don't merge until corresponding CMS PR is merged.
=> DE3611 - show features in CMS defined order

crossroads.net/app/invoices/invoice-confirmation.html, crossroads.net/app/invoices/invoice.html
Added IDs to all controls on the invoice pages, except for the controls in
embed.
=> Added IDs to the controls on the invoice pages

crossroads.net/app/live_stream/content_card/contentCard.html, crossroads.net/package.json, crossroads.net/styles/pages/streaming.scss
Update linkedContent directive and add styles to support linked content in CMS. 
Related to crdschurch/crds-styles#130
=> DE3537 link card headings

crossroads.net/package.json
=> US8656 - CRDS Styles Version

Gateway/crds-angular/Services/EventService.cs
* Remove "Hidden" from filter conditions
=> DE3625 - Event reminder emails are sometimes missing room reservations

CI/Reports/CRDS Checkin Turned Away.rdl, CI/SQL/20170615_134300_US8614-create-turned-away-proc.sql, CI/SQL/20170615_135500_US8614-add-turned-away-report.sql
Commit of report and report procs
=> US8614 - Turned Away Report

CI/Reports/CRDS ContributionStatement.rdl
Adjusted the layout for year end paper statements
=> US7181 - Paper statements report layout

crossroads.net/app/media/directives/youTubePlayer.directive.js
to deploy to int to test. Good times
=> DE3704: checkin in internet suggested fix. worked before locally so have

crossroads.net/core/templates/footer.html
Add selector to footer element.
Related to crdschurch/crds-maestro#162
=> DE3751 Footer Styles

CI/SQL/20170622_170000_DE3721-new-givers-reportSP.sql
* Don't require an Address record (use LEFT JOIN instead of INNER JOIN)
* End Date should be inclusive (i.e., end at yyyy-mm-dd 23:59:59 instead of yyyy-mm-dd 00:00:00)
=> DE3721 - New Giver report is missing some donors

CI/SQL/20170628_144800_US8871-update-sp-report_CRDS_New_Givers-only-care-about-donation-cong-not-donor.sql
=> US8871: Don't check donor congregation. We only care about the donation

crossroads.net/app/index.html, crossroads.net/app/routes.content.js
Strip HTML, add spaces, take only the first sentence, truncate to <= 140 chars
=> DE3791: Better Meta Description

Gateway/crds-angular/MinistryPlatform.config, Gateway/crds-angular/Services/GroupToolService.cs
=> US8239-contact-group-leader

crossroads.net/app/index.html, crossroads.net/core/core.run.js, crossroads.net/gulpfile.js
Update shared header to 0.4.1 and account for IE 10/11 fixes.
Corresponds to crdschurch/crds-maestro#175.
=> US8908 - Update Shared Header Reference

Gateway/MinistryPlatform.Translation/Repositories/GroupRepository.cs, Gateway/crds-angular.test/Services/GroupServiceTest.cs, Gateway/crds-angular/Services/GroupService.cs
Updated the code to filter out past events
=> DE2903-filter-out-past-events-for-group-sign-ups

crossroads.net/app/common/profile/picture/profilePicture.controller.js, crossroads.net/app/common/profile/picture/profilePicture.html
* Fix angular markup to watch for image changes
* Broadcast a global JS event to notify the shared header (to be used in the future)
=> DE1447 - Refresh profile image after change

CI/Reports/CRDS ContributionStatement.rdl
* Modify page header to show "Page x of x" per stakeholder feedback
=> US7182 - Paper statements page break logic

CI/Reports/CRDS Checkin Turned Away Summary.rdl, CI/SQL/20170622_104000_US8800-turned-away-summary-proc.sql
Rewrote proc and updated report
=> US8800 - Turned Away Summary Report

crossroads.net/app/trips/signup/tripsSignup.controller.js, crossroads.net/app/trips/travelInformation/index.js, crossroads.net/app/trips/travelInformation/travelInformation.component.js, crossroads.net/app/trips/travelInformation/travelInformation.controller.js, crossroads.net/app/trips/travelInformation/travelInformation.html, crossroads.net/app/trips/trips.module.js, crossroads.net/app/trips/trips.routes.js
http://localhost:3000/trips/mytrips/update
Mocked or stubbed most of the controller functions and frequent flyer data
=> US8988 - Travel Information Update UI

CI/SQL/20170717_114300_US8759-auto-complete-expired-room-reservations.sql, CI/SQL/20170717_115600_US8759-update-incomplete-tasks-view.sql
* Update page view to hide expired room reservations
* Add nightly process to auto-complete expired room reservations
=> US8759 - Remove expired room reservations from Incomplete Tasks

CI/Reports/CRDSChildcareSummary.rdl
=> US8753 - Update Childcare Summary

crossroads.net/core/core.controller.js
This PR fixes a race condition related to styles being removed before state change lifecycle hook is complete.
=> DE3879 Styles Removed on State Change Start

crossroads.net/styles/pages/streaming.scss
Remove scrollbars from modal on /live
=> DE3807 Modal on Live

crossroads.net/app/trips/travelInformation/travelInformation.html
* added checkbox for verification
also please review [this CMS pull request](https://github.com/crdschurch/SS-CMS/pull/383)
=> US8162 update travel info

crossroads.net/package-lock.json, crossroads.net/package.json
=> US9171 - NPM Package

crossroads.net/core/core.controller.js
=> DE3879 Styles Remove on State Change

crossroads.net/app/routes.content.js, crossroads.net/app/routes.js, crossroads.net/core/core.controller.js
3rd time's the charm. This PR is identical to crdschurch/crds-angular#4252 but targets the `development` branch.
=> DE3879 Styles Removed on State Change

crossroads.net/core/core.run.js, crossroads.net/package-lock.json
Steps to recreate:
On mobile, sign in, 
open the profile
navigate to any of the menu items under profile
the first time - profile menu collapses, but when you open any menu item (same or different) again profile stays expended.
There is video recording of all those steps on slack on Ample channel sent by Jason on 7/17/2017
and you can access this video here:
https://drive.google.com/drive/u/0/folders/0B0E7EftymfMHN3EwU3hYcjVkWnc?ths=true (the name of the video profile expanded)
  
=> DE3903 - Profile Menu

crossroads.net/app/trips/mytrips/mytrips.html
=> US9308 - Change update travel information link to a button

crossroads.net/core/core.run.js
Remove modal overlay on stateChangeSuccess unless it should explicitly be there.
=> DE4013 Modal Overlay

CI/SQL/20170810_123003_DE4055-added-missing-single-quotes-on-undivided-page.sql
All I needed to update was the extra single quotes in the STUFF function by XML but decided to add the expression and filter clause to keep all environments consistent because I noticed demo wasn't the same.
=> DE4055 Undivided Page View Not Working - needed single quotes

crossroads.net/app/index.html
Update crds-shared-header to latest version. 
Related to Related to crdschurch/crds-maestro#212 and crdschurch/crds-shared-header#67
=> DE4071 IOS Arrows

crossroads.net/app/waivers/signWaiver/sign-waiver.html
* Label changes from "Send Email" to "Next"
* Loading state changes to “Submitting…”
=> US9509 - Change waiver button "Next" 

crossroads.net/app/trips/mytrips/mytripCard.html
* "Sign Documents" is changed to "Sign These Documents"
* "Sign the I Promise" is changed to "I Promise"
=> US9508 - Change sign documents text and button label

Gateway/crds-angular/Services/GroupToolService.cs
Reverts crdschurch/crds-angular#4331
=> Revert "DE4135 - don't send the default email when 'trying a group'"

crossroads.net/app/trips/trippromise/tripPromise.controller.js, crossroads.net/app/trips/trippromise/tripPromise.html
Also, put the required asterisk in the right place so it doesn't wrap when there is an error.
=> DE4087 Inject Validation

CI/TestSQL/01.TestUsers/QA_AUTO_FinderGroups.sql, CI/TestSQL/01.TestUsers/userList.csv
I added a SQL script to create a finder group for use in automated tests.
=> Added finder groups data to scripted data.

CI/SQL/20170906_090000_DE4213-host-denial-email-merge-data-failure.sql
https://rally1.rallydev.com/#/66097202244d/detail/defect/149384508224
=> Added a script to correct the body of the host denial email

Gateway/Crossroads.ScheduledDataUpdate/Program.cs
=> Remove AWs delete before AWS upload in AWS refresh task

crossroads.net/app/common/services/analytics.service.js, crossroads.net/app/live_stream/videojs_player/videojsPlayer.controller.js, crossroads.net/app/media/directives/youTubePlayer.directive.js, crossroads.net/app/media/singleMedia.controller.js, crossroads.net/spec/common/analytics.service.spec.js
Moved all analytics calls in crds-angular into analytics service and added test coverage.
=> consolidated calls into analytics service

CI/SQL/2017_09_14_DE4283-available-online-flag-not-set.sql
Added line 67 to existing stored proc - it was missing field: 
`(IIF(G.Available_Online IS NULL, 0, G.Available_Online)) AS groupavailableonline`
=> Add new line to set Available_Online flag

Gateway/crds-angular/Services/FinderService.cs
=> DE4287: Fix null reference exception

Gateway/crds-angular/Services/PersonService.cs
So EST the offset is either -5:00 or -4:00 because of silly reasons. This code gets the correct one to send to astronomer.
=> Get the correct offset string for EST

Gateway/crds-angular/Services/PersonService.cs
After reading the documentation, [Mixpanel wants you to send dates in UTC and they will convert it for you. ](https://mixpanel.com/help/questions/articles/what-timezone-does-mixpanel-use-how-can-i-change-it)So me converting to EST made them convert it to a wrong date again.
=> Mixpanel expects to be sent dates in UTC time.

crossroads.net/app/live_stream/services/streamspot.service.js, crossroads.net/spec-es6/live_streaming/services/streamspot.service.spec.js
Use new StreamSpot endpoint that includes the in-progress event (if any)
=> DE4355 - Fix for failure to detect in-progress broadcast

CI/TestSQL/01.TestUsers/KathrynCradduckTest.sql, CI/TestSQL/01.TestUsers/QATEST_ACHGiveChangePaymentsAccount.sql, CI/TestSQL/01.TestUsers/QATEST_ACHGiveManualAccount.sql, CI/TestSQL/01.TestUsers/QATEST_ACHUserAccount.sql, CI/TestSQL/01.TestUsers/QATEST_AutomationTripFamily.sql, CI/TestSQL/01.TestUsers/QATEST_CCGiveManualAccount.sql, CI/TestSQL/01.TestUsers/QATEST_MPCRDS+20Contact.sql, CI/TestSQL/01.TestUsers/QATEST_RichTheilTest.sql, CI/TestSQL/01.TestUsers/QATEST_TripFamily.sql, CI/TestSQL/01.TestUsers/QA_AUTO_CreateExistingDonors.sql, CI/TestSQL/01.TestUsers/QA_AUTO_CreateFamily.sql
Added 'Scripted Donor' to the donor notes for all scripted users given processor ids
=> Enhancement to scripted donor accounts to help automation tests

CI/TestSQL/01.TestUsers/QATEST_GeorgeSmithFamily.sql
Manage families breaks if you try to edit a family without a source. Household source is now Kids Club Registration
=> Added a source to George Smith's household

CI/TestSQL/01.TestUsers/QA_AUTO_MakeJamesMayKCAdmin.sql
Gave admin permission to edit contacts (needed for creating/adding new family members)
=> SQL update to fix Checkin admin permissions

crossroads.net/package.json
Related to crdschurch/crds-maestro#244
=> US10041 Update Shared Header

CI/Reports/CRDS Team Leader 90 Day Inactive.rdl, CI/SQL/20171004_131800_US10063-inactive-team-member-proc.sql, CI/SQL/20171005_081400_US100063-add-inactive-team-member-report.sql
=> US10063 - Inactive serve team member report

CI/SQL/20171004_131800_US10063-inactive-team-member-proc.sql
Fixed filtering on end-dated participants
=> US10063 - Team Leader 90 Day Report

crossroads.net/app/index.html
=> US9041 Update crds-shared-header

CI/Reports/CRDS Team Leader 90 Day Inactive.rdl, CI/SQL/20171004_131800_US10063-inactive-team-member-proc.sql
Updated proc and report to use event date instead of response date
=> US10063 - Update Team Leader 90 Day

CI/ProdSQL/US10048-UpdatePreferredServingTimeForSU2SMembers.sql
**Rally:** https://rally1.rallydev.com/#/27593764268d/detail/userstory/158118506352
**Build:** http://mp-ci.centralus.cloudapp.azure.com/viewType.html?buildTypeId=MicroClients_Development_BuildAndTest_CrdsAngular&branch_MicroClients_Development_BuildAndTest=feature%2FUS10048-UpdateSU2SMembersPreferredServingTime&tab=buildTypeStatusDiv
=> Add script to updated SU2S members who are active and don't have a preferred serving time

crossroads.net/app/my_serve/serve_team_message/serveTeamMessage.html
=> DE4489 - Cancel button

CI/TestSQL/01.TestUsers/addUsersToMap.ps1
Script to add users to map given file of email-password combos and file of email-address combos.
Functionality should be the same as createMapUsers except this doesn't create a new user account.
=> Feature/us10270-Henney Add user to map script 

crossroads.net/app/index.html
Update shared header version number.
=> US10400 - Shared header

crossroads.net/app/index.html
=> US10400 Shared Header

CI/SQL/20171024_160842_US10189-CalculateResults.sql
Look at category weight start and end dates
=> use start and end date for catagory weights

crossroads.net/app/live_stream/stream/stream.html
Update the crossroads church logo on /live/stream
=> US10616 - Live Stream Logo

CI/TestSQL/01.TestUsers/addUsersToMap.ps1
Updated addUsersToMap to make it easier to run in TeamCity
=> feature/US10269 - addUsersToMap script improvement

CI/ProdSQL/US10333-UpdatePreferredServingTimeToEventTypeForSU2S.sql
**Rally:** https://rally1.rallydev.com/#/27593764268d/detail/userstory/165344217072
**Build:** http://mp-ci.centralus.cloudapp.azure.com/viewType.html?buildTypeId=MicroClients_Development_BuildAndTest_CrdsAngular&branch_MicroClients_Development_BuildAndTest=feature%2FUS10333-UpdatePreferredServingTimeToPreferredEventType&tab=buildTypeStatusDiv
=> Sql Script to update group participant table with new column and data for preferred serving event type

CI/TestSQL/01.TestUsers/addUsersToMap.ps1
Made map user list a parameter instead of hard coded
=> feature/US10785 - Test data teardown/reload script improvements

CI/TestSQL/01.TestUsers/addUsersToMap.ps1
=> feature/us10785 - Load map user script fix

crossroads.net/styles/main.scss
Make full size background images absolute when header is present
=> DE4656 - Shared Header Sticky Background

crossroads.net/app/index.html
=> US6971 - Current Series

crossroads.net/package-lock.json, crossroads.net/package.json
Bump crds-styles to 1.2.0
---
Related PRs...
crdschurch/crds-maestro#305
crdschurch/crds-styleguide#258
=> US10830 crds-styles

CI/TestSQL_TearDown/RemoveTestUsers.ps1
Added ability to pass in a userList to delete users from. Default is still userList.
=> feature/us10785 - Can now give a user list to the user teardown script

crossroads.net/core/login/login_page.html, crossroads.net/core/register/register_page.html, crossroads.net/styles/main.scss
Refactor markup and add styles to create a full height background image that scrolls when content overflows.
=> DE4683 - Full height bg img

crossroads.net/app/index.html
Fixes an issue with inconsistent data coming from /api/series endpoint in DEMO
=> [hotfix] Bump to latest version of shared header

crossroads.net/app/index.html
Bump crds-shared-header to latest version
=> DE4706 Current Series

crossroads.net/core/passwordField/passwordField.html, crossroads.net/styles/main.scss
Fix validation style on password field.
The original PR was prematurely merged. This corresponds with crdschurch/crds-maestro#316
=> US10844 - Update password field

crossroads.net/package.json
=> US10937 Release NPM Package

crossroads.net/core/register/register_page.html
* we don't want to go to the next steps page after registering
=> remove callback from register

crossroads.net/core/login/login_controller.js, crossroads.net/core/register/register.controller.js
Touch all fields in /signin and /register when submitting without entering data.
=> US10663 - Signin Validation

crossroads.net/app/index.html
=> DE4710 Expanded shared header covers part of the logo

crossroads.net/app/index.html
Bump version of shared header.
=> DE4729 Mobile Automation IDs

crossroads.net/package.json
Bump styles version to dev.
crdschurch/crds-maestro#358
=> US10903 - DDK buttons

crossroads.net/app/routes.content.js
Also a Maestro request for this:  https://github.com/crdschurch/crds-maestro/pull/357
=> US11197 get rid of resolve param

Gateway/MinistryPlatform.Translation/Repositories/InvoiceRepository.cs, Gateway/crds-angular.test/Services/CampServiceTest.cs, Gateway/crds-angular/Services/CampService.cs
=> Do not throw error when invoice searching fails!

CI/Reports/CRDS_Camp_Registration.rdl
The Column existed, but we never populated it with the data
=> Added data to column

crossroads.net/package-lock.json, crossroads.net/package.json
=> US11430 Styles

CI/SQL/20180111_102605_US11698-student-ministry-roster-report.sql
**Rally:** https://rally1.rallydev.com/#/27593764268d/detail/userstory/188204638504
=> Update proc for KC room roster to work for Student Ministry as well.

crossroads.net/app/index.html
=> US11807 - Shared Header User Menu

Gateway/MinistryPlatform.Translation/Repositories/InvoiceRepository.cs, crossroads.net/app/invoices/invoice.html
Adding recipient's name to payment widget
please pull this branch and test locally, as I have yet to set up my local env :/
=> ajcolub/US11841 - one line to add recipient name to payment wigdet

Gateway/MinistryPlatform.Translation/Repositories/InvoiceRepository.cs
=> Revert Changes for US11841(Add Invoice Recipient to Payment Widget)

crossroads.net/core/app.core.module.js, crossroads.net/package-lock.json
Add timeout to the toast so it goes away.
=> DE4949 - Forever toast

crossroads.net/styles/legacy.scss
Change opacity for modal backdrops on legacy styles
=> US10234 - Watch Trailer Button on Live

Gateway/MinistryPlatform.Translation.Test/Services/FormSubmissionRepositoryTest.cs, Gateway/MinistryPlatform.Translation.Test/Services/FormSubmissionServiceTest.cs, Gateway/MinistryPlatform.Translation/Repositories/FormSubmissionRepository.cs, Gateway/MinistryPlatform.Translation/Repositories/TripRepository.cs, Gateway/crds-angular/Controllers/API/DonationController.cs, Gateway/crds-angular/Controllers/API/TripApplicationController.cs, Gateway/crds-angular/Services/TripService.cs
Adding logging for trips processing.  Helpdesk tickets are increasingly difficult to troubleshoot and we are hoping that the additional logging will enable su to track down and correct all trips issues.
=> Hot fix/us12181 logging for trips

Gateway/MinistryPlatform.Translation.Test/Services/AddressServiceTest.cs, Gateway/MinistryPlatform.Translation.Test/Services/FinderRepositoryTest.cs, Gateway/MinistryPlatform.Translation/Models/MpAddress.cs, Gateway/MinistryPlatform.Translation/Repositories/AddressRepository.cs, Gateway/MinistryPlatform.Translation/Repositories/FinderRepository.cs, Gateway/crds-angular.test/Services/FinderServiceTest.cs, Gateway/crds-angular/Services/AddressService.cs, Gateway/crds-angular/Services/FinderService.cs
Removed code that tries to geocode addresses search results for finder. 
Also did some clean up of models and changed address update to rest call.
=> Fix error being thrown a lot. Also some cleanup of some old code.

Gateway/MinistryPlatform.Translation.Test/Services/EventParticipantServiceTest.cs, Gateway/MinistryPlatform.Translation/Repositories/EventParticipantRepository.cs
Don't count people who's participation has ended.
=> DE5070 don't count ended participants

CI/TestSQL/02.TestData/01.Batch+Deposit/AddBatchToDeposit.csv, CI/TestSQL/02.TestData/01.Batch+Deposit/CreateBatches.csv, CI/TestSQL/02.TestData/01.Batch+Deposit/CreateDeposits.csv, CI/TestSQL/02.TestData/07.Donation+Distribution/CreateDonations_DonorsHaveUserAccounts.csv
Updated csv files to create a Deposit with one batch of donations
[Browserstack run link](https://www.browserstack.com/automate/builds/9c58caf5d893ebb167a1fc36ef66eadda81eaf71)
=> Updated csv files

CI/TestSQL/02.TestData/03.Group+Attribute/CreateGroups.csv
There was another Scripted user that needed data
=> fixed again

CI/TestSQL/00.PowershellScripts/LoadTestData.ps1, CI/TestSQL/00.TeardownStoredProcs/03.DeleteData_Event_and_Event_Type_StoredProc.sql, CI/TestSQL/02.TestData/03.Group+Attribute/CreateGroups.csv, CI/TestSQL/02.TestData/03.Group+Attribute/CreateGroupsAndAttributes.ps1, CI/TestSQL/02.TestData/03.Group+Attribute/Stored Procs/01.CreateData_CreateGroup_StoredProc.sql
- Create Groups can be configured with the meeting frequency
[TeamCity run](http://mp-ci.centralus.cloudapp.azure.com/viewLog.html?buildId=44906&buildTypeId=Qa_Release_TeardownAndReloadTestData&tab=buildLog#_focus=57&state=57) from this branch. (Errors from data discrepancy between Demo and Int. Fixed in future pr.)
=> Feature/us12598 Group frequency config

CI/TestSQL/02.TestData/03.Group+Attribute/CreateGroups.csv, CI/TestSQL/02.TestData/09.EventParticipants+GroupParticipants/CreateGroupParticipants.csv
=> more fixes

CI/TestSQL/01.TestUsers/CreateUserList.csv
- Adds automation user for Create/Edit Event tool testing
=> feature/US12636 - TD/RL Add Event tool user

crossroads.net/app/common/profile/personal/profilePersonal.controller.js
Desktop: 
Mobile: 
*Note: Toast looked like that before this PR.
=> scroll to topmost error in profile

CI/TestSQL/01.TestUsers/03.Participant/CreateParticipants.csv, CI/TestSQL/01.TestUsers/04.Household+Address/CreateHouseholdAddresses.csv, CI/TestSQL/01.TestUsers/CreateUserList.csv, CI/TestSQL/02.TestData/03.Group+Attribute/CreateGroupAttributes.csv, CI/TestSQL/02.TestData/03.Group+Attribute/CreateGroups.csv, CI/TestSQL/02.TestData/09.EventParticipants+GroupParticipants/CreateGroupParticipants.csv
Made updates to the Automated Test Data .csv files to add a Private Group to test against.
=> Updated Automated Test Data .csv

CI/TestSQL/02.TestData/03.Group+Attribute/CreateGroups.csv
- Group must be available online
=> defect/dewxyz - Connect group fix

CI/TestSQL/01.TestUsers/04.Household+Address/CreateHouseholds.csv
- Drew and Ben have congregation Oakley
=> feature/US-wxyz - Scripted data update 

CI/Reports/CRDS Team Leader Inactive.rdl, CI/SQL/20180411_143800_US10005-change-inactive-report-name.sql
Updated MP report to correspond to proc changes
=> US10005 - Team Leader Gets Inactive Serve Team Email

CI/TestSQL/01.TestUsers/CreateUserList.csv
=> Added load test user

CI/TestSQL/01.TestUsers/03.Participant/CreateParticipants.csv, CI/TestSQL/01.TestUsers/04.Household+Address/CreateHouseholdAddresses.csv, CI/TestSQL/01.TestUsers/CreateUserList.csv, CI/TestSQL/02.TestData/03.Group+Attribute/CreateGroups.csv, CI/TestSQL/02.TestData/09.EventParticipants+GroupParticipants/CreateGroupParticipants.csv
updated the test data reload csv files for new Scripted Host
=> updates to Test Data csv files

crossroads.net/.gitignore, crossroads.net/app/search/search.controller.js
This PR updates the scope for 'media' type search results to coincide with the search integration for media.crossroads.net
---
Related PRs:
crdschurch/crds-media#43
crdschurch/crds-lambda#2
=> US12391 AWS Cloudsearch

crossroads.net/app/index.html
Bump shared-header version
---
crdschurch/crds-maestro#516
=> DE5374 Duplicate Sign In Buttons

crossroads.net/app/index.html
=> [hotfix] DE5374 Duplicate Sign In Buttons

crossroads.net/app/childcare_dashboard/childcare_group/childcareGroup.html
adding auto id to childcare toggle
=> ajcolub/US13229: add auto id to toggle

CI/TestSQL/02.TestData/09.EventParticipants+GroupParticipants/CreateEventAndGroupParticipants.ps1, CI/TestSQL/02.TestData/09.EventParticipants+GroupParticipants/CreateGroupParticipants.csv, CI/TestSQL/02.TestData/09.EventParticipants+GroupParticipants/Stored Procs/CreateData_CreateGroupParticipant_StoredProc.sql
- Added preferred serve event type option when creating a group participant
=> feature/USqaxx - Create Group Participant stored proc update

crossroads.net/app/invoices/invoice.html
just adding an automation id to the div on the invoice paid for an invoice that has already been paid
=> add id to invoice already paid page

CI/TestSQL/02.TestData/09.EventParticipants+GroupParticipants/Stored Procs/CreateData_CreateGroupParticipant_StoredProc.sql
- Allows same participant with different roles in group to be created
=> feature/USqa - Create Group Participant stored proc fix

CI/TestSQL/02.TestData/03.Group+Attribute/CreateContactAttributes.csv, CI/TestSQL/02.TestData/03.Group+Attribute/CreateGroupsAndAttributes.ps1, CI/TestSQL/02.TestData/03.Group+Attribute/Stored Procs/04.CreateData_CreateGroupAttribute_StoredProc.sql, CI/TestSQL/02.TestData/03.Group+Attribute/Stored Procs/05.CreateData_CreateContactAttribute_StoredProc.sql
- Added stored proc, csv and powershell to create a contact attribute
=> feature/us12638 - TD/RL QA script for creating a Contact Attribute

CI/TestSQL/02.TestData/04.Event+EventType/AddChildEvents.csv, CI/TestSQL/02.TestData/04.Event+EventType/CreateEventsAndEventTypes.ps1, CI/TestSQL/02.TestData/04.Event+EventType/Stored Procs/04.CreateData_AddChildEvent_StoredProc.sql
- Added ability to create Child Events during the TD/RL (sql, csv and ps1)
=> feature/USqa - TD/RL scripts to Add Child Event

CI/TestSQL/02.TestData/09.EventParticipants+GroupParticipants/Stored Procs/CreateData_CreateGroupParticipant_StoredProc.sql
=> defect/DEtdrl - Fixed Group Participant creation script

CI/TestSQL/02.TestData/06.PledgeCampaign+Pledge/CreatePledgeCampaigns.csv
update destination id to be the correct id for NOLA
=> update pledge to use correct destination id

CI/TestSQL/StandardScripts/02.TestData/06.PledgeCampaign+Pledge/CreatePledgeCampaigns.csv, CI/TestSQL/StandardScripts/02.TestData/06.PledgeCampaign+Pledge/CreatePledgeCampaignsAndPledges.ps1, CI/TestSQL/StandardScripts/02.TestData/06.PledgeCampaign+Pledge/Stored Procs/01.CreateData_CreatePledgeCampaign_StoredProc.sql
- Added nickname and maximum registrants options when creating a pledge campaign
- Nickname will still default to the campaign name if no nickname is given
=> feature/UStdrl - Add parameters to CreatePledgeCampaign

CI/TestSQL/StandardScripts/02.TestData/06.PledgeCampaign+Pledge/CreatePledgeCampaigns.csv
=> update trip script

CI/TestSQL/StandardScripts/02.TestData/02.Program+Product/CreateProducts.csv
add automation test product to scripting this is the product used on the automation test form for payments testing
=> add automation test product to scripting

CI/TestSQL/StandardScripts/00.TeardownStoredProcs/17.DeleteData_Batch_and_Deposit_StoredProc.sql
- Removed an unneeded variable
=> feature/UStdrl - Fixed typo in QA delete deposit script

CI/TestSQL/StandardScripts/00.TeardownStoredProcs/19.DeleteData_Equipment_StoredProc.sql, CI/TestSQL/StandardScripts/00.TeardownStoredProcs/20.DeleteData_Room_StoredProc.sql, CI/TestSQL/StandardScripts/00.TeardownStoredProcs/21.DeleteData_Building_StoredProc.sql, CI/TestSQL/StandardScripts/00.TeardownStoredProcs/22.DeleteData_Registration_StoredProc.sql, CI/TestSQL/StandardScripts/00.TeardownStoredProcs/23.DeleteData_Location_StoredProc.sql, CI/TestSQL/StandardScripts/02.TestData/04.Event+EventType/Stored Procs/03.CreateData_CreateEvent_StoredProc.sql
- Changed the initial null check and error message to reflect defaults present in the code
=> feature/US14153 - TD/RL loosen create event requirements

CI/SQL/20180723_131800_US14197-more-cogiver-exceptions.sql
* Heads of household who are in the same household, but missing a co-giving relationship
* Co-giving relationship exists, but contacts are not in the same household
=> US14197 - Add two new co-giver exceptions

CI/SQL/20180726_104900_US14420-update-quarterly-giving-statement-function.sql
* Exclude trip giving
* Exclude soft credit donations
* Exclude children under the age of 14
=> US14420 - Update email list for quarterly giving statements

CI/TestSQL/StandardScripts/00.TeardownStoredProcs/02.DeleteData_Participant_StoredProc.sql
- Added delete connect history to delete participants
=> defect/DEtdrl - Fix for QA's Delete Participant stored proc

CI/TestSQL/StandardScripts/01.TestUsers/02.Donor/Stored Procs/1a.CreateData_CreateDonorByContactId_StoredProc.sql
- Changed create donor to use configured defaults for statement type and frequency (to keep things consistent with Core Tools)
=> feature/UStdrl - Create Donor update

Gateway/crds-angular.test/Services/AccountServiceTest.cs, Gateway/crds-angular/Services/AccountService.cs
Added code to create donor record on creation of user account, fixed unit tests
=> US13907 - First Time Giver No Donor Record

CI/TestSQL/StandardScripts/00.TeardownStoredProcs/24.DeleteData_Forms_StoredProc.sql
added stored proc for deleting forms
=> stored proc for deleting forms

CI/SQL/20180801_130100_US14442-update-large-donations-sp.sql, CI/SQL/20180801_133000_US14442-update-new-givers-sp.sql, CI/SQL/20180801_145500_US14442-update-contribution-statement-sp.sql
1) Large Donations (stored proc = report_CRDS_Large_Donations)
2) New Givers (stored proc = report_CRDS_New_Givers)
3) CRDS Contribution Statements (stored proc = report_CRDS_Donor_Contribution_Statement)
=> US14442 - update reports for cogiver

CI/TestSQL/StandardScripts/01.TestUsers/01.Contact+Relationship/CreateContactRelationships.csv
- Padme and Anikin are cogivers
=> feature/US-QA TD/RL - Added cogiver relationship

CI/TestSQL/StandardScripts/02.TestData/04.Event+EventType/CreateEvents.csv
i put a new event in the create event csv
=> script new event

CI/SQL/20180816_013800_US14612-update-checkin-room-data-script.sql, CI/SQL/20180816_125500_US14612-update-capacity-script.sql, CI/SQL/20180816_1347000_US14612-update-single-room-data-proc.sql
Updated some scripts - DO NOT MERGE UNTIL FULL QA REGRESSION ON CHECKIN IN 86!
=> US14612 - Update Checkin Scripts

crossroads.net/app/routes.content.js
Updated to add default redirect
=> DE5803 - oops on profile page when going to giving history

CI/SQL/20180917_140000_US14809-audit-log-helper.sql, CI/SQL/20180917_160000_US14809-donor-statement-method.sql, CI/SQL/20180917_170000_US14809-update-service-church-specific.sql
Add a nightly process to update Statement Frequency and Statement Method for Donor records with recent contributions to ensure that they receive quarterly/annual statements.
=> US14809 - Fix donor statement method

crossroads.net/app/profile/giving/profileGiving.html, crossroads.net/app/profile/giving/recurring/templates/recurring_giving_list.html
do not delete branch after merge as this may be a hotfix on 9/26
=> remove ability to manage recurring gifts, add message about pushpay blackout

crossroads.net/app/profile/giving/profileGiving.html, crossroads.net/app/profile/giving/recurring/templates/recurring_giving_list.html
- remove ability to edit/remove existing recurring 
- remove add new gift button from under recurring gifts tab (we are disabling creation of recurring gifts in embed)
- add messaging to tell user of blackout period
=> pushpay launch - blackout

CI/SQL/20180928_093900_US15168-add-missing-households.sql, CI/SQL/20180928_101400_US15168-add-nightly-sp.sql
This script is intended to automate some of the data cleanup that was previously handled by Mike F.
=> US15168 - Add nightly stored proc to create missing Households

crossroads.net/core/core.config.js
Adding sceDelegateProvider with whitelisting crds-angular netlify urls. Should fix corkboard asset issues.
=> feature/netlify - Adding sceDelegageProvider for corkboard assets.

Gateway/MinistryPlatform.Translation/Repositories/DonorRepository.cs
Should be check of the statement method not type
=> Fixed my stupidity

Gateway/crds-angular/Security/ImpersonateAuthBaseController.cs
More accurately reflecting the previous base controller's impersonate logic
=> Allow Impersonate

Gateway/crds-angular/Security/ImpersonateAuthBaseController.cs, Gateway/crds-angular/Services/Interfaces/IUserImpersonationService.cs, Gateway/crds-angular/Services/UserImpersonationService.cs
Modifying ImpersonateBaseController to call WithImpersonation w/ a userId instead of an accessToken. Some other clean up to make code easier to read.
=> Fixing Impersonate

crossroads.net/app/common/profile/personal/profilePersonal.controller.js, crossroads.net/app/common/profile/personal/profilePersonal.template.html
Adding auth to personal profile page just as the other pages have it implemented.
=> adding auth to profile personal page

crossroads.net/app/common/profile/personal/profilePersonal.controller.js
removing unneeded check for auth to sign up page. whoops.
=> fixing auth on profile personal

Gateway/crds-angular.test/controllers/CheckScannerControllerTest.cs, Gateway/crds-angular/Controllers/API/CheckScannerController.cs
* Remove extra token check
* Comment out controller tests as they do not work with new auth
=> Change CheckScannerController to use new auth

Gateway/MinistryPlatform.Translation/Repositories/ContactRepository.cs, Gateway/MinistryPlatform.Translation/Repositories/Interfaces/IContactRepository.cs, Gateway/crds-angular.test/Services/CampServiceTest.cs, Gateway/crds-angular.test/Services/PaymentServiceTest.cs, Gateway/crds-angular/Controllers/API/CampController.cs, Gateway/crds-angular/Controllers/API/PaymentController.cs, Gateway/crds-angular/Services/CampService.cs, Gateway/crds-angular/Services/Interfaces/ICampService.cs, Gateway/crds-angular/Services/Interfaces/IPaymentService.cs, Gateway/crds-angular/Services/PaymentService.cs
Refactoring both camps and payments here. Started with payments but camps was calling the controller for payments and needed updated as well.
=> Refactor Camp and Payments for AuthDTO instead of token

Gateway/crds-angular/Controllers/API/ProfileController.cs
=> Merge canImpersonate Fix Into Demo

Gateway/crds-angular/Controllers/API/ProfileController.cs
Hotfix to allow nullable value for Can Impersonate
=> Check that canImpersonate has a value. Set to false if it does not.

Gateway/crds-angular.test/Models/Crossroads/AuthHelpers.cs, Gateway/crds-angular.test/Services/CampServiceTest.cs, Gateway/crds-angular.test/Services/ChildcareServiceTest.cs, Gateway/crds-angular.test/Services/PaymentServiceTest.cs, Gateway/crds-angular.test/crds-angular.test.csproj, Gateway/crds-angular/Controllers/API/ChildcareController.cs, Gateway/crds-angular/Services/ChildcareService.cs, Gateway/crds-angular/Services/EventService.cs, Gateway/crds-angular/Services/Interfaces/IChildcareService.cs, Gateway/crds-angular/Services/Interfaces/IEventService.cs
- also added a test helper for camps and payments
=> Refactoring childcare for the new auth

Gateway/crds-angular/Controllers/API/ProfileController.cs
Not the kid's family. The kid can't sign people up for stuff.
=> DE6468 Get the logged in person's family

CI/TestSQL/StandardScripts/01.TestUsers/CreateUserList.csv
Created User for Alicia Keys Forms to use in Form Maker features
=> feature/USWYZX 

Gateway/Crossroads.AsyncJobs/Web.config, Gateway/Crossroads.BulkEmailSync/App.config, Gateway/Crossroads.ChildcareGroupUpdates/App.config, Gateway/Crossroads.ChildcareRsvp/App.config, Gateway/Crossroads.ScheduledDataUpdate/App.config, Gateway/CrossroadsStripeOnboarding/App.config, Gateway/EventReminder/App.config, Gateway/crds-angular/Web.config, Gateway/crds-angular/crds-angular.csproj, Gateway/crds-angular/packages.config
Added logzio configuration everywhere log4net XML configurations were availabl.
=> [2000's IP] Logzio implementation

Gateway/crds-angular.test/Services/WaiverServiceTest.cs, Gateway/crds-angular.test/controllers/WaiverControllerTest.cs, Gateway/crds-angular/Controllers/API/WaiverController.cs, Gateway/crds-angular/Services/Interfaces/IWaiverService.cs, Gateway/crds-angular/Services/WaiverService.cs
The Falcons did not finish testing this PR and a decision was made NOT to move this change to production until next sprint, so we are pulling it out.
=> Revert "Waivers updated to new Auth"

Gateway/crds-angular.test/Services/WaiverServiceTest.cs, Gateway/crds-angular.test/controllers/WaiverControllerTest.cs, Gateway/crds-angular/Controllers/API/WaiverController.cs, Gateway/crds-angular/Services/Interfaces/IWaiverService.cs, Gateway/crds-angular/Services/WaiverService.cs
This reverts commit 63e00512d3c444f0dad983ae31ed1a1f0feff200.
=> Revert "Revert "Waivers updated to new Auth""

Gateway/crds-angular/Services/FirestoreUpdateService.cs
This reverts commit a0c3339ca2e5499701308ca10e49742de3ec872f.
=> Revert "US16957 | Christian | 1st attempt at New Relic logging"

.netlify/state.json, crossroads.net/app/index.html, crossroads.net/core/core.run.js, crossroads.net/core/templates/footer.html, crossroads.net/core/templates/header.html
=> US17451 Nav

crossroads.net/styles/layout/content.scss
Remove z-index on main container to play nicely w/ new header
=> DE6932 ENV Support

crossroads.net/app/index.html
Move script tag higher in the page
=> DE6958 Loading iOS

crossroads.net/core/core.js, crossroads.net/core/core.run.js, crossroads.net/package-lock.json, crossroads.net/package.json
=> DE6937 DoubleClick

crossroads.net/package-lock.json, crossroads.net/package.json
=> USXXXXX - Update CRDS Styles

crossroads.net/app/index.html, crossroads.net/core/templates/footer.html, crossroads.net/core/templates/header.html
Update prefix for header, footer, and snail trail
=> Fix header naming issue

CI/SQL/20190513_130000_Group-hotfix-insert-trigger.sql, CI/SQL/20190513_130000_Group-hotfix-update-trigger.sql, Gateway/crds-angular/Models/Map/MapPin.cs, Gateway/crds-angular/Services/FinderService.cs, Gateway/crds-angular/Services/FirestoreUpdateService.cs, crossroads.net/app/index.html, crossroads.net/core/core.controller.js
Pull components from Netlify, respecting ENV.
=> DEXXXX Components Netlify (development)

crossroads.net/app/index.html, crossroads.net/core/core.controller.js
Pull components from Netlify, respecting env
=> DEXXXX - Components Netlify Dev

crossroads.net/core/core.controller.js, crossroads.net/gulpfile.js
Replace URL for crds-components to mirror other projects in the same ENV
=> DEXXXX Components Netlify Dev

crossroads.net/app/index.html, crossroads.net/core/core.controller.js, crossroads.net/gulpfile.js
Pull components from Netlify, respecting ENV
=> [hotfix] DEXXXX Components Netlify (production)

CI/Reports/CRDS Checkin New Family.rdl, CI/SQL/20190718_132500_US10563-SCRIPT_FOR_UPDATED_StoredProc_Checkin_New_Families.sql
Updated script for CRDS_Checkin_New_Families Report.
=> US0563-CRDS New Family Checkin Script

CI/TestSQL/StandardScripts/00.TeardownStoredProcs/03.DeleteData_Event_and_Event_Type_StoredProc.sql
Most of the changes is formatting. 
The real change is line number 34
=> Added deleting event room attribute for an event room before deleting

CI/SQL/20190809_084500_fix-procs-update-cr_CreateTask, CI/SQL/20190809_090700_fix-procs-update-cr_GetRejectedRoomReservations, CI/SQL/20190809_091600_fix-procs-update-crds_service_clean_room_reservations_nightly
Commit of fixed procs - 
See diffs for changes - 
cr_CreateTask - https://www.diffchecker.com/6bG7mP6Q
cr_GetRejectedRoomReservations - diffchecker.com/6bG7mP6Q
crds_service_clean_room_reservations_nightly - https://www.diffchecker.com/31V8LDEV
=> Update broken procs

CI/Reports/CRDS Large Donations.rdl, CI/SQL/20191008_132500_US18262_SP_report_CRDS_Large_Donations.sql
There are 2 files that need to be code reviewed
=> US18262_Large_Donations_w_Payment_Type

CI/TestSQL/StandardScripts/02.TestData/05.Opportunity+Response/CreateOpportunities.csv
With the last db refresh and changes in service times means some event types no longer exists. Swap out invalid ones with valid ones
=> Event types have change

CI/TestSQL/StandardScripts/00.TeardownStoredProcs/12.DeleteData_Congregation_StoredProc.sql
- Changes already applied to Int
=> feature/DEtd/rl - Updated delete congregations stored proc

CI/SQL/2020-01-21_030300_US18674_StoredProc_report_CRDS_Event_Listing_For_CommunityCare_Email_XML_Report.sql
Please merge this code after approving. I do not have merge privileges.
Thanks,
Shakila Rajaiah
=> US18674-Event Listing EMAIL XML Report script

CI/Reports/CRDS Group Birthday Anniversaries.rdl
Please approve and merge, as I do not have merge privileges..
Thanks,
Shakila.
=> US18701-CI/Reports/CRDS Group Birthday Anniversaries RDL File

CI/Reports/CRDS Group Birthday Anniversaries.rdl, Gateway/crds-angular/Services/LoginService.cs
=> Merge into release for Group Birthday Anniversaries

Gateway/crds-angular/Services/LoginService.cs
Reverts crdschurch/crds-gateway-legacy#5367
=> Revert "Fix"

Gateway/crds-angular.test/Services/LoginServiceTest.cs, Gateway/crds-angular/Services/LoginService.cs, Gateway/crds-angular/Services/PersonService.cs
Reverts crdschurch/crds-gateway-legacy#5366
=> Revert "Feature/us18980 force reset pwd"

Gateway/crds-angular/Services/LoginService.cs
Reverts crdschurch/crds-gateway-legacy#5375
=> Revert "Feature/us18980 reset pwd"

Gateway/crds-angular.test/Services/IsolatedPersonService.cs, Gateway/crds-angular.test/Services/PersonServiceIdentityIntegrationTest.cs, Gateway/crds-angular.test/Services/PersonServiceTest.cs, Gateway/crds-angular/Services/LoginService.cs, Gateway/crds-angular/Services/PersonService.cs
Reverts crdschurch/crds-gateway-legacy#5378
=> Revert "Redo updates..."

CI/TestSQL/StandardScripts/02.TestData/03.Group+Attribute/CreateGroups.csv, CI/TestSQL/StandardScripts/02.TestData/03.Group+Attribute/CreateGroupsAndAttributes.ps1
Groups need a description to display correctly on /connect
=> TD/RL Scripts - Made group description required

CI/SQL/2020-02-18_030300_US18674_StoredProc_report_CRDS_Event_Listing_For_CommunityCare_Email_XML_Report.sql, CI/SQL/2020-02-24_030300_US18674_StoredProc_report_CRDS_Event_Listing_For_CommunityCare_Email_XML_Report.sql
Made the required changes suggested by John Eversole. Please merge this code as i do not have merge privileges in GIT.
Thanks,
Shakila Rajaiah.
=> US18674-Email Event Listing XML Script

Gateway/MinistryPlatform.Translation/Repositories/UserRepository.cs
Hotfix to restore password reset capability.
=> Removed comma from email search

Gateway/Crossroads.AsyncJobs/Processors/CheckScannerBatchProcessor.cs, Gateway/Crossroads.AsyncJobs/Processors/DirectEmailProcessor.cs, Gateway/Crossroads.AsyncJobs/Processors/ScheduledJobProcessor.cs, Gateway/Crossroads.AsyncJobs/Processors/SignupToServeProcessor.cs, Gateway/Crossroads.AsyncJobs/Processors/StripeEventProcessor.cs, Gateway/Crossroads.AsyncJobs/Processors/TripEventProcessor.cs, Gateway/MinistryPlatform.Translation/Repositories/UserRepository.cs
=> Demo Merge 9/8/20

.gitignore, Gateway/crds-angular.api_test/.dockerignore, Gateway/crds-angular.api_test/README.md, Gateway/crds-angular.api_test/cypress.json, Gateway/crds-angular.api_test/cypress/config/demo_crossroads.json, Gateway/crds-angular.api_test/cypress/config/int_crossroads.json, Gateway/crds-angular.api_test/cypress/config/localhost.json, Gateway/crds-angular.api_test/cypress/config/prod_crossroads.json, Gateway/crds-angular.api_test/cypress/config/vault_config.json, Gateway/crds-angular.api_test/cypress/integration/LoginController/POST_login_prodspec.ts, Gateway/crds-angular.api_test/cypress/integration/LoginController/schemas/badRequest.ts, Gateway/crds-angular.api_test/cypress/integration/LoginController/schemas/loginResponse.ts, Gateway/crds-angular.api_test/cypress/plugins/index.js, Gateway/crds-angular.api_test/cypress/shared/test_scenario_factory.ts, Gateway/crds-angular.api_test/cypress/support/commands.ts, Gateway/crds-angular.api_test/cypress/support/index.ts, Gateway/crds-angular.api_test/docker/Dockerfile, Gateway/crds-angular.api_test/docker/README.md, Gateway/crds-angular.api_test/docker/docker-compose.yml, Gateway/crds-angular.api_test/package-lock.json, Gateway/crds-angular.api_test/package.json, Gateway/crds-angular.api_test/tsconfig.json, Gateway/crds-angular.api_test/tslint.json
- Added folder `crds-angular.api_test` and started API test suite
- Added tests for the /api/login endpoint
- Created a Dockerfile and compose file for use in CI pipeline. Right now we can't test updates within the build pipeline before they're deployed, so tests will be configured to run after the deploy and report to Slack if any tests failed. Tests in the CI pipeline will be reported to the Cypress Dashboard which handles Slack notifications.
- API tests are pretty redundant so I'm experimenting with autogenerating them from configs. Please let me know if they're confusing or if you have any suggestions for improving them.
- Better Typescript typedefs
=> feature/US20242 - Init Api Tests

Gateway/MinistryPlatform.Translation.Test/Services/ProgramServiceTest.cs, Gateway/MinistryPlatform.Translation/Repositories/Interfaces/IProgramRepository.cs, Gateway/MinistryPlatform.Translation/Repositories/ProgramRepository.cs, Gateway/crds-angular.test/Services/ProgramServiceTest.cs, Gateway/crds-angular.test/controllers/ProgramCOntrollerTest.cs, Gateway/crds-angular.test/crds-angular.test.csproj, Gateway/crds-angular/Controllers/API/ProgramController.cs, Gateway/crds-angular/Services/Interfaces/IProgramService.cs, Gateway/crds-angular/Services/ProgramService.cs, Gateway/crds-angular/Unity.config, Gateway/crds-angular/crds-angular.csproj
Reverts crdschurch/crds-gateway-legacy#5452
=> Revert "Feature/us20200 remove programs"

Gateway/crds-angular/Controllers/API/EmailCommunicationController.cs, Gateway/crds-angular/crds-angular.csproj
Reverts crdschurch/crds-gateway-legacy#5455
Corkboard is calling /send-email endpoint
=> Revert "Remove Email Communication controller (/Sends)"

CI/TestSQL/README.md, CI/TestSQL/StandardScripts/00.TeardownStoredProcs/08.DeleteData_Donor_StoredProc.sql, CI/TestSQL/StandardScripts/00.TeardownStoredProcs/15.DeleteData_Contact_StoredProc.sql
- Updated test data teardown scripts that broke after an MP update
- Added readme to CI/TestSQL repo with overview and troubleshooting steps to follow when this error is seen again
=> defect/DE8152 - Test data SQL script fix

Gateway/crds-angular.api_test/cypress/api_tests/LoginController/GET_verifyresettoken_spec.ts, Gateway/crds-angular.api_test/cypress/api_tests/LoginController/POST_login_prodspec.ts, Gateway/crds-angular.api_test/cypress/api_tests/LoginController/POST_requestpasswordreset_mobile_prodspec.ts, Gateway/crds-angular.api_test/cypress/api_tests/LoginController/POST_requestpasswordreset_mobile_spec.ts, Gateway/crds-angular.api_test/cypress/api_tests/LoginController/POST_requestpasswordreset_prodspec.ts, Gateway/crds-angular.api_test/cypress/api_tests/LoginController/POST_requestpasswordreset_spec.ts, Gateway/crds-angular.api_test/cypress/api_tests/LoginController/POST_verifypassword_spec.ts, Gateway/crds-angular.api_test/cypress/api_tests/ProfileController/GET_profile_spec.ts, Gateway/crds-angular.api_test/cypress/api_tests/ProfileController/POST_profile_spec.ts, Gateway/crds-angular.api_test/cypress/api_tests/ProfileController/schemas/exceptionResponseSchemas.ts, Gateway/crds-angular.api_test/cypress/api_tests/UserController/GET_user_spec.ts, Gateway/crds-angular.api_test/cypress/api_tests/UserController/POST_user_spec.ts, Gateway/crds-angular.api_test/cypress/shared/CAT/cypress_api_tests.d.ts, Gateway/crds-angular.api_test/cypress/shared/CAT/cypress_api_tests.ts, Gateway/crds-angular.api_test/cypress/shared/mp_models.d.ts, Gateway/crds-angular.api_test/cypress/shared/users.ts, Gateway/crds-angular/Controllers/API/ProfileController.cs, Gateway/crds-angular/Models/Crossroads/Profile/Person.cs
- Added API tests for /api/profile. Note that there are _many_ ways the profile update can fail behind the scenes and not all are covered here (that's a good area for thorough unit tests 😉). 
- Modified the "response property validation" configuration and validation process to allow for custom validation. 
- The /Profile/Person model was just re-tabbed, nothing else was changed.
- I noticed the ModelState.IsValid check in this endpoint probably doesn't do anything because the model is missing the decorators this validation needs. I did not make any changes to the model since it's widely used, but did make notes on how to improve the validation and catch some errors earlier if we want to in a future refactor.
=> feature/US20625 - Added API tests for POST /api/profile

Gateway/MinistryPlatform.Translation/Repositories/GroupRepository.cs, Gateway/crds-angular.api_test/cypress/api_tests/FinderController/GET_participants_groupid_spec.ts, Gateway/crds-angular.api_test/cypress/api_tests/FinderController/schemas/errorResponseSchemas.ts, Gateway/crds-angular.api_test/cypress/api_tests/FinderController/schemas/groupParticipantListSchemas.ts, Gateway/crds-angular.api_test/cypress/shared/enums.ts, Gateway/crds-angular.test/Services/FinderServiceTest.cs, Gateway/crds-angular.test/Services/GroupServiceTest.cs, Gateway/crds-angular.test/controllers/FinderControllerTest.cs, Gateway/crds-angular/Controllers/API/FinderController.cs, Gateway/crds-angular/Models/Crossroads/Groups/GroupParticipantDTO.cs, Gateway/crds-angular/Services/AwsCloudsearchService.cs, Gateway/crds-angular/Services/FinderService.cs, Gateway/crds-angular/Services/GroupService.cs
- Added API tests for GET /finder/participants/{groupId} endpoint
- Auto-formatted all files, so lots of whitespace changed
- Removed dead usings, constructor parameters and/or methods from FinderController, FinderService, GroupServices and GroupRepository
- Removed dead code and linted unit tests
=> feature/US20657 - Added API test for /finder/participants/{groupId}
