crdschurch/crds-gateway-legacy

crossroads.net/README.md, crossroads.net/gulpfile.js, crossroads.net/package.json
* Add new script file for gulp, providing build and dev server tasks
* Update package.json with new dependencies, and deprecate old scripts
* Update README with new instructions for running with gulp
=> US952: Update build to use gulp & webpack instead of npm & webpack

Gateway/MinistryPlatform.Translation.Test/Services/EventServiceTest.cs, Gateway/MinistryPlatform.Translation.Test/Services/GroupServiceTest.cs, Gateway/MinistryPlatform.Translation/Services/EventService.cs, Gateway/MinistryPlatform.Translation/Services/GroupService.cs
This kicks off any process associated to the group and event, in this case, sending email to group participant after signing up
=> US1073: Set quickAdd to true when adding group & event participant sub-page records

crossroads.net/app/my_serve/refine/refineList.directive.js
Had to call `applyFamilyFilter()` in the activate function
=> DE118 - Filter not applying if family is checked

Gateway/MinistryPlatform.Translation.Test/Services/ContactServiceTest.cs, Gateway/MinistryPlatform.Translation/Services/ContactService.cs
Gender_ID and Marital_Status_ID are optional integer profile fields, but they were being returned as 0 instead of null when they were not set in the db.  This was causing issues when saving the profile, if those fields were not changed on the frontend.
=> DE123: Update Contact Service to return nulls for optional nullable fields

Gateway/crds-angular.test/Security/MPAuthTest.cs, Gateway/crds-angular.test/crds-angular.test.csproj, Gateway/crds-angular/Security/MPAuth.cs
Added a new Authorized wrapper that takes two lambda expressions - one to execute when the user is authenticated, one to execute when not authenticated.
=> US1313: Implement an optionally authorized wrapper for gateway controllers to use

crossroads.net/app/give/donation-details.html
This will prevent user from even typing more digits than can be accepted
=> US1409: Updated to set maxlength html attribute on amount input

crossroads.net/app/my_serve/refine/refineList.html
Since the form does not have a submit button, I had to add a hidden
input type. The problem is that if you add an input of type 'submit',
you can't also create it hidden. To remedy this, I added the
`display:none` style to the input tag. I think the best solution in the
long run is to actually add a submit button for the user to press.
=> DE180 submit filter dates on enter key

crossroads.net/app/my_serve/serveTeam.directive.js
When a volunteer chooses 'NO' there roleId is set to 0, so we need to
send a valid roleId to the server when populating dates. If the roleId
is 0, get the first valid roleId in the list of roles
=> DE196 Fix 'TO' field not defaulting to last opp date

crossroads.net/app/give/give_controller.js
Resetting the amountSubmitted indicator when processing a change. This alleviates the error state when the initiative field is clicked,
=> resetting the amountsubmitted indicator when processing a change

crossroads.net/app/give/directives/creditCardInfo.directive.js
Altering validation for credit card and cvc.  Error state was being triggered after the change link was clicked when the credit card and cvc were valid.
=> correcting validation on credit card and cvc

crossroads.net/app/give/give_controller.js, crossroads.net/spec/give/give.controller.spec.js
In fixing DE227, we removed the need to pull email address from $rootScope, as we now get the email address from the MP Contact during the giving flow for a registered user, or from the email address field on the guest giver form.
=> DE270: Don't look for email on $rootScope anymore - we get it from the Contact/Donor now

Gateway/crds-angular.test/Services/StripeEventServiceTest.cs, Gateway/crds-angular/Services/StripeEventService.cs
Stripe sends the net amount, not gross.  Therefore, I was subtracting fees when I should have been adding them.
=> stripe sends net amount

crossroads.net/app/common/giving/services/donation.service.js, crossroads.net/spec/give/give.controller.spec.js
In transitionForLoggedInUserBasedOnExistingDonor, when a donor is retrieved, set the GiveTransferService.view properly based on the default source on the donor.
=> DE447: Set view properly after retrieving donor

crossroads.net/app/giving_history/giving_history.controller.js, crossroads.net/spec/giving_history/giving_history.controller.spec.js
This flag drives the display of the "no giving history" section, as well as actual donations, so needs to be true even when there are no donations.  A separate flag (donation_history and soft_credit_donation_history) drives display of actual donations.
=> DE465: Set donation_view_ready to true when no profile or donations are located

crossroads.net/app/trips/trip_participant_card/tripParticipantCard.directive.js, crossroads.net/app/trips/trip_participant_card/tripParticipantCard.html
* Fixed link to point to tripgiving.amount because the route parameters
were getting lost in the multitude of transitions that were happening
=> DE467 Error on Transition

crossroads.net/app/common/giving/services/donation.service.js
This was causing an infinite digest loop (https://docs.angularjs.org/error/$rootScope/infdig)
=> DE499: Remove set of amountSubmitted in donation.service

CI/US2657-DonationStatusNotNotes.sql
Note that all the page view listed in the AC use the default field list.  therefore, changing the default fields on the page successfully changes the fields for all those views.
=> US2657-donation status added to view, notes removed

Gateway/Crossroads.Utilities/Crossroads.Utilities.csproj, Gateway/Crossroads.Utilities/Extensions/StringExtensions.cs, Gateway/crds-angular.test/Services/EzScanCheckScannerServiceTest.cs, Gateway/crds-angular/Services/EzScanCheckScannerService.cs
* [DE613](https://rally1.rallydev.com/#/27593764268d/detail/defect/46154900660)
* Changed check scanner service to strip off leading zeroes and spaces from check number, and then take the rightmost 15 digits of the check number if it still exceeds 15 (which would be a check number in the 999 trillion range...)
=> DE613: Make sure we don't exceed the MP limit for check number

crossroads.net/app/profile/giving/profileGiving.html
* [DE611](https://rally1.rallydev.com/#/27593764268d/detail/defect/46137081510)
* Updated profile giving template to use dynamic-content directive in place of ng-bind-html, to allow processing of angular code (like ui-sref) in CMS ContentBlocks
* Also updated $root.MESSAGES.noRecurringGifts.content in CMS to use ui-sref="give.recurring" instead of hardcoded link to http://crossroads.net/give
=> DE611: Update to use dynamic-content instead of ng-bind-html on contentblocks

Gateway/crds-angular.test/Services/EzScanCheckScannerServiceTest.cs, Gateway/crds-angular/Services/EzScanCheckScannerService.cs
Hardcode Account and Routing Numbers to stripe for bank accounts so EZScan can test against real checks.  Ignore test results.  Add TODO's so this will be fixed after EZScan tests.
=> US2720 - Hardcode Account and Routing Numbers to stripe for bank accounts

CI/SQL/US222-NonCashAssetPage.sql
* [DE689 Part Deux](https://rally1.rallydev.com/#/27593764268d/detail/defect/47983726679)
* Added security role access, Full access for Admin role
=> DE689: Fix security on Non-Cash Assets Page

Gateway/crds-angular.test/Services/DonorServiceTest.cs, Gateway/crds-angular.test/Services/StripeServiceTest.cs, Gateway/crds-angular/Models/Crossroads/Stewardship/StripeSubscription.cs, Gateway/crds-angular/Services/DonorService.cs, Gateway/crds-angular/Services/Interfaces/IPaymentService.cs, Gateway/crds-angular/Services/StripeService.cs
* [DE770](https://rally1.rallydev.com/#/27593764268d/detail/defect/48687773683)
* When we edit a gift that is currently in trial at Stripe, we will carry the trial period to the new plan.
=> DE770: Carry trial period over when moving subscription to new plan

Gateway/MinistryPlatform.Translation.Test/Services/DonorServiceTest.cs, Gateway/MinistryPlatform.Translation/Services/DonorService.cs
* [DE822](https://rally1.rallydev.com/#/27593764268d/detail/defect/48815512405)
* Now checking for null or 0 in communication template, then fall back to default template
=> DE822: Check for null or 0 to indicate no email template

Gateway/crds-angular.test/Services/StripeServiceTest.cs
Several Stripe unit tests were failing when run late in the day.  The issue was that we are now sending UTC times and dates to Stripe, but our tests were not updated to account for this.  So with local time of 11pm for example, the date we sent to stripe would be the next day, so tests were failing to match expected date.  Updated these tests to expect a date in UTC.
=> Fix bad Stripe unit tests

crossroads.net/app/ang.js
* [DE953](https://rally1.rallydev.com/#/27593764268d/detail/defect/49935576668)
* Reference dependencies properly
=> DE953: Add missing dependencies to ang.js

CI/SQL/Triggers/AutoCreateChildcareEvents.sql
It was breaking when Kevin did the migration because I was assuming that
the inserted record would only be one. It turns out that the migration is
inserting many records with one insert statement(?).
=> Needed to update the childcare trigger

CI/SQL/US3029-CRDS_Create_GL_Account_Mapping.sql
https://rally1.rallydev.com/#/27593764268d/detail/userstory/37394448825
<ol>
<li>The document/csv file can be found <a href="https://docs.google.com/spreadsheets/d/1OkLZ7TOb-S5c38NRuJmDOt_8u0nqw67s3WyR-47fpoU/edit#gid=0">here<a>. </li>
<li>Download the file</li>
<li>Rename it glAccount.csv</li>
<li>Run the command below to generate a sql file. </li>
<li>Go into SSMS and run the generated sql against MP.</li>
</ol>
```
cat glAccount.csv | awk 'BEGIN{printf("SET NOCOUNT ON;\n\n"); } {nf = split($0, flds, ","); printf("-- %s, %s, %s\n", flds[1], flds[2], flds[3]); printf("EXEC [MinistryPlatform].[dbo].[CRDS_Create_GL_Account_Mapping] |%s|, |%s|, |%s|, |%s|, |%s|, |%s|, |%s|, |%s|, |%s|, |%s|;\n\n", flds[1], flds[2], flds[3], flds[4], flds[5], flds[6], flds[7], flds[8], flds[9], flds[10] );}' …
```
=> US1499 - Add a stored proc to load GL Account mapping.

Gateway/crds-angular.test/Services/StripeServiceTest.cs, Gateway/crds-angular/Services/StripeService.cs
* [DE1139](https://rally1.rallydev.com/#/27593764268d/detail/defect/51012594475)
* This allows gifts to process on the correct date selected by the Community Member, regardless of their timezone.
=> DE1139: Send recurring gift times as noon UTC instead of midnight UTC

crossroads.net/app/group_finder/directives/question/input_number.html, crossroads.net/app/group_finder/directives/question/question.controller.js, crossroads.net/app/group_finder/directives/questions/questions.controller.js, crossroads.net/app/group_finder/host/host_review.controller.js
This updates the host flow capacity question to indicated spot already filled as opposed to available slots.
This is dependent on copy changes to the `bravehost` file and will need updating before moving to demo and prod
=> changed from open slots to filled slots

crossroads.net/app/group_finder/directives/group_card/group_card.html
The dashboard participant list was being limited to 3 people before the host was being eliminated from the list.  The filtering of the host is now before the limit 3 which will ensure that 3 are shown if that many participants are in the group besides the host
=> [DE1212] Dashboard should display all participants

crossroads.net/app/group_finder/dashboard/group_detail.controller.js
* The host's nickName will be placed in the scope so that the CMS content can embed the nickname in the mailto link.  
* This is dependent on the CMS content for key: `$root.MESSAGES.groupFinderHostDashboardHelp.content` being changed to 
```
<h4 class="ng-scope">Need help?</h4>
<p class="ng-scope">Have a specific question about your BRAVE group? Send us an email to <a href="mailto:journey@crossroads.net?subject=Question+from+{{hostName}},+a+BRAVE+group+host.">host@crossroads.net</a>.</p>
```
=> [DE1219] Group details page Need Help? mailto subject line

Gateway/Crossroads.AsyncJobs/Web.Demo.config, Gateway/Crossroads.AsyncJobs/Web.Integration.config, Gateway/Crossroads.AsyncJobs/Web.Release.config, Gateway/Crossroads.AsyncJobs/Web.config
The BaseUrl parameter has been in Web.config for a while, but was never used by anything in AsyncJobs.  It was recently referenced in Gateway/crds-angular/Services/EmailCommunication.cs, which is used by AsyncJobs, so AsyncJobs was failing when it tried to get this value.
=> Add missing BaseURL and BaseMPUrl parameters to Web.config and transforms

Gateway/MinistryPlatform.Translation.Test/Services/DonationServiceTest.cs, Gateway/MinistryPlatform.Translation/Services/DonationService.cs, Gateway/crds-angular.test/Services/DonationServiceTest.cs, Gateway/crds-angular/Services/DonationService.cs
* [DE1335](https://rally1.rallydev.com/#/22244455064d/detail/defect/53100051269)
* Needed to pass Donation_Status_ID from MP DonationService up to crds-angular DonationService, in order to actually use the status in other services...
=> DE1335: Pass Donation_Status from MP to crds-angular

crossroads.net/app/go_volunteer/goVolunteer.routes.js
Somehow the route for non-crossroads page was trying to authenticate.
These pages do not need authentication, it must have been a copy and
paste error or a merge conflict issue.
=> DE1348 Fix broken links

crossroads.net/app/go_volunteer/goVolunteer.routes.js, crossroads.net/app/go_volunteer/page/goVolunteerPage.component.js
After a refresh in the middle of the GoCincy flow, we should be
redirected to the organizations page. This was not happening for
organizations other than Crossroads.
* The $state.go had the wrong route name - corrected.
* Locations resolve was looking for the organizationId but after a
refresh it did not exist. Added a guard clause.
=> DE1439 Refresh in middle of Go Cincinnati Flow

crossroads.net/app/common/profile/household/profileHousehold.directive.js, crossroads.net/app/common/profile/household/profileHousehold.template.html, crossroads.net/app/common/profile/personal/profilePersonal.template.html, crossroads.net/app/signup/community_group_signup/communityGroupSignupForm.html
Hacky fix, but bootstrap breakpoints aren’t based off the modal width
and thus we need different grid classes for modals
=> US3242-Fixing Modal Household Header

CI/SQL/20160601090100_DE1526-script-request-status.sql
[DE1526](https://rally1.rallydev.com/#/22244455064d/detail/defect/56554432987)
We didn't script inserting the Childcare Request Statuses, so the id that
we referenced in the .NET code did not coorespond to the correct status.
* Wrote script to drop current statuses and insert again with explicit ID's
=> DE1526 Primary Keys for Request Status

Gateway/crds-angular.test/Services/StripeServiceTest.cs, Gateway/crds-angular/Services/StripeService.cs
* [DE1533](https://rally1.rallydev.com/#/22244455064d/detail/defect/56871787601)
* Build is currently failing due to insufficient space on DB server while processing DB scripts, but all tests are passing.
* Change was to expand **data.**balance_transaction and **data.**charge, otherwise Stripe complains with the following:
```javascript
{
error: {
type: "invalid_request_error"
message: "This property cannot be expanded (balance_transaction). You may want to try expanding 'data.balance_transaction' instead."
}
}
```
=> DE1533: Fix Stripe GetChargeRefund call

crossroads.net/package.json
crds-core was updated to allow for node-sass compilation at version 3.7 and beyond. This is simply updating the package to pull the most recent instead of locking you into 3.4.2.
=> US4167:Updated node-sass package

Gateway/crds-angular/App_Start/SwaggerConfig.cs
This allows us to specify RequiresAuthorization on endpoints that have no parameters.
=> Setup parameters on any RequiresAuthorization endpoints

crossroads.net/app/streaming/streaming.component.html, crossroads.net/styles/pages/streaming.scss
This PR delivers [US-4419](https://rally1.rallydev.com/#/41662702253d/detail/userstory/58984628724) by implementing production ready URLs for any image associated with the streaming landing page.
Since this work originated as a sub-branch of `feature/US4291-bootstrap-for-angular2` this PR is attempting to merge these updates back into that branch vs development.
=> US-4419 Production Ready Images

crossroads.net/app/childcare_dashboard/childcare_group/childcareDashboardGroup.controller.js, crossroads.net/spec/childcare_dashboard/childcare_group/childcareGroup.controller.spec.js, crossroads.net/spec/spec_index.js
We passing a string to the `$rootScope.$emit('notify')` method. Updated to pass a cms message.
=> Properly Display Error Messages

crossroads.net/app/index.html, crossroads.net/styles/pages/streaming.scss
This PR updates the embedded Typekit account to use Crossroads credentials.
=> US4411: Typekit Embed Script

crossroads.net/app/streaming/countdown.component.ts, crossroads.net/app/streaming/event.ts, crossroads.net/app/streaming/streaming.component.ts, crossroads.net/app/streaming/streaming.ng2component.html, crossroads.net/app/streaming/streamspot.service.ts, crossroads.net/spec-ts/streaming/countdown.component.spec.ts, crossroads.net/spec-ts/streaming/event.spec.ts, crossroads.net/spec-ts/streaming/streaming.component.spec.ts, crossroads.net/spec-ts/streaming/streamspot.service.spec.ts
This PR refactors the `streamspot.service.ts` by implementing a couple EventEmitter objects. This way, the service can be utilized as a singleton so we can listen for the successful promise resolution from more than one location.
/cc @samueljmello
=> US4541: Evaluate Event Status

Gateway/crds-angular/Services/ChildcareService.cs
[DE1657](https://rally1.rallydev.com/#/27593501023d/detail/defect/59666556076)
Cancel did not work when the group start date was after the current date.
We pass false to getGroupParticipants to indicate we want ALL participants
regardless of the group start date.
=> Update cancelRsvp to get all GroupParticipants

crossroads.net/app/mp_tools/mpTools.routes.js, crossroads.net/app/mp_tools/request_childcare/requestChildcare.controller.js, crossroads.net/spec/mp_tools/request_childcare/requestChildcare.controller.spec.js
[DE1703](https://rally1.rallydev.com/#/27593501023d/detail/defect/60237106158)
No reason to make other calls to MP when the user is not authorized to
use the tool. Short circuit and return as soon as unauthorized status is
discovered.
* add check and early return in constructor
* update tests to reflect changes
=> short circuit if not allowed access to the tool

crossroads.net/app/group_tool/my_groups/myGroups.html
The target link `/groups/create` will automatically redirect non-leaders to the Leadership Training page
=> US4619 - Add the correct link from My Groups to Lead a Group page

crossroads.net/app/group_tool/my_groups/group_card/groupCard.html, crossroads.net/styles/modules/group-cards.scss
* Rename "View Invites" to "View Requests"
* Adjust font size on card buttons from @media (max-width: 1200px) and (min-width: 992px) so that "View Requests" will fit in the button and look correct
* Adjust button icon vertical centering
=> US4617 - Rename My Group page group cards "View Invites" button

crossroads.net/app/group_tool/my_groups/myGroups.html, crossroads.net/styles/modules/group-cards.scss
* The order of the Lead a Group and Find a Group tools has been temporarily reversed
* The Find a Group tool has text explaining it is not yet available
* The Find a Group icon appears disabled
=> US4618 - Disable the find a group tool on the My Groups page until Aug 27

crossroads.net/app/group_tool/group_detail/about/groupDetail.about.html, crossroads.net/styles/helpers/utilities.scss, crossroads.net/styles/main.scss, crossroads.net/styles/modules/group-detail-about.scss
Fix layout of the Group Detail About tab component so that on tablet/mobile the missing profile image does not take up a huge amount of space.  The profile image will be to the left of the group name on mobile and the group name will have a larger font size
Re-build the row/column layout so that the entire right column of key/values drops below the left column on mobile, instead of interleaving.  
Right align Edit button on desktop, full width on mobile
**Desktop**
**mobile**
=> US4624 - Group Detail - About - Mobile responsive layout fix

crossroads.net/app/childcare_dashboard/childcare_group/childcareDashboardGroup.controller.js, crossroads.net/spec/childcare_dashboard/childcare_group/childcareGroup.controller.spec.js
[DE1656](https://rally1.rallydev.com/#/27593501023d/detail/defect/59666065140)
Setup logic belongs in lifecycle hooks.
=> Move constructor logic to onInit lifecycle hook

crossroads.net/app/group_tool/group_detail/about/groupDetail.about.html
* Group Detail About page "Edit" button will be right aligned on desktop
* Group Detail About page "Edit" button will be full width on mobile
=> DE1734 - Fix button alignment and sizing for the Group Detail About page

crossroads.net/app/group_tool/group_detail/requests/groupDetail.requests.controller.js, crossroads.net/app/group_tool/group_detail/requests/groupDetail.requests.html, crossroads.net/spec-es6/group_tool/group_detail/requests/groupDetail.requests.controller.spec.js
* Related to changes made for [US4644](https://rally1.rallydev.com/#/22244455064d/detail/userstory/60309945483)
* Page was not displaying results if the group only had requests or invites (but not both)
* Also some js errors were popping up in the console, related to this - fixed by adding some new controller methods
=> Fix requests page display when there are not both requests and invites

crossroads.net/app/group_tool/group_detail/requests/groupDetail.requests.html, crossroads.net/styles/modules/group-requests.scss
Rebuild the requests tab as a bootstrap grid instead of table for better control over responsive behaviors.
* Deny / Approve button stack above each other at `sm` size
* Deny / Approve button stack below user data at `xs` size
* Invite Someone button moves to top at `xs` size for mobile
* User photo is a fixed size with margin instead of taking up a bootstrap col / table col
* Use .ellipsis on data cells to avoid text overlaps
=> US4626 - Rebuild Group Detail Requests tab for responsiveness

crossroads.net/styles/modules/group-participants-cards.scss
Ignore flex CSS styling properties on iOS 8 and display as list of divs with bootstrap styling.  This fixes iPhone and iPad at iOS 8.
=> DE1767 - Fix participant layout on iOS 8

crossroads.net/app/group_tool/confirm_request/confirmRequest.component.js, crossroads.net/app/group_tool/confirm_request/confirmRequest.controller.js, crossroads.net/app/group_tool/confirm_request/confirmRequest.html, crossroads.net/app/group_tool/confirm_request/index.js, crossroads.net/app/group_tool/group_detail/about/groupDetail.about.html, crossroads.net/app/group_tool/group_search_results/groupSearchResults.controller.js, crossroads.net/app/group_tool/group_search_results/groupSearchResults.html, crossroads.net/app/group_tool/index.js
Note:   UI layout only, Submitting request functionality is mocked
Clicking "Back to Search Results" dismisses the modal
Clicking on the darkened window overlay dismisses the modal
Clicking the "Send Request" button mocks the API call with 2 sec timeout, then dismisses modal
"Description" label stacks with description text to avoid overlaying
=> US4696 - Request to Join - Confirm Request Modal

crossroads.net/app/group_tool/group_search_filter/groupSearchFilter.controller.js, crossroads.net/spec-es6/group_tool/group_search_filter/groupSearchFilter.controller.spec.js
* [DE1779 - Filters not working for groups without age range](https://rally1.rallydev.com/#/27593764268d/detail/defect/60997784532)
=> DE1779: Handle groups with missing age range

crossroads.net/app/group_tool/group_detail/participants/groupDetail.participants.html, crossroads.net/app/group_tool/group_detail/requests/groupDetail.requests.html, crossroads.net/app/group_tool/group_message/groupMessage.component.js, crossroads.net/app/group_tool/group_message/groupMessage.controller.js, crossroads.net/app/group_tool/group_message/groupMessage.html, crossroads.net/spec-es6/group_tool/group_message/groupMessage.controller.spec.js
* [US4568 - Require message when denying request or removing participant](https://rally1.rallydev.com/#/27593764268d/detail/userstory/59861948287)
* Note that this story is only to refactor the message component to allow users to specify whether the message is required or not, and prevent sending an email without a message if required.
* There is an existing defect, [DE1775](https://rally1.rallydev.com/#/27593764268d/detail/defect/60974721637), that will address issues with the actual email.
=> US4568: Add required message functionality to message component

crossroads.net/app/streaming/videojs.component.ts, crossroads.net/app/streaming/videojs.ng2component.html, crossroads.net/styles/pages/streaming.scss
This PR customizes the VJS player per the notes in [US4536](https://rally1.rallydev.com/#/41662702253d/detail/userstory/59651875173). I also refactored `videojs.component` by adding a new `debug` instance variable which allows you to bypass the redirect during times when a live stream is not available.
=> US4536: Streaming Video Embed

crossroads.net/app/group_tool/group_search_results/groupSearchResults.html
* [US4640 - UX - Group Search Results - Result row hides when group detail open](https://rally1.rallydev.com/#/22244455064d/detail/userstory/60297542646)
=> US4640: Hide search result when details are open

crossroads.net/app/group_tool/create_group/createGroup.html, crossroads.net/app/group_tool/create_group/preview/createGroup.preview.html, crossroads.net/app/group_tool/edit_group/editGroup.html, crossroads.net/app/group_tool/end_group/endGroup.html, crossroads.net/app/group_tool/group_detail/participants/groupDetail.participants.html, crossroads.net/app/group_tool/group_detail/requests/invite/groupDetail.invite.html, crossroads.net/app/group_tool/group_invitation/groupInvitation.html, crossroads.net/app/group_tool/group_message/groupMessage.html
* Right align any button that was still centered
* Make sure buttons are full-width and stack vertically with a small margin on mobile
* Change some buttons to `btn-standard` so there is only one "primary" button per page/form
=> US4697 - Right align group tool buttons, stack on mobile

crossroads.net/styles/modules/group-participants-cards.scss
Set the flex: css style to `non` so that the participant items will honor the bootstrap widths
Adjust margin-left by -1px because Safari is wrapping for some reason when it shouldn't
=> DE1808 - Fix for participant layout issue

Gateway/MinistryPlatform.Translation.Test/Services/CommunicationServiceTest.cs
* Previously was comparing a DateTime in dictionary to DateTime.Now, but those were sometimes not exactly equal, causing test failure.  Now we just make sure the value in the dictionary is relatively close to DateTime.Now.
* No associated defect or user story to approve for this PR
=> Fix test that would occasionally fail due to DateTime mismatch

crossroads.net/app/group_tool/group_detail/groupDetail.html, crossroads.net/app/group_tool/group_detail/participants/groupDetail.participants.html, crossroads.net/styles/helpers/utilities.scss
Link will be shown when there are zero participants
Increase spacing between buttons and support text
=> DE1839 - Participant Tab - Back to My Groups link show for zero participants

crossroads.net/app/group_tool/group_search_results/groupSearchResults.html
Show "Online" text for desktop / mobile search results where the `!group.hasAddress()`
Implement Map link and Distance for the mobile search results list
Note:  On mobile, the Google maps will only show a true responsive map if using a device, iOS Simulator or reloading the map tab in Chrome dev tools using a device spec
=> US4823 - "Online" search results rows

crossroads.net/app/group_tool/create_group/createGroup.controller.js, crossroads.net/app/group_tool/create_group/createGroup.html, crossroads.net/app/group_tool/edit_group/editGroup.html, crossroads.net/app/group_tool/groupTool.routes.js, crossroads.net/app/group_tool/my_groups/myGroups.html
* Cancel button only visible if linked from My Groups dashboard and will take you back to My Groups (the ui-router state that calls to `grouptool.create` must provide a state param `cancelSref` with the state the cancel button should return to.  IF there is no `cancelSref` the Cancel button will not be visible
* If clicked from leader approval email to Start a Group, there should be no Cancel button
* Cancel button always visible and takes me back to Group Detail About tab
=> US4782 - Add cancel link to Create and Edit groups pages

crossroads.net/app/common/giving/services/donation.service.js, crossroads.net/app/trips/signup/tripDeposit/templates/tripDepositAccount.html, crossroads.net/spec/common/giving/donation.service.spec.js
Fixes: [DE1835](https://rally1.rallydev.com/#/27593501023d/detail/defect/61462012686)
which is a defect on [US4506](https://rally1.rallydev.com/#/27593501023d/detail/userstory/59569138695)
* add some error handling to `createCard()` and `createBank()` in the
[donationService](crossroads.net/app/common/giving/services/donation.service.js)
* updated [tripDepositAccount.html](crossroads.net/app/trips/signup/tripDeposit/templates/tripDepositAccount.html)
to include `bankInfoSubmitted` flag in `<bank-credit-card-details>`
directive
=> Add error handling to donation service

crossroads.net/app/group_tool/group_detail/participants/groupDetail.participants.html
needs to be handled as a bootstrap column so that on mobile the inline-block and the pull left will not cause the buttons and link to be in the same row
=> DE1866 - Fix mobile link for Back to My Groups

crossroads.net/app/group_tool/confirm_request/confirmRequest.html, crossroads.net/app/group_tool/create_group/createGroup.html, crossroads.net/app/group_tool/create_group/preview/createGroup.preview.html, crossroads.net/app/group_tool/edit_group/editGroup.html, crossroads.net/app/group_tool/end_group/endGroup.html, crossroads.net/app/group_tool/group_detail/about/groupDetail.about.html, crossroads.net/app/group_tool/group_detail/participants/change_participant_role/changeParticipantRole.html, crossroads.net/app/group_tool/group_detail/participants/groupDetail.participants.html, crossroads.net/app/group_tool/group_detail/requests/invite/groupDetail.invite.html, crossroads.net/app/group_tool/group_invitation/groupInvitation.html, crossroads.net/app/group_tool/group_message/groupMessage.html, crossroads.net/app/group_tool/group_search_filter/groupSearchFilter.html
Create Group (linked from My Groups) - Cancel / Preview Group
Create Group Preview -  Edit / Submit Group
Edit Group - Cancel / Preview Group
Group Detail About tab - End Group / Edit 
End Group - Cancel / Submit
Participants - Edit / Email Group
Change Participant Role - Cancel / Change Role
Invite Someone - Cancel / Send
Deny Request - Cancel / Deny
Accept Request - Cancel / Deny
Search Filters - Cancel / Update Filters
Confirm Request - Back to Search Results / Send Request
Contact Group Leader - Back to Search Results / Send
Join a Group invitation preview - No Thanks / Join Group
Create Group (linked from My Groups)
* Preview Group
* Cancel
Create Group Preview
* Submit Group
* Edit
Edit Group
* Preview Group
* Cancel
Group Detail About tab
* Edit 
* End Group
End Group
* Submit
* …
=> US4806 - Switch button order on mobile so that primary buttons are on top

crossroads.net/app/streaming/reminder-modal.component.ts, crossroads.net/app/streaming/streaming.ng2component.html
This PR updates the reminder-modal to default to the next available stream date, per [DE1879](https://rally1.rallydev.com/#/41662702253d/detail/defect/62120424516?fdp=true). Users should still be required to select a time but by default, they should not have to choose a day (unless they want to).
=> DE1879 - Date Selector Default

crossroads.net/app/streaming/countdown.component.ts, crossroads.net/app/streaming/streaming.component.ts, crossroads.net/app/streaming/streaming.ng2component.html, crossroads.net/styles/pages/streaming.scss
This PR delivers [DE1880](https://rally1.rallydev.com/#/41662702253d/detail/defect/62121416014) by moving the "Remind Me" button into the countdown component so it's not visible until the countdown renders.
=> DE1880 - Reminder Button Context

crossroads.net/app/streaming/reminder-modal.component.ts
This PR will reset the reminder-form values to their initial state when the modal is closed. For more details, please review [DE1888](https://rally1.rallydev.com/#/41662702253d/detail/defect/62181352903).
=> DE1888 - Set Reminder Defaults

crossroads.net/styles/pages/streaming.scss
This PR ensures that the modal transition after clicking the watch now button is black, not white. For more details, please review [DE1882](https://rally1.rallydev.com/#/41662702253d/detail/defect/62122537439).
=> DE1882 - White Page Transition to Watch Now Stream

crossroads.net/app/streaming/content-card.component.ts, crossroads.net/app/streaming/content-card.ng2component.html, crossroads.net/app/streaming/video.ng2component.html
This PR is related to [DE1893](https://rally1.rallydev.com/#/41662702253d/detail/defect/62186581921). 
These items are appearing hidden in the modal window due to a problem with wow.js – it seems that it cannot animate items that don't exist in the DOM, when the page has loaded. To work around the issue, I've removed the animation on these elements, within this context only. 
This is not the ideal resolution but represents the quickest path to success with the least amount of risk prior to the code freeze. Feel free to add a new user-story for reimplementing the animations within the modal window during our next sprint.
=> DE1893 - Digital Program

CI/MigrationUtilities/GroupResources/README.md
When the CMS build is deployed, it will not have the groupresources/images or groupresources/pdf folders.  Adding instructions for creating these folders.
=> Update README with additional file upload details

crossroads.net/app/group_tool/group_detail/participants/participant_card/groupDetail.participant.card.html, crossroads.net/app/group_tool/group_detail/requests/groupDetail.requests.html
=> US4786 - Participant tab and Request tab emails should be mailto links

crossroads.net/app/common/profile/household/profileHousehold.template.html, crossroads.net/core/validators/validDropdownValue.directive.js
[DE1916](https://rally1.rallydev.com/#/27593501023d/detail/defect/62612530680)
Sometimes the value passed in to the validDropdown validator is an
unresolved promise. In those cases, we need to assume that any value
outside of `null`, `undefined` or `0`.
* add condintional to `validDropdown` validator to look for non-empty list
:tongue:
=> make validDropdown check for valid value

crossroads.net/app/streaming/content-card.ng2component.html, crossroads.net/app/streaming/streaming.component.ts, crossroads.net/app/streaming/video.component.ts, crossroads.net/core/linked_content/linked-content-ng2.component.ts, crossroads.net/styles/modules/crds-card.scss, crossroads.net/styles/pages/streaming.scss
This PR updates the content-card directive to use background images instead of inline images so that the image area is covered, even in the case of images that are smaller than the content-area.
=> DE1894 - Refactor Content Cards for Background Images

crossroads.net/app/trips/signup/signupStep.controller.js, crossroads.net/app/trips/signup/tripsSignup.service.js
[DE1921](https://rally1.rallydev.com/#/27593501023d/detail/defect/62690564891)
Choosing a spiritual life option and then progressing through the
application and then coming back to the question should not wipe out
previous answer.
* keep track in the tripsSignupService that the page was initially loaded
* reset flag on reset call
=> Save current answer to Spiritual Life Question

crossroads.net/app/streaming/reminder-modal.component.ts
This PR delivers [DE1922](https://rally1.rallydev.com/#/41662702253d/detail/defect/62759497742) by updating the streaming reminder component so that selections for date/time and phone/email persist after the modal has been closed and then reopened. 
Note– after discussing this with Isaac, we agreed that this defect really only applies to the persistence of previously selected values, with sole regard to field validation following a close/reopen event. Let me know if you have any questions about this distinction.
=> DE1922 - Selected Time Reminder

crossroads.net/app/group_tool/group_detail/participants/groupDetail.participants.html, crossroads.net/app/group_tool/group_detail/requests/groupDetail.requests.html
=> US4897 -  Participant & Request tab headings on Mobile

crossroads.net/app/streaming/content-card.ng2component.html
Apply `img-background` selector to content cards for better image handling for Retina screens. See the discussion on [DE1894](https://rally1.rallydev.com/#/41662702253d/detail/defect/62186866087/discussion) for more information.
=> DE1894 - Digital Program Images

crossroads.net/app/group_tool/group_search_filter/groupSearchFilter.html, crossroads.net/app/group_tool/group_search_results/groupSearchResults.html, crossroads.net/styles/layout/content.scss, crossroads.net/styles/layout/header.scss, crossroads.net/styles/main.scss, crossroads.net/styles/modules/group-search-filter.scss
* Site header is given z-index 20, Site "main" content is given z-index 10
* Clear Filters link is no longer visible when the Filters are collapsed
=> US4984 - Search filter as an overlay

crossroads.net/app/group_tool/create_group/preview/createGroup.preview.html, crossroads.net/app/group_tool/group_detail/about/groupDetail.about.component.js, crossroads.net/app/group_tool/group_detail/about/groupDetail.about.controller.js
The `isLeader` flag was being set using the result from a `this.groupService.getIsLeader()` call, however in the Create Group Preview process, the group hasn't been added to the database yet and so the API call is returning a 404 and the isLeader flag isn't being set true.  
The new input binding allows the Create Preview component to explicitly set `is-leader=true`
=> DE1936 - Add a Group Detail about component isLeader input binding

crossroads.net/app/group_tool/edit_group/editGroup.html
The title and description paragraph are now a content block matching the structure of the Create Group html page
=> US4709 - Edit Group title should be a content block

crossroads.net/app/live_stream/content_card/contentCard.html, crossroads.net/app/live_stream/stream/stream.html
Digital program titles were not getting truncated correctly. This is a bug fix for that issue.
=> DE1989: Get digital program titles displaying correctly when truncated.

crossroads.net/app/live_stream/countdown_header/countdownHeader.html, crossroads.net/styles/pages/streaming.scss
**Countdown is wrapping on on thinner devices**
On [https://int.crossroads.net/live](https://int.crossroads.net/live), the countdown feature wraps on smaller screens. 
>Refactor CSS to change the layout of the countdown feature, mobile-first design using media queries to target larger screens.
=> DE2117 - Countdown Shouldn't Wrap on Thinner Devices

Gateway/MinistryPlatform.Translation.Test/Services/EventServiceTest.cs, Gateway/MinistryPlatform.Translation/Repositories/EventRepository.cs, crossroads.net/app/camps/camp_waivers/camp_waivers.controller.js
Fixed bug with REST call to get Waivers to ensure only records for the specified contact are returned.
Display a growl error if Next button is clicked without selecting a radio button
=> DE2154 - Validation error if Waiver selection not made

Gateway/crds-angular/packages.config
* Nuget was unable to pull in version 4.1.0 of
* System.text.RegularExpressions
* System.net.http
* This rolls back to 4.0.0
=> fix for nuget packages in api versioning

Gateway/crds-angular/Controllers/API/CampController.cs, crossroads.net/app/camps/application_page/camper_info/camper_info.controller.js, crossroads.net/app/camps/application_page/camper_info/camper_info_form.service.js, crossroads.net/app/camps/application_page/emergency_contact_info/emergency_contact.controller.js, crossroads.net/app/camps/application_page/emergency_contact_info/emergency_contact_form.service.js, crossroads.net/app/camps/application_page/medical_info/medical_info.controller.js, crossroads.net/app/camps/application_page/medical_info/medical_info_form.service.js, crossroads.net/app/camps/application_page/product_summary/product_summary.controller.js, crossroads.net/app/camps/application_page/product_summary/product_summary_form.service.js, crossroads.net/app/camps/camps.service.js, crossroads.net/app/camps/camps_family/camp_household_members/camp_household_members.controller.js, crossroads.net/app/camps/camps_family/camp_household_members/camp_household_members.html, crossroads.net/spec/camps/application_page/camps_medical_info/camps_medical_info.component.spec.js, crossroads.net/spec/camps/application_page/camps_medical_info/medical_info_form.service.spec.js, crossroads.net/spec/camps/application_page/emergency_contact_info/emergency_contact.component.spec.js, crossroads.net/spec/camps/application_page/emergency_contact_info/emergency_contact_form.service.spec.js, crossroads.net/spec/camps/application_page/product_summary/product_summary.component.spec.js, crossroads.net/spec/camps/application_page/product_summary/product_summary_form.service.spec.js, crossroads.net/spec/camps/camper_info/camper_info.component.spec.js, crossroads.net/spec/camps/camper_info/camper_info_form.service.spec.js, crossroads.net/spec/camps/camps.service.spec.js
I've added two approaches for ensuring we aren't getting the wrong camper data.  
1.  Added CampsService.initializeCampData() and CampsService.initializerCamperData()... the initializeCamperData() function will be called when you click on a family member on the /family page.  That way we ensure that we're starting fresh for a second family member
2. Each of our "Form Services" e.g. CamperInfoForm now has a pair of classes.  The actual injected service is a factory that you must call .createForm() on.  e.g. CamperInfoForm.createForm().  This gives you an individual instance of the current form class which will only be used for the current page controller.  That way when a user revisits the page, potentially for a different camper, all new data will be retrieved from the CampsService cache
=> DE2185 - Clear Camper Data

crossroads.net/app/camps/application_page/medical_info/medical_info_form.service.js, crossroads.net/app/formlyBuilder/formlyConfig/types/phoneNumberValidator.js
... to ignore empty strings as well as null.  Note that this also required a change to the medical info form service to pass undefined for any value that was delete and is now an empty string.  This fix does *not* handle the N/A values which are part of DE2210
=> DE2216 - Change the formly phone number validator

crossroads.net/app/camps/application_page/camps_payment/camps_payment.controller.js
By making the iframe resizer use an interval it forces a check on every
page refresh rather than when it thinks it needs to check. This makes
the animation look very smooth.
=> DE2313 Forced the iframe resize to use interval

crossroads.net/app/camps/camps_family/camps_family.controller.js, crossroads.net/spec/camps/camper_info/camper_info.component.spec.js, crossroads.net/spec/camps/camps_family/camps_family.component.spec.js
* The logic when determining whether or not to show a generic cms
message failed when the specific cms message was empty.
=> DE2440 Missing CMS Message

crossroads.net/app/live_stream/stream/stream.controller.js
This PR removes a method reintroduced via 9b68f471b8582e1d1e6b3384c4baaa72a57d2b9d that refers to iFrameResizer – since this dependency was moved out of stream.controller a few commits ago, it was throwing an error. My best guess is that this is result of borked merge that took place yesterday. 
Let me know if you have any questions.
=> DE2503 Styles Broken

crossroads.net/app/live_stream/stream/stream.controller.js, crossroads.net/app/live_stream/stream/stream.html
This PR refactors an inline script on /live/stream to remove ES6 references which are creating problems in iOS9. 
To be clear, the nature of this script and its location inline within the template is debatable and may need to be removed entirely. I'm going to discuss this situation with @bzmillerboy this afternoon  - considering this code has already been merged into development, I am simply fixing the bug vs. refactoring the inline script. 
Let me know if you have any questions.
=> DE2504 - Stream Broken on iOS9

crossroads.net/styles/pages/streaming.scss
Remove left-padding from inline giving widget so padding matches.
=> DE2535 - Left margin on embed not the same

crossroads.net/app/live_stream/stream/stream.html, crossroads.net/styles/pages/streaming.scss
Change layout so horizontal slider loads before the inline giving widget on mobile devices.
> On the /live/stream page, need to revise the order of elements on mobile such that the horizontal slider appears above the inline giving iframe on mobile. 
=> US6152 - Revise mobile stack on stream page

crossroads.net/app/live_stream/stream/stream.html
This PR addresses a bug on certain browsers preventing users from fully advancing the horizontal slider. FYI – I was only able to recreate this scenario via changing the browser zoom level from 100% to 110% or 90%.
=> DE2517 - Horizontal Slider

CI/DatabaseRestoreFromBlob.ps1
This fixes allowing CR.NET to login and user the system successfully after a DB restore
=> DE2562: Added SQL to update register_api password after a restore.

crossroads.net/app/live_stream/stream/stream.html
https://www.dropbox.com/s/62fwjp3a6r1znwy/live-bug.png?dl=0
Please make sure that Give Widget goes back to the right side of the "do not miss" (it was originally designed this way and currently it's on the left side).
=> DE2576 - Two give widgets on stream page

crossroads.net/app/camps/camps.service.js, crossroads.net/spec/camps/camps.service.spec.js
Adding a timestamp as a query param on the product info resource forces
the call to be unique each time it is made which prevents the browser
from caching it.
=> DE2575 Added timestamp to product info request

crossroads.net/app/camps/application_page/camps_payment/camps_payment.controller.js, crossroads.net/spec/camps/application_page/camps_payment/camps_payment.component.spec.js
There was logic missing from the if-else statement in the buildUrl
function that caused the redirect url to point to the confirmation page
instead of the payment confirmation page when the back button is used to
get to the payments page.
* added a test case
=> DE2582 added logic to buildUrl function

Gateway/MinistryPlatform.Translation.Test/Services/EventServiceTest.cs, Gateway/MinistryPlatform.Translation/Repositories/EventRepository.cs
We are having an issue with our Camps Dashboard  trying to get all camp events using the `EventRepository.GetEvents(string eventType, string token)` method and it appears to have been changed to retrieve the `Event_Type_ID` [see here]( https://github.com/crdschurch/crds-angular/blob/development/Gateway/MinistryPlatform.Translation/Repositories/EventRepository.cs#L322) . The problem is that `Event_Type_ID` is NOT being returned and thus the code blows up.
=> Change event_Type_ID to event_type

CI/SQL/20170111_140442_US6418-UpdateSearchGroupsToIncludeMultipleTypes.sql
Note: Small groups never get set to full.
=> US6316: Don't show full groups in search results:

CI/TestSQL/02.TestData/MidgarTrip.sql
Fixed a syntax error (semicolon needed to go AFTER the paren) and added a space before (Trip Participants) when linking a group to the event.
=> Fixed a syntax error and added a space in the group linking section

crossroads.net/package.json
This PR locks the `crds-styles` dependency to version to 0.0.11 per @charlie-retzler
Let me know if you have any questions. Thanks!
=> US6445 CRDS Styles Version

crossroads.net/app/routes.js
In a previous merge, app/routes.js was changes to fix the superbowl route and somehow the route for impersonate was removed. This pull request adds the route for impersonate back to app/routes.js which enables the impersonate link in the profile hamburger menu to work correctly again.
=> DE2678: Fix impersonate link

CI/SQL/20170120101700_DE2488-default-event-room-capacity.sql
I dont think this should cause any issues as we added the Capacity and Volunteers columns this past September
=> DE2488: capacity, volunteers default value to 0

CI/SQL/20170208_181742_DE2736-FixFilter.sql
So that if you have a meeting from 12:00 - 1:00 PM it doesn't show as booked at 1:00pm for the next meeting to start.
=> Don't take the first and last minutes of a meeting into account DE2749

CI/TestSQL/02.TestData/BedrockTrip.sql, CI/TestSQL/03.TestConfigData/GoBedrockParticipants.sql, CI/TestSQL_TearDown/02.Teardown_MPData/BedrockTrip.sql
Items were failing to be created properly because the sizing of the variable was truncating the data.
=> Changed size of @tripname to varchar(24) to account for longer string

crossroads.net/app/camps/application_page/camp_waivers/camp_waivers.controller.js, crossroads.net/app/camps/application_page/medical_info/medical_info.controller.js, crossroads.net/app/camps/camps.routes.js, crossroads.net/spec/camps/application_page/camps_medical_info/camps_medical_info.component.spec.js
When in normal registration flow hitting back to go the medical info
page shouldn't disturb the workflow but hitting back when you started at
the dashboard should take you back to the dashboard.
=> DE2737 Medical info page redirects correctly

CI/TestSQL_TearDown/02.Teardown_MPData/TD_SignUpToServe_TestData.sql
* For '(t) KidsClub Oakley Group' the script is now removing opportunities
attach to it.
* For '(t) Superbowl Oakley Group' add a line to remove any event participant attach to it.
=> Removing dependent data from KC & Superbowl test groups

crossroads.net/core/services/CMS.service.js, crossroads.net/core/services/CMSData.service.ts, crossroads.net/spec-es6/core/CMS.service.spec.js
elixir was barfing when trying to parse urls with `[]` in them. the
easiest solution was to remove them, as they didn't seem to matter.
if they really do matter, then we can find a way to deal with them, but
I don't think they are a standard.
=> remove `[]` from cms urls

CI/SQL/20170119_124900_US6243-create-duplicate-phone-sp.sql
If the report takes too long it will time out without saying so. Reduced
records returned in order to make the report run faster.
=> DE2795 Reduced records returned

crossroads.net/core/services/session_service.js, crossroads.net/spec-core/services/session.service.spec.js
Corrects timing/eventing issue in session_service where "redirectIfNeeded" not working correctly from mobile device or desktop going directly to "/signout."
=> session_service redirectIfNeeded logic in new event loop

CI/SQL/20170224-074700_DE2802-UpdatePageEmailsPage.sql
Selected record expression was causing the result to be filtered be Contacts.Email_Address when processing via the code, which led to processing problems.  Because we really want to check that the user is not already in the system, checking against the Users table is more accurate.
=> DE2802 change page to be from the users table

crossroads.net/app/go_volunteer/goVolunteer.routes.js, crossroads.net/app/go_volunteer/page/anywhereProfileConfirm/goVolunteerAnywhereProfileConfirm.component.js, crossroads.net/app/go_volunteer/page/anywhereProfileConfirm/goVolunteerAnywhereProfileConfirm.controller.js, crossroads.net/app/go_volunteer/page/anywhereProfileConfirm/goVolunteerAnywhereProfileConfirm.html, crossroads.net/app/go_volunteer/page/anywhereProfileConfirm/index.js, crossroads.net/app/go_volunteer/page/index.js, crossroads.net/app/go_volunteer/projectCard/goVolunteerProjectCard.html, crossroads.net/styles/pages/go-volunteer.scss
Associated CMS pull request:  https://github.com/crdschurch/SS-CMS/pull/257
URL:  /go-local/3/crossroads/Cleveland/564/confirm
* Creates component and route
* Use content block for informative text
* Display project card and project leader's email address
=> US7077 - GO Local anywhere profile confirmation

Gateway/Crossroads.Utilities.Test/Services/ContentBlockServiceTest.cs, Gateway/Crossroads.Utilities/Interfaces/IContentBlockService.cs, Gateway/Crossroads.Utilities/Models/ContentBlock.cs, Gateway/Crossroads.Utilities/Services/ContentBlockService.cs, Gateway/MinistryPlatform.Translation/Repositories/GroupRepository.cs
* Modify ContentBlockService to change Category to a string instead of enum so that adding new categories in CMS in the future does not cause parsing errors in crds-angular.
* Do not throw an exception in GroupRepository.SendCommunityGroupConfirmationEmail if CMS data is missing/unavailable.
* Add more tests.
=> DE2902: Group signup fails due to error parsing CMS content

crossroads.net/app/go_volunteer/organizations/organizations.template.html, crossroads.net/styles/pages/go-volunteer.scss
CMS page has lorem ipsum until official content is specified
=> US6595 - Discover Opportunities Page

CI/TestSQL_TearDown/02.Teardown_MPData/TD_SignUpToServe_TestData.sql
This is so the test groups can be deleted in the tear down scripts
=> Added code to delete group attributes from the test groups

crossroads.net/app/go_volunteer/page/goVolunteerPage.component.js
This is leftover from using a custom login page. The old login page was
setting the proper value is sessionStorage. Since we no longer have that
custom login page, we can just assume that when we are on the profile
page, we're ok to proceed.
=> DE2953 Bad redirect

crossroads.net/app/go_volunteer/page/anywhereProfile/goVolunteerAnywhereProfile.html, crossroads.net/app/go_volunteer/page/anywhereProfileConfirm/goVolunteerAnywhereProfileConfirm.html, crossroads.net/core/templates/goCincinnati.html, crossroads.net/styles/pages/go-volunteer.scss
=> US6596 - GO Local Branding

CI/SQL/20170426_152812_DE3339-UpdateResetECheckEvent.sql
**Rally:** https://rally1.rallydev.com/#/27593764268d/detail/defect/110658791192
**Build:** http://mp-ci.centralus.cloudapp.azure.com/viewType.html?buildTypeId=Code_Development_Crossroads_Defect&branch_Code_Development_Crossroads=defect%2FDE3339-FixToOnlyResetEventGroupsOfAgeGrade&tab=buildTypeStatusDiv
=> Fix to only delete age grade event groups.

crossroads.net/app/index.html, crossroads.net/styles/main.scss
This reduces the time spent in `gulp build` from 4.64 min to 1.42 min.
=> DEXXXX Long Build Times

crossroads.net/app/live_stream/landing/landing.html, crossroads.net/styles/pages/streaming.scss
Only use one content block for the connect promo section.
Per Brian's request, this transitions from using several content blocks to a single one, mostly so the background image can be controlled through the CMS.
=> US8190 - Connect Promo

CI/SQL/20170531_095800_US8121-end-date-group-participant-attributes.sql, CI/SQL/20170531_100500_US8121-group-participant-end-date-cleanup.sql
* New trigger that will sync End_Date in Group_Participant_Attributes
* New index on Group_Participant_Attributes to ensure the trigger is efficient
* One-time query to clean up existing data
=> US8121 - Clean up End_Date for Group Participant Attributes

Gateway/MinistryPlatform.Translation.Test/Services/EventServiceTest.cs, Gateway/MinistryPlatform.Translation/Repositories/ChildcareRequestRepository.cs, Gateway/MinistryPlatform.Translation/Repositories/EventRepository.cs, Gateway/MinistryPlatform.Translation/Repositories/Interfaces/IEventRepository.cs, Gateway/crds-angular.test/Services/ServeServiceTest.cs
* Replace SOAP call with REST so we can do filtering in the query itself and return less data.
=> DE3565 - Exclude cancelled events from Childcare Decision tool

crossroads.net/core/core.controller.js
Unless explicitly false from CMS, render legacy styles
=> DE3293 - Legacy Styles on Give Pages

Gateway/crds-angular.test/controllers/StripeEventControllerTest.cs, Gateway/crds-angular/Controllers/API/StripeEventController.cs
* Added [IgnoreClientApiKey] on the stripe webhook handler - Stripe can't send any custom headers, so we need to allow "keyless" requests
* Also cleaned up some ReSharper warnings
=> US8694: Ignore client API keys in Stripe Webhook Handler

crossroads.net/core/core.run.js, crossroads.net/styles/legacy.scss
Addresses the following defect:
Logged in or out on iOS devices.
The main menu, as well as the menu under My Profile the page only partially loads (you can't scroll) unless you refresh. 
Notes from Tate:
it looks like at some point the class 'noscroll' is getting added to the body. When that happens, the page content is cut off and you can't scroll down the page. From my testing, it seems to show up when you go to the login form. It doesn't matter if you log in or not from that point.
Looking at the legacy.scss file, the .noscroll stuff is right in the file
=> DE3793 - Mobile iOS Scroll [Hotfix]

crossroads.net/app/index.html, crossroads.net/core/core.run.js, crossroads.net/environment.config.js
In conjunction with crdschurch/crds-shared-header#57, this fixes the profile picture issue, as well as unnecessarily re-rendering the header.
**Note that we don't want to merge this until 0.4.2 of the header is released.**
=> DE3845 - Profile Picture

crossroads.net/app/index.html
This PR updates the shared header to it's latest version which resolves [DE3856: Click Area on Mobile Profile Nav](https://rally1.rallydev.com/#/66096747656d/detail/defect/133684844556).
This is related to crdschurch/crds-maestro#181 and crdschurch/crds-shared-header#62.
=> DE3856 mobile nav click area

crossroads.net/app/routes.content.js, crossroads.net/app/routes.js, crossroads.net/core/core.controller.js
This PR hotfixes the release branch to resolve a style regression in the /profile section of the site, introduced via [DE3879](https://rally1.rallydev.com/#/66096747656d/detail/defect/134433728664?fdp=true). 
Let me know if you have any questions.
=> hotfix/DE3956 - Styles Removed on State Change

CI/Reports/CRDS ContributionStatement.rdl, CI/SQL/20170805_122800_DE4021-fix-paper-statements.sql
DE4027 - Fix for missing donations caused by using UNION instead of UNION ALL
DE4028 - Show each stock donation once regardless of number of distributions
DE4042 - Include donors who are missing a Household record or have NULL Congregation ID (treat as Not Site Specific)
Fix typo in SQL - 'No Description Given'
=> DE4021 - Show donations made via directed giving in the Tax Deductible section

crossroads.net/app/trips/trippromise/tripPromise.html
The purpose of this pull request is to update the error message displayed when a user does not check the box before attempting to submit the I Promise document for their trip. 
The previous message was: 
> Please enter a value.
And the new message is:
> Please check the box to confirm you read the I Promise statement.
Please view the PR for the defect/DE4897-IPromiseRequired branch in the SS-CMS repository for the actual content block.
=> DE4087 update error message to make @angiemama happy

CI/TestSQL/02.TestData/BedrockTrip.sql, CI/TestSQL/02.TestData/MidgarTrip.sql, CI/TestSQL_TearDown/02.Teardown_MPData/BedrockTrip.sql, CI/TestSQL_TearDown/02.Teardown_MPData/MidgarTrip.sql
Script now removes any events manually added to the Go Midgar program.
=> Fix to test teardown script

Gateway/MinistryPlatform.Translation.Test/Services/GroupParticipantRepositoryTest.cs
An nunit test [failed on the build server](http://mp-ci.centralus.cloudapp.azure.com/viewLog.html?buildId=34105&buildTypeId=MicroClients_Integration_BuildAndTest_CrdsAngular&tab=buildLog#_focus=17699), but worked successfully on the next run, without changes.  Further investigation showed that the way the test was written, a DateTime expectation could occasionally fail if the test fixture did not execute within the same second the expectation was set.  Updated the test (and others with the same issue) to consider the test successful if the expected date is within 60 seconds of the actual date.
=> Fix broken unit test

crossroads.net/core/templates/screenWidth.html
Remove the fluid container, which added unnecessary padding.
I'm worried this change will introduce regressions on other pages using the Screen Width template, but a list of which pages those are isn't readily available, so I'm not exactly sure how we go about regression testing.
Also note that, for now, the testing should be done at `/ddk-reskin/serve`. The main serve page will be changed after this is merged and after the proper channels are notified.
=> US10378 - Reskin /serve

crossroads.net/core/passwordField/passwordField.html
I accidentally removed an ID from the password field during the original reskin. This ID was important for automated testing and I received a request from Jason to reimplement it.
Reimplementing the original ID attribute to the password input. Not sure how to test this...
=> DE4616 - Missing password ID

crossroads.net/app/routes.content.js
[US10576](https://rally1.rallydev.com/#/27593501023d/detail/userstory/167807083760) -> Use Maestro to display the form instead of an iframe. This fix in particular addresses the fact that when crds-angular loads, it never kicks back out to maestro. 
- When the cms route is hit within crds-angular, determine if it requires angular. If it does not, call the cms page externally.
=> US10576 redirect if angular is not needed

crossroads.net/core/register/register_page.html
Add class to account for shared header on /register. The background now scrolls.
=> DE4669 - Register bg bug

crossroads.net/app/camps/application_page/camper_info/camper_info_form.service.js
The purpose of this PR is to update two labels on the Student Camp application.
Was:
Updated to:
=> ajcolub/US10932 - update labels on student camp application

crossroads.net/core/passwordField/passwordField.html
The password field is a shared component being pulled in on pages that haven't been reskinned. To prevent ugliness, I'm wrapping the markup of this particular component in a div with crds-styles applied.
Not sure if this is the cleanest implementation or how it'll impact load times on any screens with a password field. Please provide thorough pushback/alternate solutions because this feels like it could be handled better.
=> DE4720 - Session timeout password field

CI/TestSQL/02.TestData/MP_TestPledgeCampaign.sql
Test pledges were not avaialable to give to. This is because thier
end date was last year. The SQL script to create the pledges and
programs was setting all programs to end at the end of the year.
This SQL script is not ran very often and usually never ran at the
begining of the year. So I changed the script to always end date the
programs two years 2 years out.
=> Setting Program end dates to 2 years out

crossroads.net/styles/base/typography.scss
Remove antialias smoothing on typography. This was causing a discrepancy between fonts within Angular/Maestro and all other properties.
=> US10238 - Jumbotron on Live

crossroads.net/app/giving_history/history.html
Without this change, the Years dropdown is not clickable when the window width is reduced to bootstrap's "small" breakpoint (more frequent on mobile).
=> DE5056 - Hack z-order for Years dropdown so it works on mobile

CI/TestSQL/00.PowershellScripts/DeleteTestData.ps1, CI/TestSQL/00.PowershellScripts/LoadTestData.ps1, CI/TestSQL/01.TestUsers/01.Contact+Relationship/CreateContactsAndRelationships.ps1, CI/TestSQL/01.TestUsers/02.Donor/CreateDonors.ps1, CI/TestSQL/01.TestUsers/03.Participant/CreateParticipants.ps1, CI/TestSQL/01.TestUsers/04.Household+Address/CreateHouseholdsAndAddresses.ps1, CI/TestSQL/01.TestUsers/DeleteTestUsers.ps1, CI/TestSQL/02.TestData/01.Batch+Deposit/CreateDepositsAndBatches.ps1, CI/TestSQL/02.TestData/01.Batch+Deposit/DeleteDepositsAndBatches.ps1, CI/TestSQL/02.TestData/02.Program/CreatePrograms.ps1, CI/TestSQL/02.TestData/02.Program/DeletePrograms.ps1, CI/TestSQL/02.TestData/03.Group+Attribute/CreateAttributes.csv, CI/TestSQL/02.TestData/03.Group+Attribute/CreateGroupAttributes.csv, CI/TestSQL/02.TestData/03.Group+Attribute/CreateGroupsAndAttributes.ps1, CI/TestSQL/02.TestData/03.Group+Attribute/DeleteGroupsAndAttributes.ps1, CI/TestSQL/02.TestData/04.Event+EventType/CreateEventsAndEventTypes.ps1, CI/TestSQL/02.TestData/04.Event+EventType/DeleteEventsAndEventTypes.ps1, CI/TestSQL/02.TestData/05.Opportunity+Response/CreateOpportunitiesAndResponses.ps1, CI/TestSQL/02.TestData/05.Opportunity+Response/DeleteOpportunities.ps1, CI/TestSQL/02.TestData/06.PledgeCampaign+Pledge/CreatePledgeCampaignsAndPledges.ps1, CI/TestSQL/02.TestData/06.PledgeCampaign+Pledge/DeletePledgeCampaigns.ps1, CI/TestSQL/02.TestData/07.Donation+Distribution/CreateDonations.ps1, CI/TestSQL/02.TestData/08.Invoice+Payment/CreateInvoicesAndPayments.ps1, CI/TestSQL/02.TestData/09.EventParticipants+GroupParticipants/CreateEventAndGroupParticipants.ps1
- Previously, if an entry could not be created in MP, the remaining entries in the same file would be skipped. With this update, the script will attempt to create all data in the file and report a failing exit code at the end if anything could not be created.
- The master file called by TC will now report a failing exit code if any entry could not be created so TC can be configured to stop the build.
[TeamCity run ](http://mp-ci.centralus.cloudapp.azure.com/viewLog.html?buildId=44740&buildTypeId=Qa_Release_TeardownAndReloadTestData&tab=buildLog#_state=64)where failed teardown stops further steps.
Bonus:
- Fixed a group attribute configuration
Todo:
- The failure is an actual bug that needs to be fixed, but it does demo the exit codes added in this PR work. Bug will be fixed in a future …
=> feature/us12539 - TD/RL better error handling

CI/TestSQL/00.TeardownStoredProcs/03.DeleteData_Event_and_Event_Type_StoredProc.sql
- Fixes the delete event stored proc so that parent_event_id is null before deleting. Won't always delete otherwise.
=> defect/de5110 - Delete event error fix

CI/TestSQL/02.TestData/04.Event+EventType/CreateEvents.csv, CI/TestSQL/02.TestData/04.Event+EventType/Special Cases.txt, CI/TestSQL/02.TestData/04.Event+EventType/Stored Procs/03.CreateData_CreateEvent_StoredProc.sql
- Noticed that some event types in Int are prefixed with a * where Demo and Prod are not. This PR allows create event to search for event types with different prefixes if exact match not found.
[TeamCity run](http://mp-ci.centralus.cloudapp.azure.com/viewQueued.html?itemId=44984&buildTypeId=Qa_Release_TeardownAndReloadTestData&tab=buildLog) from this branch.
=> Defect/dewxyz - Loosen event type search

crossroads.net/app/profile/communications/profileCommunications.html
Due to some serious hoops we'd have to jump through, crds is opting to notify the user about their email preferences through Hubspot's custom generated prefs page found in an email instead of using an embedded toggle solution.
There is a content block called `profileEmailCommunications` that angular draws from to get this content.
=> US12479: Email Subscription Messaging

Gateway/MinistryPlatform.Translation/Repositories/RoomRepository.cs
The legacy Create/Edit tool should only show layouts where Room_ID is null.  This will allow us to populate the Room_Layouts table with additional room-specific layouts for the new Create/Edit tool that resides in the crds-mp-tools repo without impacting the legacy Create/Edit tool.
=> US12063 - Use MP REST API and filter layouts based on null Room_ID

crossroads.net/core/services/session_service.js
The redirectUrl cookie currently does not support going to absolute URL's, so checking to see if string starts with http/https and using $window.location to go directly to it.
=> US12746: use $window.location for absolute urls for redirecting via cookie

CI/SQL/20180716_090000_US13212-assign-pledges-nightly.sql
This fixes automation tests that create donations and then immediately run the stored proc.  The UTC vs. local discrepancy isn't an issue outside of automation because any donations that fall outside the date range will get processed on the next day.
=> US13212 - Use UTC instead of local for end date because some donations are UTC

Gateway/crds-angular.test/Services/LoginServiceTest.cs, Gateway/crds-angular/Controllers/API/LoginController.cs, Gateway/crds-angular/Services/Interfaces/ILoginService.cs, Gateway/crds-angular/Services/LoginService.cs, crossroads.net/app/common/profile/personal/confirmPassword.controller.js, crossroads.net/app/common/profile/personal/profilePersonal.controller.js, crossroads.net/core/services/password_service.js
* Add a new endpoint that verifies the combination of token + old password instead of email address + old password
* Update front-end code to use the new endpoint.
=> US14573 - Password Confirmation should work without Contact email address

CI/TestSQL/StandardScripts/00.TeardownStoredProcs/15.DeleteData_Contact_StoredProc.sql
- Removed disable/enable contact_relationships trigger from delete contact stored proc - it doesn't seem to be needed anymore and was causing problems
=> feature/US-QA-TDRL - Fixed Delete Contact stored proc

CI/SQL/20180810_112200_DE5763-event-setup-report-missing-events.sql
Fixed the following issues:
* The report would fail to show an event if the event had at least one active room reservation with only cancelled equipment reservations (i.e., no active equipment reservations).
* The report would sometimes show room reservations and/or equipment reservations that had been cancelled.
* Filtering by Room would sometimes show other rooms not matching the filter.
* Data errors were not always handled consistently.  Equipment reservations that are linked to the event, but not linked with an active room reservation for the event should show on the report to call attention to incorrect data.
=> DE5763 - Event setup report missing events

CI/SQL/20180814_140200_US11219-update-nightly-email-sync.sql
* Ignore Contact records where the email address is an empty string.
* If the audit log indicates multiple changes to the same record, report the most recent change.
=> US11219 - Dont sync empty email

Gateway/Crossroads.ScheduledDataUpdate/App.config, Gateway/MinistryPlatform.Translation/app.config
* ScheduledDataUpdate fails to run due to a missing dependency (System.Net.Http version 4.2)
=> DExxxx - Hotfix for System.Net.Http version mismatch

Gateway/crds-angular.test/crds-angular.test.csproj, Gateway/crds-angular.test/packages.config, Gateway/crds-angular/crds-angular.csproj, Gateway/crds-angular/packages.config
Adds logic to automatically retry loading client api keys if the first attempt fails.
=> US14767 - Update crds-client-api-keys to v2.0.7

crossroads.net/core/crds_utilities.js, crossroads.net/core/login/login_controller.js, crossroads.net/core/login/login_form.html
Currently, if the user is logged in, and goes to the `/signin` page, they stay on the page infinitely - there is no logic to redirect them to where they need to go. 
Solution: Check if the user is properly logged in (can't do a quick check here because any error would keep the user from able to access the login page). If they are logged in and their session is valid, redirect them to their destination or the homepage.
=> DE5915 Redirect User Away From Login if Already Signed In

crossroads.net/app/search/search-results.html
added target=_self to search results html to cause links to exit angular
Angular was not hitting netlify from the link in the search results. Any pages that were served from contentful/jekyll were hitting the not found page when they actually existed.
=> DE6032 Search Results incorrectly displaying not found page

CI/TestSQL/StandardScripts/02.TestData/02.Program+Product/CreatePrograms.csv, CI/TestSQL/StandardScripts/02.TestData/04.Event+EventType/CreateEvents.csv, CI/TestSQL/StandardScripts/02.TestData/06.PledgeCampaign+Pledge/CreatePledgeCampaigns.csv, CI/TestSQL/StandardScripts/02.TestData/06.PledgeCampaign+Pledge/CreatePledges.csv, CI/TestSQL/StandardScripts/02.TestData/09.EventParticipants+GroupParticipants/CreateEventParticipants.csv, CI/TestSQL/StandardScripts/02.TestData/09.EventParticipants+GroupParticipants/CreateGroupParticipants.csv
I had to change the dates on some of the trips, events and participants because they were dated 2018 and I needed them to be 2019 to reflect the new year.
=> Update to Test Date to Change the Dates

Gateway/MinistryPlatform.Translation/Models/MpContactDonor.cs, Gateway/MinistryPlatform.Translation/Repositories/DonorRepository.cs
- Make Statement a nullable int so stored proc does not blow up
- Have GetDonorStatment return null if a donor id does not exists
=> Make GetDonorStatments return without an exception if user does not have a donor record

Gateway/crds-angular/Security/ImpersonateAuthBaseController.cs
Moving logic to refresh expired tokens from after the request to the auth service to before the request to the auth service.
=> Logic in the new base controller to allow refreshing expired tokens

Gateway/MinistryPlatform.Translation/Repositories/UserRepository.cs
This is a hotfix, there is a comma hard coded into the parameters for _ministryPlatformService.GetRecordsDict line 187 of the UserRepository. This comma is being appended to the beginning of the email address, and when it is being searched for in the Users table in MP 0 results are returned because of the comma at the beginning of the string. I have merged into Development and all unit test passed, as well as running the code locally the password reset created a draft in MP.
=> HotFix Removed comma from email search

.gitignore, Gateway/crds-angular.api_test/cypress/config/vault_config.json, Gateway/crds-angular.api_test/cypress/integration/LoginController/POST_login_prodspec.ts, Gateway/crds-angular.api_test/cypress/integration/LoginController/POST_requestpasswordreset_mobile_spec.ts, Gateway/crds-angular.api_test/cypress/integration/LoginController/POST_requestpasswordreset_spec.ts, Gateway/crds-angular.api_test/cypress/integration/LoginController/POST_versioned_request-password-reset-mobile_prodspec.ts, Gateway/crds-angular.api_test/cypress/integration/LoginController/POST_versioned_request-password-reset_prodspec.ts, Gateway/crds-angular.api_test/cypress/integration/LoginController/schemas/unsupportedMediaResponse.ts, Gateway/crds-angular.api_test/cypress/shared/test_scenario_factory.ts, Gateway/crds-angular.api_test/cypress/shared/users.ts, Gateway/crds-angular.api_test/cypress/support/commands.ts, Gateway/crds-angular.api_test/cypress/support/index.ts, Gateway/crds-angular.api_test/cypress/support/responseCommands.ts, Gateway/crds-angular.api_test/docker/docker-compose.yml, Gateway/crds-angular.api_test/tsconfig.json
- Added coverage for 4 endpoints:
POST /api/v{apiVersion}/request-password-reset
POST /api/requestpasswordreset
POST /api/v{apiVersion}/request-password-reset-mobile
POST /api/requestpasswordreset/mobile
- Created a folder in Vault specifically for this project and added secrets to it (added in all environments)
- Created Cypress commands to handle all the assertions made against responses. These commands can be found in `cypress/support/responseCommands.ts` and are automatically loaded into each test file - no import needed.
- Moved all test user data to `cypress/shared/users.ts` with notes about their requirements. 
- Restructured configs for "defining" test scenarios in a compact manner. New version follows the same basic idea but some property names and function calls have changed. …
=> feature/US20246 - API tests for request password reset

Gateway/crds-angular.api_test/cypress.json, Gateway/crds-angular.api_test/cypress/config/demo_e2e.json, Gateway/crds-angular.api_test/cypress/config/int_e2e.json, Gateway/crds-angular.api_test/cypress/config/prod_e2e.json, Gateway/crds-angular.api_test/cypress/config/vault_config.json, Gateway/crds-angular.api_test/cypress/e2e/login_and_authenticate_prodspec.ts, Gateway/crds-angular.api_test/cypress/integration/LoginController/GET_authenticated_oktaauth_spec.ts, Gateway/crds-angular.api_test/cypress/integration/LoginController/GET_authenticated_prodspec.ts, Gateway/crds-angular.api_test/cypress/integration/LoginController/POST_login_prodspec.ts, Gateway/crds-angular.api_test/cypress/integration/LoginController/POST_requestpasswordreset_mobile_spec.ts, Gateway/crds-angular.api_test/cypress/integration/LoginController/POST_requestpasswordreset_spec.ts, Gateway/crds-angular.api_test/cypress/integration/LoginController/POST_resetpassword_spec.ts, Gateway/crds-angular.api_test/cypress/integration/LoginController/POST_versioned_request-password-reset-mobile_prodspec.ts, Gateway/crds-angular.api_test/cypress/integration/LoginController/POST_versioned_request-password-reset_prodspec.ts, Gateway/crds-angular.api_test/cypress/integration/LoginController/schemas/authenticatedResponse.ts, Gateway/crds-angular.api_test/cypress/shared/authorization/mp_client_auth.ts, Gateway/crds-angular.api_test/cypress/shared/authorization/mp_user_auth.ts, Gateway/crds-angular.api_test/cypress/shared/authorization/okta_user_auth.ts, Gateway/crds-angular.api_test/cypress/shared/mp_api.ts, Gateway/crds-angular.api_test/cypress/shared/test_scenario_factory.ts
- Added API tests for /authenticated
- Reworked TestConfig structure and conversion to be more flexible and allow for async retrieval of values (like requesting auth token via api)
- Added user authentication through Okta and MP, and isolated client authentication through MP. Note that Okta authentication cannot currently be done in the Prod environment for test users.
- Added e2e test for login and authenticated workflow
- Created a Cypress dashboard project for e2e tests
=> feature/US20275 - API tests for /authenticated endpoint

Gateway/crds-angular.api_test/cypress/api_tests/LoginController/GET_authenticated_mpauth_prodspec.ts, Gateway/crds-angular.api_test/cypress/api_tests/LoginController/GET_authenticated_oktaauth_spec.ts, Gateway/crds-angular.api_test/cypress/api_tests/LoginController/GET_verifyresettoken_spec.ts, Gateway/crds-angular.api_test/cypress/api_tests/LoginController/POST_login_prodspec.ts, Gateway/crds-angular.api_test/cypress/api_tests/LoginController/POST_requestpasswordreset_mobile_prodspec.ts, Gateway/crds-angular.api_test/cypress/api_tests/LoginController/POST_requestpasswordreset_mobile_spec.ts, Gateway/crds-angular.api_test/cypress/api_tests/LoginController/POST_requestpasswordreset_prodspec.ts, Gateway/crds-angular.api_test/cypress/api_tests/LoginController/POST_requestpasswordreset_spec.ts, Gateway/crds-angular.api_test/cypress/api_tests/LoginController/POST_resetpassword_spec.ts, Gateway/crds-angular.api_test/cypress/api_tests/LoginController/POST_verifycredentials_spec.ts, Gateway/crds-angular.api_test/cypress/config/vault_config.json, Gateway/crds-angular.api_test/cypress/shared/authorization/mp_user_auth.ts, Gateway/crds-angular.api_test/cypress/shared/authorization/okta_user_auth.ts, Gateway/crds-angular.api_test/cypress/shared/test_scenario_factory.d.ts, Gateway/crds-angular.api_test/cypress/shared/test_scenario_factory.ts, Gateway/crds-angular.api_test/cypress/shared/users.ts
- Added new tests for POST /api/verifycredentials
- Standardized and made required the `data` property so it's the same in both the TestConfig and Test objects
- Added a wrapper for MP and Okta user auth that adds the Authentication token to a given request
=> feature/US20458 - API test for POST /verifycredentials

Gateway/MinistryPlatform.Translation/Repositories/ContactRepository.cs, Gateway/MinistryPlatform.Translation/Repositories/UserRepository.cs, Gateway/crds-angular.api_test/cypress/api_tests/LoginController/POST_requestpasswordreset_mobile_spec.ts, Gateway/crds-angular.api_test/cypress/api_tests/LoginController/POST_requestpasswordreset_spec.ts, Gateway/crds-angular.api_test/cypress/api_tests/UserController/GET_user_spec.ts, Gateway/crds-angular.api_test/cypress/api_tests/UserController/POST_user_spec.ts, Gateway/crds-angular.api_test/cypress/shared/users.ts
- When searching for a user or contact by email, records found will be filtered to exactly match the email given before throwing an error if multiple records are found.
- API tests were updated
=> defect/DE8140 - Fix when person has email that is substring of email

Gateway/crds-angular.api_test/cypress/api_tests/ProfileController/GET_profile_spec.ts, Gateway/crds-angular.api_test/cypress/api_tests/ProfileController/schemas/errorResponseSchemas.ts, Gateway/crds-angular.api_test/cypress/api_tests/ProfileController/schemas/getProfileSchema.ts, Gateway/crds-angular.api_test/cypress/shared/mp_api.ts, Gateway/crds-angular.api_test/cypress/shared/mp_models.d.ts, Gateway/crds-angular.api_test/cypress/shared/users.ts, Gateway/crds-angular.api_test/cypress/support/index.ts, Gateway/crds-angular/Controllers/API/ProfileController.cs, Gateway/crds-angular/Services/UserImpersonationService.cs
- Added API test for GET /api/profile endpoint
- Extracted MP models into their own typedef file
- Separated the impersonation logic from the non-impersonation logic in the GET /api/profile endpoint to make it a bit easier to follow.
- Added some validation logic in UserImpersonationService.DoImpersonation to prevent looking for a "null" user. This scenario was already handled gracefully deeper in the code, but only after wasting a lot of effort querying MP.
=> Feature/US20476 - Adds API tests for GET /api/profile

Gateway/crds-angular.api_test/cypress/api_tests/LookupController/GET_lookup_find_spec.ts, Gateway/crds-angular.api_test/cypress/api_tests/LookupController/schemas/exceptionResponseSchemas.ts, Gateway/crds-angular.api_test/cypress/api_tests/ProfileController/POST_profile_nodemospec.ts, Gateway/crds-angular.api_test/cypress/config/api/demo.json, Gateway/crds-angular.api_test/cypress/shared/authorization/mp_client_auth.ts, Gateway/crds-angular.api_test/cypress/shared/mp_models.d.ts, Gateway/crds-angular/Controllers/API/LookupController.cs
- Added API tests for LookupController's GET /lookup/{id}/find?email={email} endpoint
- Added filter to skip tests that can't be run in demo. This is a temporary workaround to skip POST /profile tests since data isn't correctly set up. These tests will still be run in Int.
- Simplified logic in LookupController.EmailExists and removed code that wasn't cleaned up after an old refactor
- Modified how the endpoint Route is defined to improve clarity and for Swagger accuracy. Swagger now correctly reports that email is a query parameter (previously it was inline) and the misleading `userId` variable was renamed to `contactId`.
- Removed dead code and unneeded constructor parameters from the LookupController class.
=> feature/US20654 - API tests for GET /lookup/{id}/find?email={email}
